/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Optparser174011 Optparser174011;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Optparser174011  {
  TNimObject Sup;
NimStringDesc* cmd;
NI pos;
NIM_BOOL inshortstate;
NU8 kind;
NimStringDesc* key;
NimStringDesc* val;
};
typedef NU8 TY77659[32];
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, initoptparser_174030)(NimStringDesc* cmdline, Optparser174011* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, paramcount_125830)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, quoteifcontainswhite_99340)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, paramstr_125809)(NI i);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, parseword_174204)(NimStringDesc* s, NI i, NimStringDesc** w, TY77659 delim);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, handleshortoption_174291)(Optparser174011* p);
N_NIMCALL(void, nponext)(Optparser174011* p);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NimStringDesc*, npocmdLineRest)(Optparser174011* p);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
STRING_LITERAL(TMP1830, "", 0);
STRING_LITERAL(TMP1834, "", 0);
static NIM_CONST TY77659 TMP1843 = {
0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST TY77659 TMP1847 = {
0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x24,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
extern TFrame* frameptr_17042;
extern TNimType NTI3411; /* RootObj */
TNimType NTI174011; /* OptParser */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
extern TNimType NTI138; /* bool */
TNimType NTI174009; /* CmdLineKind */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, initoptparser_174030)(NimStringDesc* cmdline, Optparser174011* Result) {
	nimfr("initOptParser", "parseopt.nim")
	nimln(52, "parseopt.nim");
	(*Result).pos = ((NI) 0);
	nimln(53, "parseopt.nim");
	(*Result).inshortstate = NIM_FALSE;
	nimln(54, "parseopt.nim");
	{
		if (!!(((cmdline) && (cmdline)->Sup.len == 0))) goto LA3;
		nimln(55, "parseopt.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), copyString(cmdline));
	}
	goto LA1;
	LA3: ;
	{
		nimln(57, "parseopt.nim");
		unsureAsgnRef((void**) (&(*Result).cmd), copyString(((NimStringDesc*) &TMP1830)));
		{
			NI i_174046;
			NI HEX3Atmp_174049;
			NI res_174052;
			i_174046 = 0;
			HEX3Atmp_174049 = 0;
			nimln(58, "parseopt.nim");
			HEX3Atmp_174049 = paramcount_125830();
			nimln(1598, "system.nim");
			res_174052 = ((NI) 1);
			{
				nimln(1599, "system.nim");
				while (1) {
					NimStringDesc* LOC9;
					NimStringDesc* LOC10;
					NimStringDesc* LOC11;
					NI TMP1833;
					if (!(res_174052 <= HEX3Atmp_174049)) goto LA8;
					nimln(1600, "system.nim");
					i_174046 = res_174052;
					nimln(59, "parseopt.nim");
					LOC9 = 0;
					LOC10 = 0;
					LOC10 = paramstr_125809(i_174046);
					LOC11 = 0;
					LOC11 = quoteifcontainswhite_99340(LOC10);
					LOC9 = rawNewString((*Result).cmd->Sup.len + LOC11->Sup.len + 1);
appendString(LOC9, (*Result).cmd);
appendString(LOC9, LOC11);
appendChar(LOC9, 32);
					unsureAsgnRef((void**) (&(*Result).cmd), LOC9);
					nimln(1614, "system.nim");
					TMP1833 = addInt(res_174052, ((NI) 1));
					res_174052 = (NI)(TMP1833);
				} LA8: ;
			}
		}
	}
	LA1: ;
	nimln(60, "parseopt.nim");
	(*Result).kind = ((NU8) 0);
	nimln(61, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).key), copyString(((NimStringDesc*) &TMP1834)));
	nimln(62, "parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).val), copyString(((NimStringDesc*) &TMP1834)));
	popFrame();
}

N_NIMCALL(NI, parseword_174204)(NimStringDesc* s, NI i, NimStringDesc** w, TY77659 delim) {
	NI result;
	nimfr("parseWord", "parseopt.nim")
	result = 0;
	nimln(66, "parseopt.nim");
	result = i;
	nimln(67, "parseopt.nim");
	{
		NI TMP1835;
		if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA3;
		nimln(68, "parseopt.nim");
		TMP1835 = addInt(result, ((NI) 1));
		result = (NI)(TMP1835);
		{
			nimln(69, "parseopt.nim");
			while (1) {
				NI TMP1836;
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!((((NU8)(s->data[result])) == ((NU8)(0)) || ((NU8)(s->data[result])) == ((NU8)(34))))) goto LA6;
				nimln(70, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				(*w) = addChar((*w), s->data[result]);
				nimln(71, "parseopt.nim");
				TMP1836 = addInt(result, ((NI) 1));
				result = (NI)(TMP1836);
			} LA6: ;
		}
		nimln(72, "parseopt.nim");
		{
			NI TMP1837;
			if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA9;
			TMP1837 = addInt(result, ((NI) 1));
			result = (NI)(TMP1837);
		}
		LA9: ;
	}
	goto LA1;
	LA3: ;
	{
		{
			nimln(74, "parseopt.nim");
			while (1) {
				NI TMP1838;
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!(((delim[((NU8)(s->data[result]))/8] &(1<<(((NU8)(s->data[result]))%8)))!=0))) goto LA13;
				nimln(75, "parseopt.nim");
				if ((NU)(result) > (NU)(s->Sup.len)) raiseIndexError();
				(*w) = addChar((*w), s->data[result]);
				nimln(76, "parseopt.nim");
				TMP1838 = addInt(result, ((NI) 1));
				result = (NI)(TMP1838);
			} LA13: ;
		}
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, handleshortoption_174291)(Optparser174011* p) {
	NI i;
	NI TMP1839;
	nimfr("handleShortOption", "parseopt.nim")
	nimln(79, "parseopt.nim");
	i = (*p).pos;
	nimln(80, "parseopt.nim");
	(*p).kind = ((NU8) 3);
	nimln(81, "parseopt.nim");
	if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
	(*p).key = addChar((*p).key, (*p).cmd->data[i]);
	nimln(82, "parseopt.nim");
	TMP1839 = addInt(i, ((NI) 1));
	i = (NI)(TMP1839);
	nimln(83, "parseopt.nim");
	(*p).inshortstate = NIM_TRUE;
	{
		nimln(84, "parseopt.nim");
		while (1) {
			NI TMP1840;
			if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
			if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA2;
			nimln(85, "parseopt.nim");
			TMP1840 = addInt(i, ((NI) 1));
			i = (NI)(TMP1840);
			nimln(86, "parseopt.nim");
			(*p).inshortstate = NIM_FALSE;
		} LA2: ;
	}
	nimln(87, "parseopt.nim");
	{
		NI TMP1841;
		if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
		if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(58)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(61)))) goto LA5;
		nimln(88, "parseopt.nim");
		TMP1841 = addInt(i, ((NI) 1));
		i = (NI)(TMP1841);
		nimln(89, "parseopt.nim");
		(*p).inshortstate = NIM_FALSE;
		{
			nimln(90, "parseopt.nim");
			while (1) {
				NI TMP1842;
				if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
				if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA8;
				TMP1842 = addInt(i, ((NI) 1));
				i = (NI)(TMP1842);
			} LA8: ;
		}
		nimln(91, "parseopt.nim");
		i = parseword_174204((*p).cmd, i, (&(*p).val), TMP1843);
	}
	LA5: ;
	nimln(92, "parseopt.nim");
	{
		if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
		if (!((NU8)((*p).cmd->data[i]) == (NU8)(0))) goto LA11;
		(*p).inshortstate = NIM_FALSE;
	}
	LA11: ;
	nimln(93, "parseopt.nim");
	(*p).pos = i;
	popFrame();
}

N_NIMCALL(void, nponext)(Optparser174011* p) {
	NI i;
	nimfr("next", "parseopt.nim")
{	nimln(98, "parseopt.nim");
	i = (*p).pos;
	{
		nimln(99, "parseopt.nim");
		while (1) {
			NI TMP1844;
			if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
			if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA2;
			TMP1844 = addInt(i, ((NI) 1));
			i = (NI)(TMP1844);
		} LA2: ;
	}
	nimln(100, "parseopt.nim");
	(*p).pos = i;
	nimln(101, "parseopt.nim");
	(*p).key = setLengthStr((*p).key, ((NI) 0));
	nimln(102, "parseopt.nim");
	(*p).val = setLengthStr((*p).val, ((NI) 0));
	nimln(103, "parseopt.nim");
	{
		if (!(*p).inshortstate) goto LA5;
		nimln(104, "parseopt.nim");
		handleshortoption_174291(p);
		nimln(105, "parseopt.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(106, "parseopt.nim");
	if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
	switch (((NU8)((*p).cmd->data[i]))) {
	case 0:
	{
		nimln(108, "parseopt.nim");
		(*p).kind = ((NU8) 0);
	}
	break;
	case 45:
	{
		NI TMP1845;
		nimln(110, "parseopt.nim");
		TMP1845 = addInt(i, ((NI) 1));
		i = (NI)(TMP1845);
		nimln(111, "parseopt.nim");
		{
			NI TMP1846;
			if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
			if (!((NU8)((*p).cmd->data[i]) == (NU8)(45))) goto LA11;
			nimln(112, "parseopt.nim");
			(*p).kind = ((NU8) 2);
			nimln(113, "parseopt.nim");
			TMP1846 = addInt(i, ((NI) 1));
			i = (NI)(TMP1846);
			nimln(114, "parseopt.nim");
			i = parseword_174204((*p).cmd, i, (&(*p).key), TMP1847);
			{
				nimln(115, "parseopt.nim");
				while (1) {
					NI TMP1848;
					if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
					if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA14;
					TMP1848 = addInt(i, ((NI) 1));
					i = (NI)(TMP1848);
				} LA14: ;
			}
			nimln(116, "parseopt.nim");
			{
				NI TMP1849;
				if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
				if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(58)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(61)))) goto LA17;
				nimln(117, "parseopt.nim");
				TMP1849 = addInt(i, ((NI) 1));
				i = (NI)(TMP1849);
				{
					nimln(118, "parseopt.nim");
					while (1) {
						NI TMP1850;
						if ((NU)(i) > (NU)((*p).cmd->Sup.len)) raiseIndexError();
						if (!(((NU8)((*p).cmd->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmd->data[i])) == ((NU8)(32)))) goto LA20;
						TMP1850 = addInt(i, ((NI) 1));
						i = (NI)(TMP1850);
					} LA20: ;
				}
				nimln(119, "parseopt.nim");
				(*p).pos = parseword_174204((*p).cmd, i, (&(*p).val), TMP1843);
			}
			goto LA15;
			LA17: ;
			{
				nimln(121, "parseopt.nim");
				(*p).pos = i;
			}
			LA15: ;
		}
		goto LA9;
		LA11: ;
		{
			nimln(123, "parseopt.nim");
			(*p).pos = i;
			nimln(124, "parseopt.nim");
			handleshortoption_174291(p);
		}
		LA9: ;
	}
	break;
	default:
	{
		nimln(126, "parseopt.nim");
		(*p).kind = ((NU8) 1);
		nimln(127, "parseopt.nim");
		(*p).pos = parseword_174204((*p).cmd, i, (&(*p).key), TMP1843);
	}
	break;
	}
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, npocmdLineRest)(Optparser174011* p) {
	NimStringDesc* result;
	NI TMP1854;
	NimStringDesc* LOC1;
	nimfr("cmdLineRest", "parseopt.nim")
	result = 0;
	nimln(131, "parseopt.nim");
	TMP1854 = subInt(((*p).cmd ? (*p).cmd->Sup.len : 0), ((NI) 1));
	LOC1 = 0;
	LOC1 = copyStrLast((*p).cmd, (*p).pos, (NI)(TMP1854));
	result = nsuStrip(LOC1, NIM_TRUE, NIM_TRUE);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseoptInit)(void) {
	nimfr("parseopt", "parseopt.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseoptDatInit)(void) {
static TNimNode* TMP10620[6];
static TNimNode* TMP10621[4];
NI TMP10623;
static char* NIM_CONST TMP10622[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode TMP1828[12];
NTI174011.size = sizeof(Optparser174011);
NTI174011.kind = 17;
NTI174011.base = (&NTI3411);
TMP10620[0] = &TMP1828[1];
TMP1828[1].kind = 1;
TMP1828[1].offset = offsetof(Optparser174011, cmd);
TMP1828[1].typ = (&NTI149);
TMP1828[1].name = "cmd";
TMP10620[1] = &TMP1828[2];
TMP1828[2].kind = 1;
TMP1828[2].offset = offsetof(Optparser174011, pos);
TMP1828[2].typ = (&NTI108);
TMP1828[2].name = "pos";
TMP10620[2] = &TMP1828[3];
TMP1828[3].kind = 1;
TMP1828[3].offset = offsetof(Optparser174011, inshortstate);
TMP1828[3].typ = (&NTI138);
TMP1828[3].name = "inShortState";
TMP10620[3] = &TMP1828[4];
NTI174009.size = sizeof(NU8);
NTI174009.kind = 14;
NTI174009.base = 0;
NTI174009.flags = 3;
for (TMP10623 = 0; TMP10623 < 4; TMP10623++) {
TMP1828[TMP10623+5].kind = 1;
TMP1828[TMP10623+5].offset = TMP10623;
TMP1828[TMP10623+5].name = TMP10622[TMP10623];
TMP10621[TMP10623] = &TMP1828[TMP10623+5];
}
TMP1828[9].len = 4; TMP1828[9].kind = 2; TMP1828[9].sons = &TMP10621[0];
NTI174009.node = &TMP1828[9];
TMP1828[4].kind = 1;
TMP1828[4].offset = offsetof(Optparser174011, kind);
TMP1828[4].typ = (&NTI174009);
TMP1828[4].name = "kind";
TMP10620[4] = &TMP1828[10];
TMP1828[10].kind = 1;
TMP1828[10].offset = offsetof(Optparser174011, key);
TMP1828[10].typ = (&NTI149);
TMP1828[10].name = "key";
TMP10620[5] = &TMP1828[11];
TMP1828[11].kind = 1;
TMP1828[11].offset = offsetof(Optparser174011, val);
TMP1828[11].typ = (&NTI149);
TMP1828[11].name = "val";
TMP1828[0].len = 6; TMP1828[0].kind = 2; TMP1828[0].sons = &TMP10620[0];
NTI174011.node = &TMP1828[0];
}

