/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct Tnode191813 Tnode191813;
typedef struct Ttype191849 Ttype191849;
typedef struct Tlineinfo163338 Tlineinfo163338;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Tsym191843 Tsym191843;
typedef struct Tident167021 Tident167021;
typedef struct Tnodeseq191807 Tnodeseq191807;
typedef struct Tidobj167015 Tidobj167015;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Ttypeseq191845 Ttypeseq191845;
typedef struct Tscope191837 Tscope191837;
typedef struct TY191944 TY191944;
typedef struct Tstrtable191817 Tstrtable191817;
typedef struct Tsymseq191815 Tsymseq191815;
typedef struct Tloc191827 Tloc191827;
typedef struct Ropeobj161009 Ropeobj161009;
typedef struct Tlib191831 Tlib191831;
typedef struct Tcell46947 Tcell46947;
typedef struct Tcellseq46963 Tcellseq46963;
typedef struct Tgcheap48816 Tgcheap48816;
typedef struct Tcellset46959 Tcellset46959;
typedef struct Tpagedesc46955 Tpagedesc46955;
typedef struct Tmemregion28810 Tmemregion28810;
typedef struct Tsmallchunk28040 Tsmallchunk28040;
typedef struct Tllchunk28804 Tllchunk28804;
typedef struct Tbigchunk28042 Tbigchunk28042;
typedef struct Tintset28017 Tintset28017;
typedef struct Ttrunk28013 Ttrunk28013;
typedef struct Tavlnode28808 Tavlnode28808;
typedef struct Tgcstat48814 Tgcstat48814;
typedef struct Tinstantiation191833 Tinstantiation191833;
typedef struct Tlistentry130022 Tlistentry130022;
typedef struct Tbasechunk28038 Tbasechunk28038;
typedef struct Tfreecell28030 Tfreecell28030;
typedef struct TY191933 TY191933;
struct  Tlineinfo163338  {
NI16 line;
NI16 col;
NI32 fileindex;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tnode191813  {
Ttype191849* typ;
Tlineinfo163338 info;
NU16 flags;
NU8 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym191843* sym;
} S4;
struct {Tident167021* ident;
} S5;
struct {Tnodeseq191807* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef NU8 TY192031[20];
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj167015  {
  TNimObject Sup;
NI id;
};
struct  Tstrtable191817  {
NI counter;
Tsymseq191815* data;
};
struct  Tloc191827  {
NU8 k;
NU8 s;
NU16 flags;
Ttype191849* t;
Ropeobj161009* r;
Ropeobj161009* heaproot;
};
struct  Tsym191843  {
  Tidobj167015 Sup;
NU8 kind;
union{
struct {Ttypeseq191845* typeinstcache;
Tscope191837* typscope;
} S1;
struct {TY191944* procinstcache;
Tsym191843* gcunsafetyreason;
} S2;
struct {TY191944* usedgenerics;
Tstrtable191817 tab;
} S3;
struct {Tsym191843* guard;
} S4;
} kindU;
NU16 magic;
Ttype191849* typ;
Tident167021* name;
Tlineinfo163338 info;
Tsym191843* owner;
NU32 flags;
Tnode191813* ast;
NU32 options;
NI position;
NI offset;
Tloc191827 loc;
Tlib191831* annex;
Tnode191813* constraint;
};
struct  Tident167021  {
  Tidobj167015 Sup;
NimStringDesc* s;
Tident167021* next;
NI h;
};
struct  Ttype191849  {
  Tidobj167015 Sup;
NU8 kind;
NU8 callconv;
NU32 flags;
Ttypeseq191845* sons;
Tnode191813* n;
Tsym191843* owner;
Tsym191843* sym;
Tsym191843* destructor;
Tsym191843* deepcopy;
Tsym191843* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc191827 loc;
};
struct  Tcell46947  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46963  {
NI len;
NI cap;
Tcell46947** d;
};
struct  Tcellset46959  {
NI counter;
NI max;
Tpagedesc46955* head;
Tpagedesc46955** data;
};
typedef Tsmallchunk28040* TY28822[512];
typedef Ttrunk28013* Ttrunkbuckets28015[256];
struct  Tintset28017  {
Ttrunkbuckets28015 data;
};
struct  Tmemregion28810  {
NI minlargeobj;
NI maxlargeobj;
TY28822 freesmallchunks;
Tllchunk28804* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk28042* freechunkslist;
Tintset28017 chunkstarts;
Tavlnode28808* root;
Tavlnode28808* deleted;
Tavlnode28808* last;
Tavlnode28808* freeavlnodes;
};
struct  Tgcstat48814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48816  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46963 zct;
Tcellseq46963 decstack;
Tcellset46959 cycleroots;
Tcellseq46963 tempstack;
NI recgclock;
Tmemregion28810 region;
Tgcstat48814 stat;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tscope191837  {
NI depthlevel;
Tstrtable191817 symbols;
Tnodeseq191807* usingsyms;
Tscope191837* parent;
};
struct  Ropeobj161009  {
  TNimObject Sup;
Ropeobj161009* left;
Ropeobj161009* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry130022  {
  TNimObject Sup;
Tlistentry130022* prev;
Tlistentry130022* next;
};
struct  Tlib191831  {
  Tlistentry130022 Sup;
NU8 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj161009* name;
Tnode191813* path;
};
typedef NI TY28020[8];
struct  Tpagedesc46955  {
Tpagedesc46955* next;
NI key;
TY28020 bits;
};
struct  Tbasechunk28038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk28040  {
  Tbasechunk28038 Sup;
Tsmallchunk28040* next;
Tsmallchunk28040* prev;
Tfreecell28030* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28804  {
NI size;
NI acc;
Tllchunk28804* next;
};
struct  Tbigchunk28042  {
  Tbasechunk28038 Sup;
Tbigchunk28042* next;
Tbigchunk28042* prev;
NI align;
NF data;
};
struct  Ttrunk28013  {
Ttrunk28013* next;
NI key;
TY28020 bits;
};
typedef Tavlnode28808* TY28814[2];
struct  Tavlnode28808  {
TY28814 link;
NI key;
NI upperbound;
NI level;
};
struct  Tinstantiation191833  {
Tsym191843* sym;
Ttypeseq191845* concretetypes;
TY191933* usedby;
};
struct  Tfreecell28030  {
Tfreecell28030* next;
NI zerofield;
};
struct Tnodeseq191807 {
  TGenericSeq Sup;
  Tnode191813* data[SEQ_DECL_SIZE];
};
struct Ttypeseq191845 {
  TGenericSeq Sup;
  Ttype191849* data[SEQ_DECL_SIZE];
};
struct TY191944 {
  TGenericSeq Sup;
  Tinstantiation191833* data[SEQ_DECL_SIZE];
};
struct Tsymseq191815 {
  TGenericSeq Sup;
  Tsym191843* data[SEQ_DECL_SIZE];
};
struct TY191933 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, hasson_220019)(Tnode191813* father, Tnode191813* son);
N_NIMCALL(NI, sonslen_194403)(Tnode191813* n);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, cyclictreeaux_220072)(Tnode191813* n, Tnode191813* s);
N_NIMCALL(void, addson_193819)(Tnode191813* father, Tnode191813* son);
N_NIMCALL(void, delson_195577)(Tnode191813* father, NI idx);
N_NIMCALL(NIM_BOOL, cyclictree_220138)(Tnode191813* n);
N_NIMCALL(Tnode191813*, newnodei_193351)(NU8 kind, Tlineinfo163338 info);
N_NIMCALL(NIM_BOOL, exprstructuralequivalent_220149)(Tnode191813* a, Tnode191813* b);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_BOOL, sametree_220248)(Tnode191813* a, Tnode191813* b);
N_NIMCALL(Tsym191843*, getprocsym_220358)(Tnode191813* call);
N_NIMCALL(Tsym191843*, getopsym_220370)(Tnode191813* op);
N_NIMCALL(void, internalerror_165199)(Tlineinfo163338 info, NimStringDesc* errmsg);
N_NIMCALL(NU16, getmagic_220403)(Tnode191813* op);
N_NIMCALL(Tsym191843*, treetosym_220417)(Tnode191813* t);
N_NIMCALL(NIM_BOOL, isconstexpr_220428)(Tnode191813* n);
N_NIMCALL(NIM_BOOL, isdeepconstexpr_220459)(Tnode191813* n);
static N_INLINE(NI, len_192097)(Tnode191813* n);
N_NIMCALL(Ttype191849*, skiptypes_195167)(Ttype191849* t, NU64 kinds);
N_NIMCALL(void, flattentreeaux_220526)(Tnode191813* d, Tnode191813* a, NU16 op);
N_NIMCALL(Tnode191813*, copytree_196028)(Tnode191813* src);
N_NIMCALL(Tnode191813*, flattentree_220577)(Tnode191813* root, NU16 op);
N_NIMCALL(Tnode191813*, copynode_195640)(Tnode191813* src);
N_NIMCALL(void, swapoperands_220598)(Tnode191813* op);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46947*, usrtocell_50446)(void* usr);
static N_INLINE(void, rtladdzct_52004)(Tcell46947* c);
N_NOINLINE(void, addzct_50417)(Tcellseq46963* s, Tcell46947* c);
static N_INLINE(NIM_BOOL, isrange_220612)(Tnode191813* n);
static N_INLINE(Tnode191813*, HEX5BHEX5D_192244)(Tnode191813* n, NI i);
N_NIMCALL(NU16, whichpragma_220673)(Tnode191813* n);
N_NIMCALL(NU16, whichkeyword_172386)(Tident167021* id);
N_NIMCALL(void, unneststmts_220704)(Tnode191813* n, Tnode191813* result);
N_NIMCALL(void, add_192164)(Tnode191813* father, Tnode191813* son);
N_NIMCALL(Tnode191813*, flattenstmts_220759)(Tnode191813* n);
N_NIMCALL(Tnode191813*, extractrange_220771)(NU8 k, Tnode191813* n, NI a, NI b);
N_NIMCALL(Tnode191813*, newnodei_193407)(NU8 kind, Tlineinfo163338 info, NI children);
static NIM_CONST TY192031 TMP3425 = {
0xEC, 0xFF, 0x7F, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP3426, "sons", 4);
static NIM_CONST TY192031 TMP3430 = {
0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP3431, "sym", 3);
static NIM_CONST TY192031 TMP3432 = {
0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP3433, "ident", 5);
static NIM_CONST TY192031 TMP3434 = {
0xE0, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP3435, "intVal", 6);
static NIM_CONST TY192031 TMP3436 = {
0x00, 0x00, 0x0F, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP3437, "floatVal", 8);
static NIM_CONST TY192031 TMP3438 = {
0x00, 0x00, 0x70, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP3439, "strVal", 6);
STRING_LITERAL(TMP3444, "getOpSym", 8);
extern TFrame* frameptr_17242;
extern Tgcheap48816 gch_48844;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17242 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17242;
	frameptr_17242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17242 = (*frameptr_17242).prev;
}

N_NIMCALL(NIM_BOOL, hasson_220019)(Tnode191813* father, Tnode191813* son) {
	NIM_BOOL result;
	nimfr("hasSon", "trees.nim")
{	result = 0;
	{
		NI i_220036;
		NI HEX3Atmp_220050;
		NI LOC2;
		NI TMP3424;
		NI res_220053;
		i_220036 = 0;
		HEX3Atmp_220050 = 0;
		nimln(16, "trees.nim");
		LOC2 = 0;
		LOC2 = sonslen_194403(father);
		TMP3424 = subInt(LOC2, ((NI) 1));
		HEX3Atmp_220050 = (NI)(TMP3424);
		nimln(1598, "system.nim");
		res_220053 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP3427;
				if (!(res_220053 <= HEX3Atmp_220050)) goto LA4;
				nimln(1600, "system.nim");
				i_220036 = res_220053;
				nimln(17, "trees.nim");
				{
					if (((TMP3425[(*father).kind/8] &(1<<((*father).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
					if ((NU)(i_220036) >= (NU)((*father).kindU.S6.sons->Sup.len)) raiseIndexError();
					if (!((*father).kindU.S6.sons->data[i_220036] == son)) goto LA7;
					nimln(18, "trees.nim");
					result = NIM_TRUE;
					goto BeforeRet;
				}
				LA7: ;
				nimln(1614, "system.nim");
				TMP3427 = addInt(res_220053, ((NI) 1));
				res_220053 = (NI)(TMP3427);
			} LA4: ;
		}
	}
	nimln(19, "trees.nim");
	result = NIM_FALSE;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, cyclictreeaux_220072)(Tnode191813* n, Tnode191813* s) {
	NIM_BOOL result;
	NI m;
	nimfr("cyclicTreeAux", "trees.nim")
{	result = 0;
	nimln(22, "trees.nim");
	{
		if (!(n == NIM_NIL)) goto LA3;
		nimln(23, "trees.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA3: ;
	nimln(24, "trees.nim");
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = hasson_220019(s, n);
		if (!LOC7) goto LA8;
		nimln(25, "trees.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA8: ;
	nimln(26, "trees.nim");
	m = sonslen_194403(s);
	nimln(27, "trees.nim");
	addson_193819(s, n);
	nimln(28, "trees.nim");
	{
		if (!!(((*n).kind >= ((NU8) 1) && (*n).kind <= ((NU8) 23)))) goto LA12;
		{
			NI i_220113;
			NI HEX3Atmp_220116;
			NI LOC15;
			NI TMP3428;
			NI res_220119;
			i_220113 = 0;
			HEX3Atmp_220116 = 0;
			nimln(29, "trees.nim");
			LOC15 = 0;
			LOC15 = sonslen_194403(n);
			TMP3428 = subInt(LOC15, ((NI) 1));
			HEX3Atmp_220116 = (NI)(TMP3428);
			nimln(1598, "system.nim");
			res_220119 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP3429;
					if (!(res_220119 <= HEX3Atmp_220116)) goto LA17;
					nimln(1600, "system.nim");
					i_220113 = res_220119;
					nimln(30, "trees.nim");
					{
						NIM_BOOL LOC20;
						if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
						if ((NU)(i_220113) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
						LOC20 = 0;
						LOC20 = cyclictreeaux_220072((*n).kindU.S6.sons->data[i_220113], s);
						if (!LOC20) goto LA21;
						nimln(31, "trees.nim");
						result = NIM_TRUE;
						goto BeforeRet;
					}
					LA21: ;
					nimln(1614, "system.nim");
					TMP3429 = addInt(res_220119, ((NI) 1));
					res_220119 = (NI)(TMP3429);
				} LA17: ;
			}
		}
	}
	LA12: ;
	nimln(32, "trees.nim");
	result = NIM_FALSE;
	nimln(33, "trees.nim");
	delson_195577(s, m);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, cyclictree_220138)(Tnode191813* n) {
	NIM_BOOL result;
	Tnode191813* s;
	nimfr("cyclicTree", "trees.nim")
	result = 0;
	nimln(36, "trees.nim");
	s = newnodei_193351(((NU8) 1), (*n).info);
	nimln(37, "trees.nim");
	result = cyclictreeaux_220072(n, s);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, exprstructuralequivalent_220149)(Tnode191813* a, Tnode191813* b) {
	NIM_BOOL result;
	nimfr("exprStructuralEquivalent", "trees.nim")
{	result = 0;
	nimln(40, "trees.nim");
	result = NIM_FALSE;
	nimln(41, "trees.nim");
	{
		if (!(a == b)) goto LA3;
		nimln(42, "trees.nim");
		result = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		NIM_BOOL LOC7;
		nimln(43, "trees.nim");
		LOC6 = 0;
		LOC7 = 0;
		LOC7 = !((a == NIM_NIL));
		if (!(LOC7)) goto LA8;
		LOC7 = !((b == NIM_NIL));
		LA8: ;
		LOC6 = LOC7;
		if (!(LOC6)) goto LA9;
		LOC6 = ((*a).kind == (*b).kind);
		LA9: ;
		if (!LOC6) goto LA10;
		nimln(44, "trees.nim");
		switch ((*a).kind) {
		case ((NU8) 3):
		{
			nimln(47, "trees.nim");
			if (!(((TMP3430[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			if (!(((TMP3430[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			result = ((*(*(*a).kindU.S4.sym).name).Sup.id == (*(*(*b).kindU.S4.sym).name).Sup.id);
		}
		break;
		case ((NU8) 2):
		{
			nimln(48, "trees.nim");
			if (!(((TMP3432[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3433));
			if (!(((TMP3432[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3433));
			result = ((*(*a).kindU.S5.ident).Sup.id == (*(*b).kindU.S5.ident).Sup.id);
		}
		break;
		case ((NU8) 5) ... ((NU8) 10):
		{
			nimln(49, "trees.nim");
			if (!(((TMP3434[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3435));
			if (!(((TMP3434[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3435));
			result = ((*a).kindU.S1.intval == (*b).kindU.S1.intval);
		}
		break;
		case ((NU8) 16) ... ((NU8) 18):
		{
			nimln(50, "trees.nim");
			if (!(((TMP3436[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3437));
			if (!(((TMP3436[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3437));
			result = ((*a).kindU.S2.floatval == (*b).kindU.S2.floatval);
		}
		break;
		case ((NU8) 20) ... ((NU8) 22):
		{
			nimln(51, "trees.nim");
			if (!(((TMP3438[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3439));
			if (!(((TMP3438[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3439));
			result = eqStrings((*a).kindU.S3.strval, (*b).kindU.S3.strval);
		}
		break;
		case ((NU8) 1):
		case ((NU8) 23):
		case ((NU8) 4):
		{
			nimln(52, "trees.nim");
			result = NIM_TRUE;
		}
		break;
		default:
		{
			nimln(54, "trees.nim");
			{
				NI LOC21;
				NI LOC22;
				LOC21 = 0;
				LOC21 = sonslen_194403(a);
				LOC22 = 0;
				LOC22 = sonslen_194403(b);
				if (!(LOC21 == LOC22)) goto LA23;
				{
					NI i_220222;
					NI HEX3Atmp_220226;
					NI LOC26;
					NI TMP3440;
					NI res_220229;
					i_220222 = 0;
					HEX3Atmp_220226 = 0;
					nimln(55, "trees.nim");
					LOC26 = 0;
					LOC26 = sonslen_194403(a);
					TMP3440 = subInt(LOC26, ((NI) 1));
					HEX3Atmp_220226 = (NI)(TMP3440);
					nimln(1598, "system.nim");
					res_220229 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP3441;
							if (!(res_220229 <= HEX3Atmp_220226)) goto LA28;
							nimln(1600, "system.nim");
							i_220222 = res_220229;
							nimln(56, "trees.nim");
							{
								NIM_BOOL LOC31;
								if (((TMP3425[(*a).kind/8] &(1<<((*a).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
								if ((NU)(i_220222) >= (NU)((*a).kindU.S6.sons->Sup.len)) raiseIndexError();
								if (((TMP3425[(*b).kind/8] &(1<<((*b).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
								if ((NU)(i_220222) >= (NU)((*b).kindU.S6.sons->Sup.len)) raiseIndexError();
								LOC31 = 0;
								LOC31 = exprstructuralequivalent_220149((*a).kindU.S6.sons->data[i_220222], (*b).kindU.S6.sons->data[i_220222]);
								if (!!(LOC31)) goto LA32;
								goto BeforeRet;
							}
							LA32: ;
							nimln(1614, "system.nim");
							TMP3441 = addInt(res_220229, ((NI) 1));
							res_220229 = (NI)(TMP3441);
						} LA28: ;
					}
				}
				nimln(57, "trees.nim");
				result = NIM_TRUE;
			}
			LA23: ;
		}
		break;
		}
	}
	goto LA1;
	LA10: ;
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, sametree_220248)(Tnode191813* a, Tnode191813* b) {
	NIM_BOOL result;
	nimfr("sameTree", "trees.nim")
{	result = 0;
	nimln(60, "trees.nim");
	result = NIM_FALSE;
	nimln(61, "trees.nim");
	{
		if (!(a == b)) goto LA3;
		nimln(62, "trees.nim");
		result = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		NIM_BOOL LOC7;
		nimln(63, "trees.nim");
		LOC6 = 0;
		LOC7 = 0;
		LOC7 = !((a == NIM_NIL));
		if (!(LOC7)) goto LA8;
		LOC7 = !((b == NIM_NIL));
		LA8: ;
		LOC6 = LOC7;
		if (!(LOC6)) goto LA9;
		LOC6 = ((*a).kind == (*b).kind);
		LA9: ;
		if (!LOC6) goto LA10;
		nimln(64, "trees.nim");
		{
			if (!!(((*a).flags == (*b).flags))) goto LA14;
			goto BeforeRet;
		}
		LA14: ;
		nimln(65, "trees.nim");
		{
			if (!!(((*a).info.line == (*b).info.line))) goto LA18;
			goto BeforeRet;
		}
		LA18: ;
		nimln(66, "trees.nim");
		{
			if (!!(((*a).info.col == (*b).info.col))) goto LA22;
			nimln(67, "trees.nim");
			goto BeforeRet;
		}
		LA22: ;
		nimln(68, "trees.nim");
		switch ((*a).kind) {
		case ((NU8) 3):
		{
			nimln(71, "trees.nim");
			if (!(((TMP3430[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			if (!(((TMP3430[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			result = ((*(*(*a).kindU.S4.sym).name).Sup.id == (*(*(*b).kindU.S4.sym).name).Sup.id);
		}
		break;
		case ((NU8) 2):
		{
			nimln(72, "trees.nim");
			if (!(((TMP3432[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3433));
			if (!(((TMP3432[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3433));
			result = ((*(*a).kindU.S5.ident).Sup.id == (*(*b).kindU.S5.ident).Sup.id);
		}
		break;
		case ((NU8) 5) ... ((NU8) 10):
		{
			nimln(73, "trees.nim");
			if (!(((TMP3434[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3435));
			if (!(((TMP3434[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3435));
			result = ((*a).kindU.S1.intval == (*b).kindU.S1.intval);
		}
		break;
		case ((NU8) 16) ... ((NU8) 18):
		{
			nimln(74, "trees.nim");
			if (!(((TMP3436[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3437));
			if (!(((TMP3436[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3437));
			result = ((*a).kindU.S2.floatval == (*b).kindU.S2.floatval);
		}
		break;
		case ((NU8) 20) ... ((NU8) 22):
		{
			nimln(75, "trees.nim");
			if (!(((TMP3438[(*a).kind/8] &(1<<((*a).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3439));
			if (!(((TMP3438[(*b).kind/8] &(1<<((*b).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3439));
			result = eqStrings((*a).kindU.S3.strval, (*b).kindU.S3.strval);
		}
		break;
		case ((NU8) 1):
		case ((NU8) 23):
		case ((NU8) 4):
		{
			nimln(76, "trees.nim");
			result = NIM_TRUE;
		}
		break;
		default:
		{
			nimln(78, "trees.nim");
			{
				NI LOC33;
				NI LOC34;
				LOC33 = 0;
				LOC33 = sonslen_194403(a);
				LOC34 = 0;
				LOC34 = sonslen_194403(b);
				if (!(LOC33 == LOC34)) goto LA35;
				{
					NI i_220332;
					NI HEX3Atmp_220336;
					NI LOC38;
					NI TMP3442;
					NI res_220339;
					i_220332 = 0;
					HEX3Atmp_220336 = 0;
					nimln(79, "trees.nim");
					LOC38 = 0;
					LOC38 = sonslen_194403(a);
					TMP3442 = subInt(LOC38, ((NI) 1));
					HEX3Atmp_220336 = (NI)(TMP3442);
					nimln(1598, "system.nim");
					res_220339 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP3443;
							if (!(res_220339 <= HEX3Atmp_220336)) goto LA40;
							nimln(1600, "system.nim");
							i_220332 = res_220339;
							nimln(80, "trees.nim");
							{
								NIM_BOOL LOC43;
								if (((TMP3425[(*a).kind/8] &(1<<((*a).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
								if ((NU)(i_220332) >= (NU)((*a).kindU.S6.sons->Sup.len)) raiseIndexError();
								if (((TMP3425[(*b).kind/8] &(1<<((*b).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
								if ((NU)(i_220332) >= (NU)((*b).kindU.S6.sons->Sup.len)) raiseIndexError();
								LOC43 = 0;
								LOC43 = sametree_220248((*a).kindU.S6.sons->data[i_220332], (*b).kindU.S6.sons->data[i_220332]);
								if (!!(LOC43)) goto LA44;
								goto BeforeRet;
							}
							LA44: ;
							nimln(1614, "system.nim");
							TMP3443 = addInt(res_220339, ((NI) 1));
							res_220339 = (NI)(TMP3443);
						} LA40: ;
					}
				}
				nimln(81, "trees.nim");
				result = NIM_TRUE;
			}
			LA35: ;
		}
		break;
		}
	}
	goto LA1;
	LA10: ;
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Tsym191843*, getprocsym_220358)(Tnode191813* call) {
	Tsym191843* result;
	nimfr("getProcSym", "trees.nim")
	result = 0;
	nimln(84, "trees.nim");
	if (((TMP3425[(*call).kind/8] &(1<<((*call).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
	if ((NU)(((NI) 0)) >= (NU)((*call).kindU.S6.sons->Sup.len)) raiseIndexError();
	if (!(((TMP3430[(*(*call).kindU.S6.sons->data[((NI) 0)]).kind/8] &(1<<((*(*call).kindU.S6.sons->data[((NI) 0)]).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
	result = (*(*call).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym;
	popFrame();
	return result;
}

N_NIMCALL(Tsym191843*, getopsym_220370)(Tnode191813* op) {
	Tsym191843* result;
	nimfr("getOpSym", "trees.nim")
	result = 0;
	nimln(87, "trees.nim");
	{
		if (!!(((*op).kind == ((NU8) 27) || (*op).kind == ((NU8) 32) || (*op).kind == ((NU8) 26) || (*op).kind == ((NU8) 28)))) goto LA3;
		nimln(88, "trees.nim");
		result = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		nimln(90, "trees.nim");
		{
			NI LOC8;
			LOC8 = 0;
			LOC8 = sonslen_194403(op);
			if (!(LOC8 <= ((NI) 0))) goto LA9;
			internalerror_165199((*op).info, ((NimStringDesc*) &TMP3444));
		}
		goto LA6;
		LA9: ;
		{
			nimln(91, "trees.nim");
			if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
			if ((NU)(((NI) 0)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
			if (!((*(*op).kindU.S6.sons->data[((NI) 0)]).kind == ((NU8) 3))) goto LA12;
			if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
			if ((NU)(((NI) 0)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
			if (!(((TMP3430[(*(*op).kindU.S6.sons->data[((NI) 0)]).kind/8] &(1<<((*(*op).kindU.S6.sons->data[((NI) 0)]).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			result = (*(*op).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym;
		}
		goto LA6;
		LA12: ;
		{
			nimln(92, "trees.nim");
			result = NIM_NIL;
		}
		LA6: ;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NU16, getmagic_220403)(Tnode191813* op) {
	NU16 result;
	nimfr("getMagic", "trees.nim")
	result = 0;
	nimln(95, "trees.nim");
	switch ((*op).kind) {
	case ((NU8) 27):
	case ((NU8) 29):
	case ((NU8) 30):
	case ((NU8) 31):
	case ((NU8) 26):
	case ((NU8) 28):
	case ((NU8) 32):
	{
		nimln(97, "trees.nim");
		if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		if ((NU)(((NI) 0)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
		switch ((*(*op).kindU.S6.sons->data[((NI) 0)]).kind) {
		case ((NU8) 3):
		{
			nimln(98, "trees.nim");
			if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
			if ((NU)(((NI) 0)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
			if (!(((TMP3430[(*(*op).kindU.S6.sons->data[((NI) 0)]).kind/8] &(1<<((*(*op).kindU.S6.sons->data[((NI) 0)]).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			result = (*(*(*op).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym).magic;
		}
		break;
		default:
		{
			nimln(99, "trees.nim");
			result = ((NU16) 0);
		}
		break;
		}
	}
	break;
	default:
	{
		nimln(100, "trees.nim");
		result = ((NU16) 0);
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(Tsym191843*, treetosym_220417)(Tnode191813* t) {
	Tsym191843* result;
	nimfr("treeToSym", "trees.nim")
	result = 0;
	nimln(103, "trees.nim");
	if (!(((TMP3430[(*t).kind/8] &(1<<((*t).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
	result = (*t).kindU.S4.sym;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isconstexpr_220428)(Tnode191813* n) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("isConstExpr", "trees.nim")
	result = 0;
	nimln(106, "trees.nim");
	nimln(108, "trees.nim");
	LOC1 = 0;
	nimln(106, "trees.nim");
	LOC1 = ((*n).kind >= ((NU8) 5) && (*n).kind <= ((NU8) 10) || (*n).kind >= ((NU8) 20) && (*n).kind <= ((NU8) 22) || (*n).kind >= ((NU8) 16) && (*n).kind <= ((NU8) 18) || (*n).kind == ((NU8) 23));
	if (LOC1) goto LA2;
	nimln(108, "trees.nim");
	LOC1 = (((*n).flags &(1<<((((NU8) 4))&15)))!=0);
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NI, len_192097)(Tnode191813* n) {
	NI result;
	nimfr("len", "ast.nim")
	result = 0;
	nimln(934, "ast.nim");
	{
		if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		if (!(*n).kindU.S6.sons == 0) goto LA3;
		result = ((NI) 0);
	}
	goto LA1;
	LA3: ;
	{
		nimln(935, "ast.nim");
		if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		result = ((*n).kindU.S6.sons ? (*n).kindU.S6.sons->Sup.len : 0);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isdeepconstexpr_220459)(Tnode191813* n) {
	NIM_BOOL result;
	nimfr("isDeepConstExpr", "trees.nim")
{	result = 0;
	nimln(111, "trees.nim");
	switch ((*n).kind) {
	case ((NU8) 5) ... ((NU8) 10):
	case ((NU8) 20) ... ((NU8) 22):
	case ((NU8) 16) ... ((NU8) 18):
	case ((NU8) 23):
	{
		nimln(114, "trees.nim");
		result = NIM_TRUE;
	}
	break;
	case ((NU8) 33):
	case ((NU8) 34):
	case ((NU8) 58):
	case ((NU8) 59):
	{
		nimln(116, "trees.nim");
		if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		if ((NU)(((NI) 1)) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
		result = isdeepconstexpr_220459((*n).kindU.S6.sons->data[((NI) 1)]);
	}
	break;
	case ((NU8) 39):
	case ((NU8) 41):
	case ((NU8) 37):
	case ((NU8) 38):
	case ((NU8) 155):
	{
		NIM_BOOL LOC13;
		Ttype191849* LOC15;
		{
			NI i_220483;
			NI HEX3Atmp_220504;
			NI LOC5;
			NI res_220507;
			i_220483 = 0;
			HEX3Atmp_220504 = 0;
			nimln(118, "trees.nim");
			LOC5 = 0;
			LOC5 = len_192097(n);
			HEX3Atmp_220504 = subInt(LOC5, 1);
			nimln(1598, "system.nim");
			res_220507 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP3445;
					if (!(res_220507 <= HEX3Atmp_220504)) goto LA7;
					nimln(1600, "system.nim");
					i_220483 = res_220507;
					nimln(119, "trees.nim");
					{
						NIM_BOOL LOC10;
						if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
						if ((NU)(i_220483) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
						LOC10 = 0;
						LOC10 = isdeepconstexpr_220459((*n).kindU.S6.sons->data[i_220483]);
						if (!!(LOC10)) goto LA11;
						result = NIM_FALSE;
						goto BeforeRet;
					}
					LA11: ;
					nimln(1619, "system.nim");
					TMP3445 = addInt(res_220507, ((NI) 1));
					res_220507 = (NI)(TMP3445);
				} LA7: ;
			}
		}
		nimln(122, "trees.nim");
		LOC13 = 0;
		LOC13 = (*n).typ == 0;
		if (LOC13) goto LA14;
		LOC15 = 0;
		LOC15 = skiptypes_195167((*n).typ, 10240);
		LOC13 = !(((*LOC15).kind == ((NU8) 17)));
		LA14: ;
		result = LOC13;
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, flattentreeaux_220526)(Tnode191813* d, Tnode191813* a, NU16 op) {
	nimfr("flattenTreeAux", "trees.nim")
	nimln(126, "trees.nim");
	{
		NU16 LOC3;
		LOC3 = 0;
		LOC3 = getmagic_220403(a);
		if (!(LOC3 == op)) goto LA4;
		{
			NI i_220552;
			NI HEX3Atmp_220555;
			NI LOC7;
			NI TMP3446;
			NI res_220558;
			i_220552 = 0;
			HEX3Atmp_220555 = 0;
			nimln(127, "trees.nim");
			LOC7 = 0;
			LOC7 = sonslen_194403(a);
			TMP3446 = subInt(LOC7, ((NI) 1));
			HEX3Atmp_220555 = (NI)(TMP3446);
			nimln(1598, "system.nim");
			res_220558 = ((NI) 1);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP3447;
					if (!(res_220558 <= HEX3Atmp_220555)) goto LA9;
					nimln(1600, "system.nim");
					i_220552 = res_220558;
					nimln(128, "trees.nim");
					if (((TMP3425[(*a).kind/8] &(1<<((*a).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
					if ((NU)(i_220552) >= (NU)((*a).kindU.S6.sons->Sup.len)) raiseIndexError();
					flattentreeaux_220526(d, (*a).kindU.S6.sons->data[i_220552], op);
					nimln(1614, "system.nim");
					TMP3447 = addInt(res_220558, ((NI) 1));
					res_220558 = (NI)(TMP3447);
				} LA9: ;
			}
		}
	}
	goto LA1;
	LA4: ;
	{
		Tnode191813* LOC11;
		nimln(130, "trees.nim");
		LOC11 = 0;
		LOC11 = copytree_196028(a);
		addson_193819(d, LOC11);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(Tnode191813*, flattentree_220577)(Tnode191813* root, NU16 op) {
	Tnode191813* result;
	nimfr("flattenTree", "trees.nim")
	result = 0;
	nimln(133, "trees.nim");
	result = copynode_195640(root);
	nimln(134, "trees.nim");
	{
		NU16 LOC3;
		Tnode191813* LOC6;
		LOC3 = 0;
		LOC3 = getmagic_220403(root);
		if (!(LOC3 == op)) goto LA4;
		nimln(136, "trees.nim");
		if (((TMP3425[(*root).kind/8] &(1<<((*root).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		if ((NU)(((NI) 0)) >= (NU)((*root).kindU.S6.sons->Sup.len)) raiseIndexError();
		LOC6 = 0;
		LOC6 = copynode_195640((*root).kindU.S6.sons->data[((NI) 0)]);
		addson_193819(result, LOC6);
		nimln(137, "trees.nim");
		flattentreeaux_220526(result, root, op);
	}
	LA4: ;
	popFrame();
	return result;
}

static N_INLINE(Tcell46947*, usrtocell_50446)(void* usr) {
	Tcell46947* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46947*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46947))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_52004)(Tcell46947* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50417((&gch_48844.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46947* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50446(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46947* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50446((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_52004(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, swapoperands_220598)(Tnode191813* op) {
	Tnode191813* tmp;
	nimfr("swapOperands", "trees.nim")
	nimln(140, "trees.nim");
	if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
	if ((NU)(((NI) 1)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
	tmp = (*op).kindU.S6.sons->data[((NI) 1)];
	nimln(141, "trees.nim");
	if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
	if ((NU)(((NI) 1)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
	if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
	if ((NU)(((NI) 2)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
	asgnRefNoCycle((void**) (&(*op).kindU.S6.sons->data[((NI) 1)]), (*op).kindU.S6.sons->data[((NI) 2)]);
	nimln(142, "trees.nim");
	if (((TMP3425[(*op).kind/8] &(1<<((*op).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
	if ((NU)(((NI) 2)) >= (NU)((*op).kindU.S6.sons->Sup.len)) raiseIndexError();
	asgnRefNoCycle((void**) (&(*op).kindU.S6.sons->data[((NI) 2)]), tmp);
	popFrame();
}

static N_INLINE(Tnode191813*, HEX5BHEX5D_192244)(Tnode191813* n, NI i) {
	Tnode191813* result;
	nimfr("[]", "ast.nim")
	result = 0;
	nimln(948, "ast.nim");
	if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
	if ((NU)(i) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
	result = (*n).kindU.S6.sons->data[i];
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isrange_220612)(Tnode191813* n) {
	NIM_BOOL result;
	nimfr("isRange", "trees.nim")
	result = 0;
	nimln(145, "trees.nim");
	{
		if (!((*n).kind == ((NU8) 27) || (*n).kind == ((NU8) 29) || (*n).kind == ((NU8) 30) || (*n).kind == ((NU8) 31) || (*n).kind == ((NU8) 26) || (*n).kind == ((NU8) 28) || (*n).kind == ((NU8) 32))) goto LA3;
		nimln(146, "trees.nim");
		{
			NIM_BOOL LOC7;
			NIM_BOOL LOC8;
			Tnode191813* LOC9;
			Tnode191813* LOC11;
			NIM_BOOL LOC13;
			Tnode191813* LOC14;
			Tnode191813* LOC16;
			Tnode191813* LOC17;
			LOC7 = 0;
			LOC8 = 0;
			LOC9 = 0;
			LOC9 = HEX5BHEX5D_192244(n, ((NI) 0));
			LOC8 = ((*LOC9).kind == ((NU8) 2));
			if (!(LOC8)) goto LA10;
			LOC11 = 0;
			LOC11 = HEX5BHEX5D_192244(n, ((NI) 0));
			if (!(((TMP3432[(*LOC11).kind/8] &(1<<((*LOC11).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3433));
			LOC8 = ((*(*LOC11).kindU.S5.ident).Sup.id == ((NI) 75));
			LA10: ;
			LOC7 = LOC8;
			if (LOC7) goto LA12;
			nimln(147, "trees.nim");
			LOC13 = 0;
			LOC14 = 0;
			LOC14 = HEX5BHEX5D_192244(n, ((NI) 0));
			LOC13 = ((*LOC14).kind == ((NU8) 56) || (*LOC14).kind == ((NU8) 57));
			if (!(LOC13)) goto LA15;
			nimln(148, "trees.nim");
			LOC16 = 0;
			LOC16 = HEX5BHEX5D_192244(n, ((NI) 0));
			LOC17 = 0;
			LOC17 = HEX5BHEX5D_192244(LOC16, ((NI) 1));
			if (!(((TMP3430[(*LOC17).kind/8] &(1<<((*LOC17).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3431));
			LOC13 = ((*(*(*LOC17).kindU.S4.sym).name).Sup.id == ((NI) 75));
			LA15: ;
			LOC7 = LOC13;
			LA12: ;
			if (!LOC7) goto LA18;
			nimln(149, "trees.nim");
			result = NIM_TRUE;
		}
		LA18: ;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NU16, whichpragma_220673)(Tnode191813* n) {
	NU16 result;
	Tnode191813* key;
	nimfr("whichPragma", "trees.nim")
	result = 0;
	nimln(152, "trees.nim");
	{
		if (!((*n).kind == ((NU8) 34))) goto LA3;
		if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		if ((NU)(((NI) 0)) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
		key = (*n).kindU.S6.sons->data[((NI) 0)];
	}
	goto LA1;
	LA3: ;
	{
		key = n;
	}
	LA1: ;
	nimln(153, "trees.nim");
	{
		if (!((*key).kind == ((NU8) 2))) goto LA8;
		if (!(((TMP3432[(*key).kind/8] &(1<<((*key).kind%8)))!=0))) raiseFieldError(((NimStringDesc*) &TMP3433));
		result = whichkeyword_172386((*key).kindU.S5.ident);
	}
	LA8: ;
	popFrame();
	return result;
}

N_NIMCALL(void, unneststmts_220704)(Tnode191813* n, Tnode191813* result) {
	nimfr("unnestStmts", "trees.nim")
	nimln(156, "trees.nim");
	{
		if (!((*n).kind == ((NU8) 115))) goto LA3;
		{
			Tnode191813* x_220717;
			x_220717 = 0;
			{
				NI i_220734;
				NI HEX3Atmp_220736;
				NI LOC7;
				NI res_220738;
				i_220734 = 0;
				HEX3Atmp_220736 = 0;
				nimln(1537, "ast.nim");
				LOC7 = 0;
				LOC7 = len_192097(n);
				HEX3Atmp_220736 = subInt(LOC7, 1);
				nimln(1598, "system.nim");
				res_220738 = ((NI) 0);
				{
					nimln(1599, "system.nim");
					while (1) {
						NI TMP3448;
						if (!(res_220738 <= HEX3Atmp_220736)) goto LA9;
						nimln(1600, "system.nim");
						i_220734 = res_220738;
						nimln(1537, "ast.nim");
						if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
						if ((NU)(i_220734) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
						x_220717 = (*n).kindU.S6.sons->data[i_220734];
						nimln(157, "trees.nim");
						unneststmts_220704(x_220717, result);
						nimln(1619, "system.nim");
						TMP3448 = addInt(res_220738, ((NI) 1));
						res_220738 = (NI)(TMP3448);
					} LA9: ;
				}
			}
		}
	}
	goto LA1;
	LA3: ;
	{
		nimln(158, "trees.nim");
		if (!!(((*n).kind == ((NU8) 125) || (*n).kind == ((NU8) 23)))) goto LA11;
		nimln(159, "trees.nim");
		add_192164(result, n);
	}
	goto LA1;
	LA11: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(Tnode191813*, flattenstmts_220759)(Tnode191813* n) {
	Tnode191813* result;
	nimfr("flattenStmts", "trees.nim")
	result = 0;
	nimln(163, "trees.nim");
	result = newnodei_193351(((NU8) 115), (*n).info);
	nimln(164, "trees.nim");
	unneststmts_220704(n, result);
	nimln(165, "trees.nim");
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = len_192097(result);
		if (!(LOC3 == ((NI) 1))) goto LA4;
		nimln(166, "trees.nim");
		if (((TMP3425[(*result).kind/8] &(1<<((*result).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
		if ((NU)(((NI) 0)) >= (NU)((*result).kindU.S6.sons->Sup.len)) raiseIndexError();
		result = (*result).kindU.S6.sons->data[((NI) 0)];
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(Tnode191813*, extractrange_220771)(NU8 k, Tnode191813* n, NI a, NI b) {
	Tnode191813* result;
	NI TMP3449;
	NI TMP3450;
	nimfr("extractRange", "trees.nim")
	result = 0;
	nimln(169, "trees.nim");
	TMP3449 = subInt(b, a);
	TMP3450 = addInt((NI)(TMP3449), ((NI) 1));
	result = newnodei_193407(k, (*n).info, (NI)(TMP3450));
	{
		NI i_220788;
		NI HEX3Atmp_220792;
		NI TMP3451;
		NI res_220795;
		i_220788 = 0;
		HEX3Atmp_220792 = 0;
		nimln(170, "trees.nim");
		TMP3451 = subInt(b, a);
		HEX3Atmp_220792 = (NI)(TMP3451);
		nimln(1598, "system.nim");
		res_220795 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP3452;
				NI TMP3453;
				if (!(res_220795 <= HEX3Atmp_220792)) goto LA3;
				nimln(1600, "system.nim");
				i_220788 = res_220795;
				nimln(170, "trees.nim");
				if (((TMP3425[(*result).kind/8] &(1<<((*result).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
				if ((NU)(i_220788) >= (NU)((*result).kindU.S6.sons->Sup.len)) raiseIndexError();
				if (((TMP3425[(*n).kind/8] &(1<<((*n).kind%8)))!=0)) raiseFieldError(((NimStringDesc*) &TMP3426));
				TMP3452 = addInt(i_220788, a);
				if ((NU)((NI)(TMP3452)) >= (NU)((*n).kindU.S6.sons->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) (&(*result).kindU.S6.sons->data[i_220788]), (*n).kindU.S6.sons->data[(NI)(TMP3452)]);
				nimln(1619, "system.nim");
				TMP3453 = addInt(res_220795, ((NI) 1));
				res_220795 = (NI)(TMP3453);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, compiler_treesInit)(void) {
	nimfr("trees", "trees.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, compiler_treesDatInit)(void) {
}

