/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct Tindexentry311396 Tindexentry311396;
typedef struct TY311897 TY311897;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY13606 TY13606;
typedef struct Tsym189843 Tsym189843;
typedef struct Tsymseq189815 Tsymseq189815;
typedef struct Tidobj165015 Tidobj165015;
typedef struct TNimObject TNimObject;
typedef struct Ttypeseq189845 Ttypeseq189845;
typedef struct Tscope189837 Tscope189837;
typedef struct TY189944 TY189944;
typedef struct Tstrtable189817 Tstrtable189817;
typedef struct Ttype189849 Ttype189849;
typedef struct Tident165021 Tident165021;
typedef struct Tlineinfo161338 Tlineinfo161338;
typedef struct Tnode189813 Tnode189813;
typedef struct Tloc189827 Tloc189827;
typedef struct Ropeobj159009 Ropeobj159009;
typedef struct Tlib189831 Tlib189831;
typedef struct Tnodeseq189807 Tnodeseq189807;
typedef struct Tinstantiation189833 Tinstantiation189833;
typedef struct Tlistentry129022 Tlistentry129022;
typedef struct TY189933 TY189933;
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (Tindexentry311396* x_312696, Tindexentry311396* y_312698, void* ClEnv);
void* ClEnv;
} TY312694;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tindexentry311396  {
NimStringDesc* keyword;
NimStringDesc* link;
NimStringDesc* linktitle;
NimStringDesc* linkdesc;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TMP5961) (Tindexentry311396* x_312751, Tindexentry311396* y_312753);
typedef N_CLOSURE_PTR(NI, TMP5965) (Tindexentry311396* x_312751, Tindexentry311396* y_312753);
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (NimStringDesc* x_314310, NimStringDesc* y_314312, void* ClEnv);
void* ClEnv;
} TY314308;
typedef N_CLOSURE_PTR(NI, TMP6007) (NimStringDesc* x_314365, NimStringDesc* y_314367);
typedef N_CLOSURE_PTR(NI, TMP6010) (NimStringDesc* x_314365, NimStringDesc* y_314367);
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (Tsym189843* x_350527, Tsym189843* y_350529, void* ClEnv);
void* ClEnv;
} TY350525;
typedef N_CLOSURE_PTR(NI, TMP6967) (Tsym189843* x_350582, Tsym189843* y_350584);
typedef N_CLOSURE_PTR(NI, TMP6970) (Tsym189843* x_350582, Tsym189843* y_350584);
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj165015  {
  TNimObject Sup;
NI id;
};
struct  Tstrtable189817  {
NI counter;
Tsymseq189815* data;
};
struct  Tlineinfo161338  {
NI16 line;
NI16 col;
NI32 fileindex;
};
struct  Tloc189827  {
NU8 k;
NU8 s;
NU16 flags;
Ttype189849* t;
Ropeobj159009* r;
Ropeobj159009* heaproot;
};
struct  Tsym189843  {
  Tidobj165015 Sup;
NU8 kind;
union{
struct {Ttypeseq189845* typeinstcache;
Tscope189837* typscope;
} S1;
struct {TY189944* procinstcache;
Tsym189843* gcunsafetyreason;
} S2;
struct {TY189944* usedgenerics;
Tstrtable189817 tab;
} S3;
struct {Tsym189843* guard;
} S4;
} kindU;
NU16 magic;
Ttype189849* typ;
Tident165021* name;
Tlineinfo161338 info;
Tsym189843* owner;
NU32 flags;
Tnode189813* ast;
NU32 options;
NI position;
NI offset;
Tloc189827 loc;
Tlib189831* annex;
Tnode189813* constraint;
};
struct  Tscope189837  {
NI depthlevel;
Tstrtable189817 symbols;
Tnodeseq189807* usingsyms;
Tscope189837* parent;
};
struct  Ttype189849  {
  Tidobj165015 Sup;
NU8 kind;
NU8 callconv;
NU32 flags;
Ttypeseq189845* sons;
Tnode189813* n;
Tsym189843* owner;
Tsym189843* sym;
Tsym189843* destructor;
Tsym189843* deepcopy;
Tsym189843* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc189827 loc;
};
struct  Tident165021  {
  Tidobj165015 Sup;
NimStringDesc* s;
Tident165021* next;
NI h;
};
struct  Tnode189813  {
Ttype189849* typ;
Tlineinfo161338 info;
NU16 flags;
NU8 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym189843* sym;
} S4;
struct {Tident165021* ident;
} S5;
struct {Tnodeseq189807* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
struct  Ropeobj159009  {
  TNimObject Sup;
Ropeobj159009* left;
Ropeobj159009* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry129022  {
  TNimObject Sup;
Tlistentry129022* prev;
Tlistentry129022* next;
};
struct  Tlib189831  {
  Tlistentry129022 Sup;
NU8 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj159009* name;
Tnode189813* path;
};
struct  Tinstantiation189833  {
Tsym189843* sym;
Ttypeseq189845* concretetypes;
TY189933* usedby;
};
struct TY311897 {
  TGenericSeq Sup;
  Tindexentry311396 data[SEQ_DECL_SIZE];
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct Tsymseq189815 {
  TGenericSeq Sup;
  Tsym189843* data[SEQ_DECL_SIZE];
};
struct Ttypeseq189845 {
  TGenericSeq Sup;
  Ttype189849* data[SEQ_DECL_SIZE];
};
struct TY189944 {
  TGenericSeq Sup;
  Tinstantiation189833* data[SEQ_DECL_SIZE];
};
struct Tnodeseq189807 {
  TGenericSeq Sup;
  Tnode189813* data[SEQ_DECL_SIZE];
};
struct TY189933 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX2A_309020)(NI x, NU8 order);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, merge_312732)(Tindexentry311396* a, NI aLen0, Tindexentry311396* b, NI bLen0, NI lo, NI m, NI hi, TY312694 cmp, NU8 order);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_87017)(NimStringDesc* msg);
N_NIMCALL(void, HEX3CHEX2D_311807)(Tindexentry311396* a, Tindexentry311396* b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void, merge_314346)(NimStringDesc** a, NI aLen0, NimStringDesc** b, NI bLen0, NI lo, NI m, NI hi, TY314308 cmp, NU8 order);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, merge_350563)(Tsym189843** a, NI aLen0, Tsym189843** b, NI bLen0, NI lo, NI m, NI hi, TY350525 cmp, NU8 order);
STRING_LITERAL(TMP5962, "j <= m ", 7);
extern TFrame* frameptr_17042;
extern TNimType NTI311897; /* seq[TIndexEntry] */
extern TNimType NTI13606; /* seq[string] */
extern TNimType NTI189815; /* TSymSeq */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(NI, HEX2A_309020)(NI x, NU8 order) {
	NI result;
	NI y;
	NI TMP5844;
	NI TMP5845;
	nimfr("*", "algorithm.nim")
	result = 0;
	nimln(24, "algorithm.nim");
	TMP5844 = subInt(((NI) (order)), ((NI) 1));
	y = (NI)(TMP5844);
	nimln(25, "algorithm.nim");
	TMP5845 = subInt((NI)(x ^ ((NI) (y))), ((NI) (y)));
	result = (NI)(TMP5845);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, merge_312732)(Tindexentry311396* a, NI aLen0, Tindexentry311396* b, NI bLen0, NI lo, NI m, NI hi, TY312694 cmp, NU8 order) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr("merge", "algorithm.nim")
{	nimln(119, "algorithm.nim");
	{
		NI TMP5960;
		NI LOC3;
		NI LOC4;
		if ((NU)(m) >= (NU)(aLen0)) raiseIndexError();
		TMP5960 = addInt(m, ((NI) 1));
		if ((NU)((NI)(TMP5960)) >= (NU)(aLen0)) raiseIndexError();
		LOC3 = 0;
		LOC3 = cmp.ClEnv? cmp.ClPrc((&a[m]), (&a[(NI)(TMP5960)]), cmp.ClEnv):((TMP5961)(cmp.ClPrc))((&a[m]), (&a[(NI)(TMP5960)]));
		LOC4 = 0;
		LOC4 = HEX2A_309020(LOC3, order);
		if (!(LOC4 <= ((NI) 0))) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	nimln(120, "algorithm.nim");
	j = lo;
	nimln(122, "algorithm.nim");
	{
		if (!!((j <= m))) goto LA9;
		failedassertimpl_87017(((NimStringDesc*) &TMP5962));
	}
	LA9: ;
	nimln(124, "algorithm.nim");
	bb = ((NI) 0);
	{
		nimln(125, "algorithm.nim");
		while (1) {
			NI TMP5963;
			NI TMP5964;
			if (!(j <= m)) goto LA12;
			nimln(126, "algorithm.nim");
			if ((NU)(bb) >= (NU)(bLen0)) raiseIndexError();
			if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
			HEX3CHEX2D_311807((&b[bb]), (&a[j]));
			nimln(127, "algorithm.nim");
			TMP5963 = addInt(bb, ((NI) 1));
			bb = (NI)(TMP5963);
			nimln(128, "algorithm.nim");
			TMP5964 = addInt(j, ((NI) 1));
			j = (NI)(TMP5964);
		} LA12: ;
	}
	nimln(132, "algorithm.nim");
	i = ((NI) 0);
	nimln(133, "algorithm.nim");
	k = lo;
	{
		nimln(135, "algorithm.nim");
		while (1) {
			NIM_BOOL LOC15;
			NI TMP5968;
			LOC15 = 0;
			LOC15 = (k < j);
			if (!(LOC15)) goto LA16;
			LOC15 = (j <= hi);
			LA16: ;
			if (!LOC15) goto LA14;
			nimln(136, "algorithm.nim");
			{
				NI LOC19;
				NI LOC20;
				NI TMP5966;
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				LOC19 = 0;
				LOC19 = cmp.ClEnv? cmp.ClPrc((&b[i]), (&a[j]), cmp.ClEnv):((TMP5965)(cmp.ClPrc))((&b[i]), (&a[j]));
				LOC20 = 0;
				LOC20 = HEX2A_309020(LOC19, order);
				if (!(LOC20 <= ((NI) 0))) goto LA21;
				nimln(137, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				HEX3CHEX2D_311807((&a[k]), (&b[i]));
				nimln(138, "algorithm.nim");
				TMP5966 = addInt(i, ((NI) 1));
				i = (NI)(TMP5966);
			}
			goto LA17;
			LA21: ;
			{
				NI TMP5967;
				nimln(140, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				HEX3CHEX2D_311807((&a[k]), (&a[j]));
				nimln(141, "algorithm.nim");
				TMP5967 = addInt(j, ((NI) 1));
				j = (NI)(TMP5967);
			}
			LA17: ;
			nimln(142, "algorithm.nim");
			TMP5968 = addInt(k, ((NI) 1));
			k = (NI)(TMP5968);
		} LA14: ;
	}
	{
		nimln(145, "algorithm.nim");
		while (1) {
			NI TMP5969;
			NI TMP5970;
			if (!(k < j)) goto LA25;
			nimln(146, "algorithm.nim");
			if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
			if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
			HEX3CHEX2D_311807((&a[k]), (&b[i]));
			nimln(147, "algorithm.nim");
			TMP5969 = addInt(k, ((NI) 1));
			k = (NI)(TMP5969);
			nimln(148, "algorithm.nim");
			TMP5970 = addInt(i, ((NI) 1));
			i = (NI)(TMP5970);
		} LA25: ;
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sort_312687)(Tindexentry311396* a, NI aLen0, TY312694 cmp, NU8 order) {
	NI n;
	TY311897* b;
	NI TMP5955;
	NI s;
	nimfr("sort", "algorithm.nim")
	nimln(180, "algorithm.nim");
	n = aLen0;
	b = 0;
	nimln(182, "algorithm.nim");
	TMP5955 = divInt(n, ((NI) 2));
	b = (TY311897*) newSeq((&NTI311897), ((NI)chckRange((NI)(TMP5955), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(183, "algorithm.nim");
	s = ((NI) 1);
	{
		nimln(184, "algorithm.nim");
		while (1) {
			NI m;
			NI TMP5958;
			NI TMP5959;
			NI TMP5976;
			if (!(s < n)) goto LA2;
			nimln(185, "algorithm.nim");
			TMP5958 = subInt(n, ((NI) 1));
			TMP5959 = subInt((NI)(TMP5958), s);
			m = (NI)(TMP5959);
			{
				nimln(186, "algorithm.nim");
				while (1) {
					NI TMP5971;
					NI TMP5972;
					NI TMP5973;
					NI TMP5974;
					NI TMP5975;
					if (!(((NI) 0) <= m)) goto LA4;
					nimln(187, "algorithm.nim");
					TMP5971 = subInt(m, s);
					TMP5972 = addInt((NI)(TMP5971), ((NI) 1));
					TMP5973 = addInt(m, s);
					merge_312732(a, aLen0, b->data, b->Sup.len, (((NI)(TMP5972) >= ((NI) 0)) ? (NI)(TMP5972) : ((NI) 0)), m, (NI)(TMP5973), cmp, order);
					nimln(188, "algorithm.nim");
					TMP5974 = mulInt(s, ((NI) 2));
					TMP5975 = subInt(m, (NI)(TMP5974));
					m = (NI)(TMP5975);
				} LA4: ;
			}
			nimln(189, "algorithm.nim");
			TMP5976 = mulInt(s, ((NI) 2));
			s = (NI)(TMP5976);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, merge_314346)(NimStringDesc** a, NI aLen0, NimStringDesc** b, NI bLen0, NI lo, NI m, NI hi, TY314308 cmp, NU8 order) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr("merge", "algorithm.nim")
{	nimln(119, "algorithm.nim");
	{
		NI TMP6006;
		NI LOC3;
		NI LOC4;
		if ((NU)(m) >= (NU)(aLen0)) raiseIndexError();
		TMP6006 = addInt(m, ((NI) 1));
		if ((NU)((NI)(TMP6006)) >= (NU)(aLen0)) raiseIndexError();
		LOC3 = 0;
		LOC3 = cmp.ClEnv? cmp.ClPrc(a[m], a[(NI)(TMP6006)], cmp.ClEnv):((TMP6007)(cmp.ClPrc))(a[m], a[(NI)(TMP6006)]);
		LOC4 = 0;
		LOC4 = HEX2A_309020(LOC3, order);
		if (!(LOC4 <= ((NI) 0))) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	nimln(120, "algorithm.nim");
	j = lo;
	nimln(122, "algorithm.nim");
	{
		if (!!((j <= m))) goto LA9;
		failedassertimpl_87017(((NimStringDesc*) &TMP5962));
	}
	LA9: ;
	nimln(124, "algorithm.nim");
	bb = ((NI) 0);
	{
		nimln(125, "algorithm.nim");
		while (1) {
			NI TMP6008;
			NI TMP6009;
			if (!(j <= m)) goto LA12;
			nimln(112, "algorithm.nim");
			if ((NU)(bb) >= (NU)(bLen0)) raiseIndexError();
			if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
			unsureAsgnRef((void**) (&b[bb]), a[j]);
			nimln(127, "algorithm.nim");
			TMP6008 = addInt(bb, ((NI) 1));
			bb = (NI)(TMP6008);
			nimln(128, "algorithm.nim");
			TMP6009 = addInt(j, ((NI) 1));
			j = (NI)(TMP6009);
		} LA12: ;
	}
	nimln(132, "algorithm.nim");
	i = ((NI) 0);
	nimln(133, "algorithm.nim");
	k = lo;
	{
		nimln(135, "algorithm.nim");
		while (1) {
			NIM_BOOL LOC15;
			NI TMP6013;
			LOC15 = 0;
			LOC15 = (k < j);
			if (!(LOC15)) goto LA16;
			LOC15 = (j <= hi);
			LA16: ;
			if (!LOC15) goto LA14;
			nimln(136, "algorithm.nim");
			{
				NI LOC19;
				NI LOC20;
				NI TMP6011;
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				LOC19 = 0;
				LOC19 = cmp.ClEnv? cmp.ClPrc(b[i], a[j], cmp.ClEnv):((TMP6010)(cmp.ClPrc))(b[i], a[j]);
				LOC20 = 0;
				LOC20 = HEX2A_309020(LOC19, order);
				if (!(LOC20 <= ((NI) 0))) goto LA21;
				nimln(112, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				unsureAsgnRef((void**) (&a[k]), b[i]);
				nimln(138, "algorithm.nim");
				TMP6011 = addInt(i, ((NI) 1));
				i = (NI)(TMP6011);
			}
			goto LA17;
			LA21: ;
			{
				NI TMP6012;
				nimln(112, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				unsureAsgnRef((void**) (&a[k]), a[j]);
				nimln(141, "algorithm.nim");
				TMP6012 = addInt(j, ((NI) 1));
				j = (NI)(TMP6012);
			}
			LA17: ;
			nimln(142, "algorithm.nim");
			TMP6013 = addInt(k, ((NI) 1));
			k = (NI)(TMP6013);
		} LA14: ;
	}
	{
		nimln(145, "algorithm.nim");
		while (1) {
			NI TMP6014;
			NI TMP6015;
			if (!(k < j)) goto LA25;
			nimln(112, "algorithm.nim");
			if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
			if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
			unsureAsgnRef((void**) (&a[k]), b[i]);
			nimln(147, "algorithm.nim");
			TMP6014 = addInt(k, ((NI) 1));
			k = (NI)(TMP6014);
			nimln(148, "algorithm.nim");
			TMP6015 = addInt(i, ((NI) 1));
			i = (NI)(TMP6015);
		} LA25: ;
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sort_314301)(NimStringDesc** a, NI aLen0, TY314308 cmp, NU8 order) {
	NI n;
	TY13606* b;
	NI TMP6003;
	NI s;
	nimfr("sort", "algorithm.nim")
	nimln(180, "algorithm.nim");
	n = aLen0;
	b = 0;
	nimln(182, "algorithm.nim");
	TMP6003 = divInt(n, ((NI) 2));
	b = (TY13606*) newSeq((&NTI13606), ((NI)chckRange((NI)(TMP6003), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(183, "algorithm.nim");
	s = ((NI) 1);
	{
		nimln(184, "algorithm.nim");
		while (1) {
			NI m;
			NI TMP6004;
			NI TMP6005;
			NI TMP6021;
			if (!(s < n)) goto LA2;
			nimln(185, "algorithm.nim");
			TMP6004 = subInt(n, ((NI) 1));
			TMP6005 = subInt((NI)(TMP6004), s);
			m = (NI)(TMP6005);
			{
				nimln(186, "algorithm.nim");
				while (1) {
					NI TMP6016;
					NI TMP6017;
					NI TMP6018;
					NI TMP6019;
					NI TMP6020;
					if (!(((NI) 0) <= m)) goto LA4;
					nimln(187, "algorithm.nim");
					TMP6016 = subInt(m, s);
					TMP6017 = addInt((NI)(TMP6016), ((NI) 1));
					TMP6018 = addInt(m, s);
					merge_314346(a, aLen0, b->data, b->Sup.len, (((NI)(TMP6017) >= ((NI) 0)) ? (NI)(TMP6017) : ((NI) 0)), m, (NI)(TMP6018), cmp, order);
					nimln(188, "algorithm.nim");
					TMP6019 = mulInt(s, ((NI) 2));
					TMP6020 = subInt(m, (NI)(TMP6019));
					m = (NI)(TMP6020);
				} LA4: ;
			}
			nimln(189, "algorithm.nim");
			TMP6021 = mulInt(s, ((NI) 2));
			s = (NI)(TMP6021);
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, merge_350563)(Tsym189843** a, NI aLen0, Tsym189843** b, NI bLen0, NI lo, NI m, NI hi, TY350525 cmp, NU8 order) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr("merge", "algorithm.nim")
{	nimln(119, "algorithm.nim");
	{
		NI TMP6966;
		NI LOC3;
		NI LOC4;
		if ((NU)(m) >= (NU)(aLen0)) raiseIndexError();
		TMP6966 = addInt(m, ((NI) 1));
		if ((NU)((NI)(TMP6966)) >= (NU)(aLen0)) raiseIndexError();
		LOC3 = 0;
		LOC3 = cmp.ClEnv? cmp.ClPrc(a[m], a[(NI)(TMP6966)], cmp.ClEnv):((TMP6967)(cmp.ClPrc))(a[m], a[(NI)(TMP6966)]);
		LOC4 = 0;
		LOC4 = HEX2A_309020(LOC3, order);
		if (!(LOC4 <= ((NI) 0))) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	nimln(120, "algorithm.nim");
	j = lo;
	nimln(122, "algorithm.nim");
	{
		if (!!((j <= m))) goto LA9;
		failedassertimpl_87017(((NimStringDesc*) &TMP5962));
	}
	LA9: ;
	nimln(124, "algorithm.nim");
	bb = ((NI) 0);
	{
		nimln(125, "algorithm.nim");
		while (1) {
			NI TMP6968;
			NI TMP6969;
			if (!(j <= m)) goto LA12;
			nimln(112, "algorithm.nim");
			if ((NU)(bb) >= (NU)(bLen0)) raiseIndexError();
			if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
			unsureAsgnRef((void**) (&b[bb]), a[j]);
			nimln(127, "algorithm.nim");
			TMP6968 = addInt(bb, ((NI) 1));
			bb = (NI)(TMP6968);
			nimln(128, "algorithm.nim");
			TMP6969 = addInt(j, ((NI) 1));
			j = (NI)(TMP6969);
		} LA12: ;
	}
	nimln(132, "algorithm.nim");
	i = ((NI) 0);
	nimln(133, "algorithm.nim");
	k = lo;
	{
		nimln(135, "algorithm.nim");
		while (1) {
			NIM_BOOL LOC15;
			NI TMP6973;
			LOC15 = 0;
			LOC15 = (k < j);
			if (!(LOC15)) goto LA16;
			LOC15 = (j <= hi);
			LA16: ;
			if (!LOC15) goto LA14;
			nimln(136, "algorithm.nim");
			{
				NI LOC19;
				NI LOC20;
				NI TMP6971;
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				LOC19 = 0;
				LOC19 = cmp.ClEnv? cmp.ClPrc(b[i], a[j], cmp.ClEnv):((TMP6970)(cmp.ClPrc))(b[i], a[j]);
				LOC20 = 0;
				LOC20 = HEX2A_309020(LOC19, order);
				if (!(LOC20 <= ((NI) 0))) goto LA21;
				nimln(112, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
				unsureAsgnRef((void**) (&a[k]), b[i]);
				nimln(138, "algorithm.nim");
				TMP6971 = addInt(i, ((NI) 1));
				i = (NI)(TMP6971);
			}
			goto LA17;
			LA21: ;
			{
				NI TMP6972;
				nimln(112, "algorithm.nim");
				if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
				if ((NU)(j) >= (NU)(aLen0)) raiseIndexError();
				unsureAsgnRef((void**) (&a[k]), a[j]);
				nimln(141, "algorithm.nim");
				TMP6972 = addInt(j, ((NI) 1));
				j = (NI)(TMP6972);
			}
			LA17: ;
			nimln(142, "algorithm.nim");
			TMP6973 = addInt(k, ((NI) 1));
			k = (NI)(TMP6973);
		} LA14: ;
	}
	{
		nimln(145, "algorithm.nim");
		while (1) {
			NI TMP6974;
			NI TMP6975;
			if (!(k < j)) goto LA25;
			nimln(112, "algorithm.nim");
			if ((NU)(k) >= (NU)(aLen0)) raiseIndexError();
			if ((NU)(i) >= (NU)(bLen0)) raiseIndexError();
			unsureAsgnRef((void**) (&a[k]), b[i]);
			nimln(147, "algorithm.nim");
			TMP6974 = addInt(k, ((NI) 1));
			k = (NI)(TMP6974);
			nimln(148, "algorithm.nim");
			TMP6975 = addInt(i, ((NI) 1));
			i = (NI)(TMP6975);
		} LA25: ;
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sort_350518)(Tsym189843** a, NI aLen0, TY350525 cmp, NU8 order) {
	NI n;
	Tsymseq189815* b;
	NI TMP6963;
	NI s;
	nimfr("sort", "algorithm.nim")
	nimln(180, "algorithm.nim");
	n = aLen0;
	b = 0;
	nimln(182, "algorithm.nim");
	TMP6963 = divInt(n, ((NI) 2));
	b = (Tsymseq189815*) newSeq((&NTI189815), ((NI)chckRange((NI)(TMP6963), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(183, "algorithm.nim");
	s = ((NI) 1);
	{
		nimln(184, "algorithm.nim");
		while (1) {
			NI m;
			NI TMP6964;
			NI TMP6965;
			NI TMP6981;
			if (!(s < n)) goto LA2;
			nimln(185, "algorithm.nim");
			TMP6964 = subInt(n, ((NI) 1));
			TMP6965 = subInt((NI)(TMP6964), s);
			m = (NI)(TMP6965);
			{
				nimln(186, "algorithm.nim");
				while (1) {
					NI TMP6976;
					NI TMP6977;
					NI TMP6978;
					NI TMP6979;
					NI TMP6980;
					if (!(((NI) 0) <= m)) goto LA4;
					nimln(187, "algorithm.nim");
					TMP6976 = subInt(m, s);
					TMP6977 = addInt((NI)(TMP6976), ((NI) 1));
					TMP6978 = addInt(m, s);
					merge_350563(a, aLen0, b->data, b->Sup.len, (((NI)(TMP6977) >= ((NI) 0)) ? (NI)(TMP6977) : ((NI) 0)), m, (NI)(TMP6978), cmp, order);
					nimln(188, "algorithm.nim");
					TMP6979 = mulInt(s, ((NI) 2));
					TMP6980 = subInt(m, (NI)(TMP6979));
					m = (NI)(TMP6980);
				} LA4: ;
			}
			nimln(189, "algorithm.nim");
			TMP6981 = mulInt(s, ((NI) 2));
			s = (NI)(TMP6981);
		} LA2: ;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void) {
	nimfr("algorithm", "algorithm.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void) {
}

