/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Processobj146402 Processobj146402;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY147201 TY147201;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Stringtableobj137012 Stringtableobj137012;
typedef struct Streamobj141027 Streamobj141027;
typedef struct Tfilehandlestream147807 Tfilehandlestream147807;
typedef struct Keyvaluepairseq137010 Keyvaluepairseq137010;
typedef struct TY108548 TY108548;
typedef struct Tsecurityattributes105242 Tsecurityattributes105242;
typedef struct Tstartupinfo105244 Tstartupinfo105244;
typedef struct Tprocessinformation105246 Tprocessinformation105246;
typedef struct TY149210 TY149210;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TY77659[32];
typedef NimStringDesc* TY146637[1];
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Processobj146402  {
  TNimObject Sup;
NI fprocesshandle;
int inhandle;
int outhandle;
int errhandle;
NI id;
int exitcode;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, void* ClEnv);
void* ClEnv;
} TY146795;
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(void, TMP602) (NI idx);
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef N_CLOSURE_PTR(void, TMP605) (NI idx);
typedef N_CLOSURE_PTR(void, TMP610) (NI idx);
typedef N_NIMCALL_PTR(void, TY141028) (Streamobj141027* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY141032) (Streamobj141027* s);
typedef N_NIMCALL_PTR(void, TY141036) (Streamobj141027* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY141041) (Streamobj141027* s);
typedef N_NIMCALL_PTR(NI, TY141045) (Streamobj141027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY141051) (Streamobj141027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY141057) (Streamobj141027* s);
struct  Streamobj141027  {
  TNimObject Sup;
TY141028 closeimpl;
TY141032 atendimpl;
TY141036 setpositionimpl;
TY141041 getpositionimpl;
TY141045 readdataimpl;
TY141051 writedataimpl;
TY141057 flushimpl;
};
struct  Tfilehandlestream147807  {
  Streamobj141027 Sup;
NI handle;
NIM_BOOL attheend;
};
typedef N_STDCALL_PTR(NI32, TY105431) (NI hfile, void* Buffer, NI32 nnumberofbytestoread, NI32* lpnumberofbytesread, void* lpoverlapped);
typedef N_STDCALL_PTR(NI32, TY105442) (NI hfile, void* Buffer, NI32 nnumberofbytestowrite, NI32* lpnumberofbyteswritten, void* lpoverlapped);
struct  Stringtableobj137012  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq137010* data;
NU8 mode;
};
struct TY108548 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Tsecurityattributes105242  {
NI32 nlength;
void* lpsecuritydescriptor;
NI32 binherithandle;
};
typedef N_STDCALL_PTR(NI32, TY105453) (NI* hreadpipe, NI* hwritepipe, Tsecurityattributes105242* lppipeattributes, NI32 nsize);
typedef N_STDCALL_PTR(NI32, TY105425) (NI hobject);
struct  Tstartupinfo105244  {
NI32 cb;
NCSTRING lpreserved;
NCSTRING lpdesktop;
NCSTRING lptitle;
NI32 dwx;
NI32 dwy;
NI32 dwxsize;
NI32 dwysize;
NI32 dwxcountchars;
NI32 dwycountchars;
NI32 dwfillattribute;
NI32 dwflags;
NI16 wshowwindow;
NI16 cbreserved2;
void* lpreserved2;
NI hstdinput;
NI hstdoutput;
NI hstderror;
};
struct  Tprocessinformation105246  {
NI hprocess;
NI hthread;
NI32 dwprocessid;
NI32 dwthreadid;
};
typedef N_STDCALL_PTR(NI, TY105639) (NI32 nstdhandle);
typedef N_STDCALL_PTR(NI32, TY105464) (NI16* lpapplicationname, NI16* lpcommandline, Tsecurityattributes105242* lpprocessattributes, Tsecurityattributes105242* lpthreadattributes, NI32 binherithandles, NI32 dwcreationflags, NI16* lpenvironment, NI16* lpcurrentdirectory, Tstartupinfo105244* lpstartupinfo, Tprocessinformation105246* lpprocessinformation);
typedef N_STDCALL_PTR(NI32, TY105605) (NI hthread);
typedef N_STDCALL_PTR(NI32, TY105611) (NI hthread);
typedef N_STDCALL_PTR(NI32, TY105617) (NI hhandle, NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI32, TY105624) (NI hprocess, NI uexitcode);
typedef N_STDCALL_PTR(NI32, TY105631) (NI hprocess, NI32* lpexitcode);
typedef NI Twohandlearray107273[64];
typedef N_STDCALL_PTR(NI32, TY107281) (NI32 ncount, NI* lphandles, NI32 bwaitall, NI32 dwmilliseconds);
struct TY149210 {
NimStringDesc* Field0;
NI Field1;
};
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct TY147201 {
  TGenericSeq Sup;
  Processobj146402* data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq137010 {
  TGenericSeq Sup;
  TY108548 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, nospquoteShellWindows)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, contains_101373)(NimStringDesc* s, TY77659 chars);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, allcharsinset_100459)(NimStringDesc* s, TY77659 theset);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s);
N_NIMCALL(Processobj146402*, startcmd_146646)(NimStringDesc* command, NU8 options);
N_NIMCALL(NI, nospprocessID)(Processobj146402* p);
N_NIMCALL(int, nospinputHandle)(Processobj146402* p);
N_NIMCALL(int, nospoutputHandle)(Processobj146402* p);
N_NIMCALL(int, nosperrorHandle)(Processobj146402* p);
N_NIMCALL(NI, nospcountProcessors)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds, NI cmdsLen0, NU8 options, NI n, TY146795 beforerunevent);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, TMP598)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP599)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_52622)(Tcell46746* c);
static N_INLINE(NIM_BOOL, canbecycleroot_50267)(Tcell46746* c);
static N_INLINE(void, rtladdcycleroot_51023)(Tcell46746* c);
N_NOINLINE(void, incl_47465)(Tcellset46758* s, Tcell46746* cell);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, decref_52204)(Tcell46746* c);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, nossleep)(NI milsecs);
N_NIMCALL(NimStringDesc*, nospexecProcess)(NimStringDesc* command, NimStringDesc** args, NI argsLen0, Stringtableobj137012* env, NU8 options);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NIM_BOOL, readline_141509)(Streamobj141027* s, NimStringDesc** line);
N_NIMCALL(void, del_149033)(TY147201** x, NI i);
N_NIMCALL(void, hsclose_147810)(Streamobj141027* s);
N_NIMCALL(NIM_BOOL, hsatend_147816)(Streamobj141027* s);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, hsreaddata_147823)(Streamobj141027* s_147825, void* buffer, NI buflen);
N_NIMCALL(void, raiseoserror_115430)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_115454)(void);
N_NIMCALL(void, hswritedata_147838)(Streamobj141027* s_147840, void* buffer, NI buflen);
N_NIMCALL(Tfilehandlestream147807*, newfilehandlestream_147852)(NI handle);
N_NIMCALL(void, TMP619)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NCSTRING, buildcommandline_147867)(NimStringDesc* a, NimStringDesc** args, NI argsLen0);
N_NOCONV(void*, alloc0_6017)(NI size);
N_NIMCALL(NCSTRING, buildenv_147906)(Stringtableobj137012* env);
N_NIMCALL(void, createpipehandles_147985)(NI* rdhandle, NI* wrhandle);
static N_INLINE(void, fileclose_148001)(NI h);
N_NIMCALL(Processobj146402*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj137012* env, NU8 options);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NI16*, newwidecstring_81144)(NCSTRING s);
N_NOCONV(void, dealloc_6048)(void* p);
N_NIMCALL(void, nospsuspend)(Processobj146402* p);
N_NIMCALL(void, nospresume)(Processobj146402* p);
N_NIMCALL(NIM_BOOL, nosprunning)(Processobj146402* p);
N_NIMCALL(void, nospterminate)(Processobj146402* p);
N_NIMCALL(void, nospkill)(Processobj146402* p);
N_NIMCALL(NI, nospwaitForExit)(Processobj146402* p, NI timeout);
N_NIMCALL(NI, peekexitcode_146725)(Processobj146402* p);
N_NIMCALL(Streamobj141027*, nospinputStream)(Processobj146402* p);
N_NIMCALL(Streamobj141027*, nospoutputStream)(Processobj146402* p);
N_NIMCALL(Streamobj141027*, nosperrorStream)(Processobj146402* p);
N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command);
N_NIMCALL(NI16*, newwidecstring_81205)(NimStringDesc* s);
N_NIMCALL(NI, select_147608)(TY147201** readfds, NI timeout);
N_NIMCALL(void, execcmdex_149204)(NimStringDesc* command, NU8 options, TY149210* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, nospclose)(Processobj146402* p);
static NIM_CONST TY77659 TMP570 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP571, "", 0);
STRING_LITERAL(TMP572, "\"", 1);
STRING_LITERAL(TMP573, "\\\"", 2);
STRING_LITERAL(TMP575, "len(a) == L string modified while iterating over it", 51);
NIM_CONST TY77659 safeunixchars_146464 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP576, "\'\'", 2);
static NIM_CONST TY77659 TMP579 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP580, "\'", 1);
STRING_LITERAL(TMP595, "\'\"\'\"\'", 5);
STRING_LITERAL(TMP596, "0 < n ", 6);
static NIM_CONST TY146795 TMP601 = {NIM_NIL,NIM_NIL};
STRING_LITERAL(TMP612, "", 0);
STRING_LITERAL(TMP613, "\015\012", 2);
STRING_LITERAL(TMP627, "=", 1);
STRING_LITERAL(TMP632, "len(args) == 0 ", 15);
STRING_LITERAL(TMP633, "len(readfds) <= 0x00000040 ", 27);
NIM_CONST TY149210 TMP637 = {((NimStringDesc*) &TMP612),
((NI) -1)}
;
extern TFrame* frameptr_17042;
extern TNimType NTI3411; /* RootObj */
TNimType NTI146402; /* ProcessObj */
extern TNimType NTI105222; /* THandle */
extern TNimType NTI13008; /* FileHandle */
extern TNimType NTI5811; /* cint */
TNimType NTI146404; /* Process */
TNimType NTI147201; /* seq[Process] */
extern Tgcheap48616 gch_48644;
extern TNimType NTI141027; /* StreamObj */
TNimType NTI147807; /* TFileHandleStream */
extern TNimType NTI138; /* bool */
extern TY105431 Dl_105430;
extern TY105442 Dl_105441;
TNimType NTI147805; /* PFileHandleStream */
extern TY105453 Dl_105452;
extern TY105425 Dl_105424;
extern TY105639 Dl_105638;
extern TY105464 Dl_105463;
extern TY105605 Dl_105604;
extern TY105611 Dl_105610;
extern TY105617 Dl_105616;
extern TY105624 Dl_105623;
extern TY105631 Dl_105630;
extern TY107281 Dl_107280;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NimStringDesc*, nospquoteShellWindows)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_BOOL needquote;
	NIM_BOOL LOC1;
	NimStringDesc* backslashbuff;
	nimfr("quoteShellWindows", "osproc.nim")
	result = 0;
	nimln(60, "osproc.nim");
	LOC1 = 0;
	LOC1 = contains_101373(s, TMP570);
	if (LOC1) goto LA2;
	LOC1 = ((s ? s->Sup.len : 0) == ((NI) 0));
	LA2: ;
	needquote = LOC1;
	nimln(62, "osproc.nim");
	result = copyString(((NimStringDesc*) &TMP571));
	nimln(63, "osproc.nim");
	backslashbuff = copyString(((NimStringDesc*) &TMP571));
	nimln(64, "osproc.nim");
	{
		if (!needquote) goto LA5;
		nimln(65, "osproc.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP572));
	}
	LA5: ;
	{
		NIM_CHAR c_146438;
		NI i_146442;
		NI L_146444;
		c_146438 = 0;
		nimln(3102, "system.nim");
		i_146442 = ((NI) 0);
		nimln(3103, "system.nim");
		L_146444 = (s ? s->Sup.len : 0);
		{
			nimln(3104, "system.nim");
			while (1) {
				NI TMP574;
				if (!(i_146442 < L_146444)) goto LA9;
				nimln(3105, "system.nim");
				if ((NU)(i_146442) > (NU)(s->Sup.len)) raiseIndexError();
				c_146438 = s->data[i_146442];
				nimln(68, "osproc.nim");
				{
					if (!((NU8)(c_146438) == (NU8)(92))) goto LA12;
					nimln(69, "osproc.nim");
					backslashbuff = addChar(backslashbuff, c_146438);
				}
				goto LA10;
				LA12: ;
				{
					nimln(70, "osproc.nim");
					if (!((NU8)(c_146438) == (NU8)(34))) goto LA15;
					nimln(71, "osproc.nim");
					result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
					nimln(72, "osproc.nim");
					result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
					nimln(73, "osproc.nim");
					backslashbuff = setLengthStr(backslashbuff, ((NI) 0));
					nimln(74, "osproc.nim");
					result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP573));
				}
				goto LA10;
				LA15: ;
				{
					nimln(76, "osproc.nim");
					{
						if (!!(((backslashbuff ? backslashbuff->Sup.len : 0) == ((NI) 0)))) goto LA20;
						nimln(77, "osproc.nim");
						result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
						nimln(78, "osproc.nim");
						backslashbuff = setLengthStr(backslashbuff, ((NI) 0));
					}
					LA20: ;
					nimln(79, "osproc.nim");
					result = addChar(result, c_146438);
				}
				LA10: ;
				nimln(3106, "system.nim");
				TMP574 = addInt(i_146442, ((NI) 1));
				i_146442 = (NI)(TMP574);
				nimln(3107, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_146444))) goto LA24;
					failedassertimpl_88817(((NimStringDesc*) &TMP575));
				}
				LA24: ;
			} LA9: ;
		}
	}
	nimln(81, "osproc.nim");
	{
		if (!needquote) goto LA28;
		nimln(82, "osproc.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP572));
	}
	LA28: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_BOOL safe;
	nimfr("quoteShellPosix", "osproc.nim")
{	result = 0;
	nimln(89, "osproc.nim");
	{
		if (!((s ? s->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(90, "osproc.nim");
		result = copyString(((NimStringDesc*) &TMP576));
		goto BeforeRet;
	}
	LA3: ;
	nimln(92, "osproc.nim");
	safe = allcharsinset_100459(s, TMP579);
	nimln(94, "osproc.nim");
	{
		if (!safe) goto LA7;
		nimln(95, "osproc.nim");
		result = copyString(s);
		goto BeforeRet;
	}
	goto LA5;
	LA7: ;
	{
		NimStringDesc* LOC10;
		NimStringDesc* LOC11;
		nimln(97, "osproc.nim");
		LOC10 = 0;
		LOC11 = 0;
		LOC11 = nsuReplaceStr(s, ((NimStringDesc*) &TMP580), ((NimStringDesc*) &TMP595));
		LOC10 = rawNewString(LOC11->Sup.len + 2);
appendString(LOC10, ((NimStringDesc*) &TMP580));
appendString(LOC10, LOC11);
appendString(LOC10, ((NimStringDesc*) &TMP580));
		result = LOC10;
		goto BeforeRet;
	}
	LA5: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("quoteShell", "osproc.nim")
{	result = 0;
	nimln(102, "osproc.nim");
	result = nospquoteShellWindows(s);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Processobj146402*, startcmd_146646)(NimStringDesc* command, NU8 options) {
	Processobj146402* result;
	TY146637 LOC1;
	nimfr("startCmd", "osproc.nim")
	result = 0;
	nimln(158, "osproc.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	result = nospstartProcess(command, ((NimStringDesc*) &TMP571), LOC1, 0, NIM_NIL, (options | 4));
	popFrame();
	return result;
}

N_NIMCALL(NI, nospprocessID)(Processobj146402* p) {
	NI result;
	nimfr("processID", "osproc.nim")
{	result = 0;
	nimln(183, "osproc.nim");
	result = (*p).id;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, nospinputHandle)(Processobj146402* p) {
	int result;
	nimfr("inputHandle", "osproc.nim")
	result = 0;
	nimln(219, "osproc.nim");
	result = (*p).inhandle;
	popFrame();
	return result;
}

N_NIMCALL(int, nospoutputHandle)(Processobj146402* p) {
	int result;
	nimfr("outputHandle", "osproc.nim")
	result = 0;
	nimln(227, "osproc.nim");
	result = (*p).outhandle;
	popFrame();
	return result;
}

N_NIMCALL(int, nosperrorHandle)(Processobj146402* p) {
	int result;
	nimfr("errorHandle", "osproc.nim")
	result = 0;
	nimln(235, "osproc.nim");
	result = (*p).errhandle;
	popFrame();
	return result;
}

N_NIMCALL(NI, nospcountProcessors)(void) {
	NI result;
	nimfr("countProcessors", "osproc.nim")
	result = 0;
	nimln(240, "osproc.nim");
	result = ncpicountProcessors();
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP598)(void* p, NI op) {
	Processobj146402* a;
	a = (Processobj146402*)p;
}
N_NIMCALL(void, TMP599)(void* p, NI op) {
	TY147201* a;
	NI LOC1;
	a = (TY147201*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_50267)(Tcell46746* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_51023)(Tcell46746* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(139, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(191, "gc.nim");
		incl_47465((&gch_48644.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_52622)(Tcell46746* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_50267(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_51023(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, decref_52204)(Tcell46746* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_51804(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_50267(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_51023(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		Tcell46746* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_50246(src);
		incref_52622(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		Tcell46746* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_50246((*dest));
		decref_52204(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds, NI cmdsLen0, NU8 options, NI n, TY146795 beforerunevent) {
	NI result;
	nimfr("execProcesses", "osproc.nim")
	result = 0;
	nimln(255, "osproc.nim");
	{
		if (!!((((NI) 0) < n))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP596));
	}
	LA3: ;
	nimln(256, "osproc.nim");
	{
		TY147201* q;
		NI m;
		NI i;
		if (!(((NI) 1) < n)) goto LA7;
		q = 0;
		nimln(258, "osproc.nim");
		q = (TY147201*) newSeq((&NTI147201), ((NI)chckRange(n, ((NI) 0), ((NI) 2147483647))));
		nimln(259, "osproc.nim");
		m = ((n <= cmdsLen0) ? n : cmdsLen0);
		{
			NI i_147235;
			NI HEX3Atmp_147528;
			NI TMP600;
			NI res_147531;
			i_147235 = 0;
			HEX3Atmp_147528 = 0;
			nimln(260, "osproc.nim");
			TMP600 = subInt(m, ((NI) 1));
			HEX3Atmp_147528 = (NI)(TMP600);
			nimln(1598, "system.nim");
			res_147531 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					TY146637 LOC16;
					NI TMP603;
					if (!(res_147531 <= HEX3Atmp_147528)) goto LA11;
					nimln(1600, "system.nim");
					i_147235 = res_147531;
					nimln(261, "osproc.nim");
					{
						if (!!((beforerunevent.ClPrc == TMP601.ClPrc && beforerunevent.ClEnv == TMP601.ClEnv))) goto LA14;
						nimln(262, "osproc.nim");
						beforerunevent.ClEnv? beforerunevent.ClPrc(i_147235, beforerunevent.ClEnv):((TMP602)(beforerunevent.ClPrc))(i_147235);
					}
					LA14: ;
					nimln(263, "osproc.nim");
					if ((NU)(i_147235) >= (NU)(q->Sup.len)) raiseIndexError();
					if ((NU)(i_147235) >= (NU)(cmdsLen0)) raiseIndexError();
					memset((void*)LOC16, 0, sizeof(LOC16));
					asgnRef((void**) (&q->data[i_147235]), nospstartProcess(cmds[i_147235], ((NimStringDesc*) &TMP571), LOC16, 0, NIM_NIL, (options | 4)));
					nimln(1619, "system.nim");
					TMP603 = addInt(res_147531, ((NI) 1));
					res_147531 = (NI)(TMP603);
				} LA11: ;
			}
		}
		nimln(281, "osproc.nim");
		i = m;
		{
			nimln(282, "osproc.nim");
			while (1) {
				if (!(i <= (cmdsLen0-1))) goto LA18;
				nimln(283, "osproc.nim");
				nossleep(((NI) 50));
				{
					NI r_147413;
					NI HEX3Atmp_147537;
					NI TMP604;
					NI res_147540;
					r_147413 = 0;
					HEX3Atmp_147537 = 0;
					nimln(284, "osproc.nim");
					TMP604 = subInt(n, ((NI) 1));
					HEX3Atmp_147537 = (NI)(TMP604);
					nimln(1598, "system.nim");
					res_147540 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP607;
							if (!(res_147540 <= HEX3Atmp_147537)) goto LA21;
							nimln(1600, "system.nim");
							r_147413 = res_147540;
							nimln(285, "osproc.nim");
							{
								NIM_BOOL LOC24;
								NI LOC27;
								TY146637 LOC36;
								NI TMP606;
								if ((NU)(r_147413) >= (NU)(q->Sup.len)) raiseIndexError();
								LOC24 = 0;
								LOC24 = nosprunning(q->data[r_147413]);
								if (!!(LOC24)) goto LA25;
								nimln(287, "osproc.nim");
								if ((NU)(r_147413) >= (NU)(q->Sup.len)) raiseIndexError();
								LOC27 = 0;
								LOC27 = nospwaitForExit(q->data[r_147413], ((NI) -1));
								result = ((LOC27 >= result) ? LOC27 : result);
								nimln(288, "osproc.nim");
								{
									if ((NU)(r_147413) >= (NU)(q->Sup.len)) raiseIndexError();
									if (!!((q->data[r_147413] == NIM_NIL))) goto LA30;
									if ((NU)(r_147413) >= (NU)(q->Sup.len)) raiseIndexError();
									nospclose(q->data[r_147413]);
								}
								LA30: ;
								nimln(289, "osproc.nim");
								{
									if (!!((beforerunevent.ClPrc == TMP601.ClPrc && beforerunevent.ClEnv == TMP601.ClEnv))) goto LA34;
									nimln(290, "osproc.nim");
									beforerunevent.ClEnv? beforerunevent.ClPrc(i, beforerunevent.ClEnv):((TMP605)(beforerunevent.ClPrc))(i);
								}
								LA34: ;
								nimln(291, "osproc.nim");
								if ((NU)(r_147413) >= (NU)(q->Sup.len)) raiseIndexError();
								if ((NU)(i) >= (NU)(cmdsLen0)) raiseIndexError();
								memset((void*)LOC36, 0, sizeof(LOC36));
								asgnRef((void**) (&q->data[r_147413]), nospstartProcess(cmds[i], ((NimStringDesc*) &TMP571), LOC36, 0, NIM_NIL, (options | 4)));
								nimln(292, "osproc.nim");
								TMP606 = addInt(i, ((NI) 1));
								i = (NI)(TMP606);
								nimln(293, "osproc.nim");
								{
									if (!((cmdsLen0-1) < i)) goto LA39;
									goto LA19;
								}
								LA39: ;
							}
							LA25: ;
							nimln(1619, "system.nim");
							TMP607 = addInt(res_147540, ((NI) 1));
							res_147540 = (NI)(TMP607);
						} LA21: ;
					}
				} LA19: ;
			} LA18: ;
		}
		{
			NI j_147471;
			NI HEX3Atmp_147545;
			NI TMP608;
			NI res_147548;
			j_147471 = 0;
			HEX3Atmp_147545 = 0;
			nimln(294, "osproc.nim");
			TMP608 = subInt(m, ((NI) 1));
			HEX3Atmp_147545 = (NI)(TMP608);
			nimln(1598, "system.nim");
			res_147548 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI LOC44;
					NI TMP609;
					if (!(res_147548 <= HEX3Atmp_147545)) goto LA43;
					nimln(1600, "system.nim");
					j_147471 = res_147548;
					nimln(295, "osproc.nim");
					if ((NU)(j_147471) >= (NU)(q->Sup.len)) raiseIndexError();
					LOC44 = 0;
					LOC44 = nospwaitForExit(q->data[j_147471], ((NI) -1));
					result = ((LOC44 >= result) ? LOC44 : result);
					nimln(296, "osproc.nim");
					{
						if ((NU)(j_147471) >= (NU)(q->Sup.len)) raiseIndexError();
						if (!!((q->data[j_147471] == NIM_NIL))) goto LA47;
						if ((NU)(j_147471) >= (NU)(q->Sup.len)) raiseIndexError();
						nospclose(q->data[j_147471]);
					}
					LA47: ;
					nimln(1619, "system.nim");
					TMP609 = addInt(res_147548, ((NI) 1));
					res_147548 = (NI)(TMP609);
				} LA43: ;
			}
		}
	}
	goto LA5;
	LA7: ;
	{
		{
			NI i_147498;
			NI HEX3Atmp_147553;
			NI res_147556;
			i_147498 = 0;
			HEX3Atmp_147553 = 0;
			nimln(298, "osproc.nim");
			HEX3Atmp_147553 = (cmdsLen0-1);
			nimln(1598, "system.nim");
			res_147556 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					Processobj146402* p;
					TY146637 LOC57;
					NI LOC58;
					NI TMP611;
					if (!(res_147556 <= HEX3Atmp_147553)) goto LA52;
					nimln(1600, "system.nim");
					i_147498 = res_147556;
					nimln(299, "osproc.nim");
					{
						if (!!((beforerunevent.ClPrc == TMP601.ClPrc && beforerunevent.ClEnv == TMP601.ClEnv))) goto LA55;
						nimln(300, "osproc.nim");
						beforerunevent.ClEnv? beforerunevent.ClPrc(i_147498, beforerunevent.ClEnv):((TMP610)(beforerunevent.ClPrc))(i_147498);
					}
					LA55: ;
					nimln(301, "osproc.nim");
					if ((NU)(i_147498) >= (NU)(cmdsLen0)) raiseIndexError();
					memset((void*)LOC57, 0, sizeof(LOC57));
					p = nospstartProcess(cmds[i_147498], ((NimStringDesc*) &TMP571), LOC57, 0, NIM_NIL, (options | 4));
					nimln(302, "osproc.nim");
					LOC58 = 0;
					LOC58 = nospwaitForExit(p, ((NI) -1));
					result = ((LOC58 >= result) ? LOC58 : result);
					nimln(303, "osproc.nim");
					nospclose(p);
					nimln(1619, "system.nim");
					TMP611 = addInt(res_147556, ((NI) 1));
					res_147556 = (NI)(TMP611);
				} LA52: ;
			}
		}
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospexecProcess)(NimStringDesc* command, NimStringDesc** args, NI argsLen0, Stringtableobj137012* env, NU8 options) {
	NimStringDesc* result;
	Processobj146402* p;
	Streamobj141027* outp;
	NimStringDesc* line;
	nimfr("execProcess", "osproc.nim")
	result = 0;
	nimln(321, "osproc.nim");
	p = nospstartProcess(command, ((NimStringDesc*) &TMP571), args, argsLen0, env, options);
	nimln(322, "osproc.nim");
	outp = nospoutputStream(p);
	nimln(323, "osproc.nim");
	result = copyString(((NimStringDesc*) &TMP612));
	nimln(324, "osproc.nim");
	line = rawNewString(((NI) 120));
	{
		nimln(325, "osproc.nim");
		while (1) {
			nimln(327, "osproc.nim");
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = readline_141509(outp, (&line));
				if (!LOC5) goto LA6;
				nimln(328, "osproc.nim");
				result = resizeString(result, line->Sup.len + 0);
appendString(result, line);
				nimln(329, "osproc.nim");
				result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP613));
			}
			goto LA3;
			LA6: ;
			{
				NIM_BOOL LOC9;
				nimln(330, "osproc.nim");
				LOC9 = 0;
				LOC9 = nosprunning(p);
				if (!!(LOC9)) goto LA10;
				goto LA1;
			}
			goto LA3;
			LA10: ;
			LA3: ;
		}
	} LA1: ;
	nimln(331, "osproc.nim");
	nospclose(p);
	popFrame();
	return result;
}

N_NIMCALL(void, hsclose_147810)(Streamobj141027* s) {
	nimfr("hsClose", "osproc.nim")
	popFrame();
}

N_NIMCALL(NIM_BOOL, hsatend_147816)(Streamobj141027* s) {
	NIM_BOOL result;
	nimfr("hsAtEnd", "osproc.nim")
{	result = 0;
	nimln(343, "osproc.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI147807));
	result = (*((Tfilehandlestream147807*) (s))).attheend;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, hsreaddata_147823)(Streamobj141027* s_147825, void* buffer, NI buflen) {
	NI result;
	Tfilehandlestream147807* s;
	NI32 br;
	NI32 a;
	nimfr("hsReadData", "osproc.nim")
{	result = 0;
	nimln(346, "osproc.nim");
	if (s_147825) chckObj((*s_147825).Sup.m_type, (&NTI147807));
	s = ((Tfilehandlestream147807*) (s_147825));
	nimln(347, "osproc.nim");
	{
		if (!(*s).attheend) goto LA3;
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA3: ;
	br = 0;
	nimln(349, "osproc.nim");
	a = Dl_105430((*s).handle, buffer, ((int) (buflen)), (&br), NIM_NIL);
	nimln(353, "osproc.nim");
	{
		NIM_BOOL LOC7;
		NI32 LOC11;
		LOC7 = 0;
		LOC7 = (a == ((NI32) 0));
		if (!(LOC7)) goto LA8;
		LOC7 = !((br == ((NI32) 0)));
		LA8: ;
		if (!LOC7) goto LA9;
		LOC11 = 0;
		LOC11 = oslasterror_115454();
		raiseoserror_115430(LOC11);
	}
	LA9: ;
	nimln(354, "osproc.nim");
	(*s).attheend = (((NI) (br)) < buflen);
	nimln(355, "osproc.nim");
	result = ((NI) (br));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, hswritedata_147838)(Streamobj141027* s_147840, void* buffer, NI buflen) {
	Tfilehandlestream147807* s;
	NI32 byteswritten;
	NI32 a;
	nimfr("hsWriteData", "osproc.nim")
	nimln(358, "osproc.nim");
	if (s_147840) chckObj((*s_147840).Sup.m_type, (&NTI147807));
	s = ((Tfilehandlestream147807*) (s_147840));
	byteswritten = 0;
	nimln(360, "osproc.nim");
	a = Dl_105441((*s).handle, buffer, ((int) (buflen)), (&byteswritten), NIM_NIL);
	nimln(362, "osproc.nim");
	{
		NI32 LOC5;
		if (!(a == ((NI32) 0))) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_115454();
		raiseoserror_115430(LOC5);
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP619)(void* p, NI op) {
	Tfilehandlestream147807* a;
	a = (Tfilehandlestream147807*)p;
}

N_NIMCALL(Tfilehandlestream147807*, newfilehandlestream_147852)(NI handle) {
	Tfilehandlestream147807* result;
	nimfr("newFileHandleStream", "osproc.nim")
	result = 0;
	nimln(365, "osproc.nim");
	result = (Tfilehandlestream147807*) newObj((&NTI147805), sizeof(Tfilehandlestream147807));
	(*result).Sup.Sup.m_type = (&NTI147807);
	nimln(366, "osproc.nim");
	(*result).handle = handle;
	nimln(367, "osproc.nim");
	(*result).Sup.closeimpl = hsclose_147810;
	nimln(368, "osproc.nim");
	(*result).Sup.atendimpl = hsatend_147816;
	nimln(369, "osproc.nim");
	(*result).Sup.readdataimpl = hsreaddata_147823;
	nimln(370, "osproc.nim");
	(*result).Sup.writedataimpl = hswritedata_147838;
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING, buildcommandline_147867)(NimStringDesc* a, NimStringDesc** args, NI argsLen0) {
	NCSTRING result;
	NimStringDesc* res;
	NI TMP621;
	void* LOC5;
	nimfr("buildCommandLine", "osproc.nim")
	result = 0;
	nimln(373, "osproc.nim");
	res = nospquoteShell(a);
	{
		NI i_147884;
		NI HEX3Atmp_147886;
		NI res_147889;
		i_147884 = 0;
		HEX3Atmp_147886 = 0;
		nimln(374, "osproc.nim");
		HEX3Atmp_147886 = (argsLen0-1);
		nimln(1598, "system.nim");
		res_147889 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NI TMP620;
				if (!(res_147889 <= HEX3Atmp_147886)) goto LA3;
				nimln(1600, "system.nim");
				i_147884 = res_147889;
				nimln(375, "osproc.nim");
				res = addChar(res, 32);
				nimln(376, "osproc.nim");
				if ((NU)(i_147884) >= (NU)(argsLen0)) raiseIndexError();
				LOC4 = 0;
				LOC4 = nospquoteShell(args[i_147884]);
				res = resizeString(res, LOC4->Sup.len + 0);
appendString(res, LOC4);
				nimln(1619, "system.nim");
				TMP620 = addInt(res_147889, ((NI) 1));
				res_147889 = (NI)(TMP620);
			} LA3: ;
		}
	}
	nimln(377, "osproc.nim");
	TMP621 = addInt((res ? res->Sup.len : 0), ((NI) 1));
	LOC5 = 0;
	LOC5 = alloc0_6017(((NI)chckRange((NI)(TMP621), ((NI) 0), ((NI) 2147483647))));
	result = ((NCSTRING) (LOC5));
	nimln(378, "osproc.nim");
	memcpy(((void*) (result)), ((void*) (res->data)), ((NI)chckRange((res ? res->Sup.len : 0), ((NI) 0), ((NI) 2147483647))));
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING, buildenv_147906)(Stringtableobj137012* env) {
	NCSTRING result;
	NI L;
	NI TMP626;
	void* LOC9;
	nimfr("buildEnv", "osproc.nim")
	result = 0;
	nimln(381, "osproc.nim");
	L = ((NI) 0);
	{
		NimStringDesc* key_147911;
		NimStringDesc* val_147912;
		key_147911 = 0;
		val_147912 = 0;
		{
			NI h_147939;
			NI HEX3Atmp_147941;
			NI res_147943;
			h_147939 = 0;
			HEX3Atmp_147941 = 0;
			nimln(43, "strtabs.nim");
			HEX3Atmp_147941 = ((*env).data ? ((*env).data->Sup.len-1) : -1);
			nimln(1598, "system.nim");
			res_147943 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP625;
					if (!(res_147943 <= HEX3Atmp_147941)) goto LA4;
					nimln(1600, "system.nim");
					h_147939 = res_147943;
					nimln(44, "strtabs.nim");
					{
						NI TMP622;
						NI TMP623;
						NI TMP624;
						if ((NU)(h_147939) >= (NU)((*env).data->Sup.len)) raiseIndexError();
						if (!!((*env).data->data[h_147939].Field0 == 0)) goto LA7;
						nimln(45, "strtabs.nim");
						if ((NU)(h_147939) >= (NU)((*env).data->Sup.len)) raiseIndexError();
						key_147911 = (*env).data->data[h_147939].Field0;
						if ((NU)(h_147939) >= (NU)((*env).data->Sup.len)) raiseIndexError();
						val_147912 = (*env).data->data[h_147939].Field1;
						nimln(382, "osproc.nim");
						TMP622 = addInt((key_147911 ? key_147911->Sup.len : 0), (val_147912 ? val_147912->Sup.len : 0));
						TMP623 = addInt((NI)(TMP622), ((NI) 2));
						TMP624 = addInt(L, (NI)(TMP623));
						L = (NI)(TMP624);
					}
					LA7: ;
					nimln(1619, "system.nim");
					TMP625 = addInt(res_147943, ((NI) 1));
					res_147943 = (NI)(TMP625);
				} LA4: ;
			}
		}
	}
	nimln(383, "osproc.nim");
	TMP626 = addInt(L, ((NI) 2));
	LOC9 = 0;
	LOC9 = alloc0_6017(((NI)chckRange((NI)(TMP626), ((NI) 0), ((NI) 2147483647))));
	result = ((NCSTRING) (LOC9));
	nimln(384, "osproc.nim");
	L = ((NI) 0);
	{
		NimStringDesc* key_147922;
		NimStringDesc* val_147923;
		key_147922 = 0;
		val_147923 = 0;
		{
			NI h_147951;
			NI HEX3Atmp_147953;
			NI res_147955;
			h_147951 = 0;
			HEX3Atmp_147953 = 0;
			nimln(43, "strtabs.nim");
			HEX3Atmp_147953 = ((*env).data ? ((*env).data->Sup.len-1) : -1);
			nimln(1598, "system.nim");
			res_147955 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					NI TMP631;
					if (!(res_147955 <= HEX3Atmp_147953)) goto LA13;
					nimln(1600, "system.nim");
					h_147951 = res_147955;
					nimln(44, "strtabs.nim");
					{
						NimStringDesc* x;
						NimStringDesc* LOC18;
						NI TMP628;
						NI TMP629;
						NI TMP630;
						if ((NU)(h_147951) >= (NU)((*env).data->Sup.len)) raiseIndexError();
						if (!!((*env).data->data[h_147951].Field0 == 0)) goto LA16;
						nimln(45, "strtabs.nim");
						if ((NU)(h_147951) >= (NU)((*env).data->Sup.len)) raiseIndexError();
						key_147922 = (*env).data->data[h_147951].Field0;
						if ((NU)(h_147951) >= (NU)((*env).data->Sup.len)) raiseIndexError();
						val_147923 = (*env).data->data[h_147951].Field1;
						nimln(386, "osproc.nim");
						LOC18 = 0;
						LOC18 = rawNewString(key_147922->Sup.len + val_147923->Sup.len + 1);
appendString(LOC18, key_147922);
appendString(LOC18, ((NimStringDesc*) &TMP627));
appendString(LOC18, val_147923);
						x = LOC18;
						nimln(387, "osproc.nim");
						TMP628 = addInt((x ? x->Sup.len : 0), ((NI) 1));
						memcpy(((void*) ((&result[L]))), ((void*) (x->data)), ((NI)chckRange((NI)(TMP628), ((NI) 0), ((NI) 2147483647))));
						nimln(388, "osproc.nim");
						TMP629 = addInt((x ? x->Sup.len : 0), ((NI) 1));
						TMP630 = addInt(L, (NI)(TMP629));
						L = (NI)(TMP630);
					}
					LA16: ;
					nimln(1619, "system.nim");
					TMP631 = addInt(res_147955, ((NI) 1));
					res_147955 = (NI)(TMP631);
				} LA13: ;
			}
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(void, createpipehandles_147985)(NI* rdhandle, NI* wrhandle) {
	Tsecurityattributes105242 piinheritablepipe;
	nimfr("createPipeHandles", "osproc.nim")
	memset((void*)(&piinheritablepipe), 0, sizeof(piinheritablepipe));
	nimln(399, "osproc.nim");
	piinheritablepipe.nlength = ((int) (((NI)sizeof(Tsecurityattributes105242))));
	nimln(400, "osproc.nim");
	piinheritablepipe.lpsecuritydescriptor = NIM_NIL;
	nimln(401, "osproc.nim");
	piinheritablepipe.binherithandle = ((NI32) 1);
	nimln(402, "osproc.nim");
	{
		NI32 LOC3;
		NI32 LOC6;
		LOC3 = 0;
		LOC3 = Dl_105452(rdhandle, wrhandle, (&piinheritablepipe), ((NI32) 1024));
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		nimln(403, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_115454();
		raiseoserror_115430(LOC6);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, fileclose_148001)(NI h) {
	nimfr("fileClose", "osproc.nim")
	nimln(406, "osproc.nim");
	{
		NI32 LOC5;
		if (!(((NI) 4) < h)) goto LA3;
		LOC5 = 0;
		LOC5 = Dl_105424(h);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Processobj146402*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj137012* env, NU8 options) {
	Processobj146402* result;
	Tstartupinfo105244 si;
	Tprocessinformation105246 procinfo;
	NI success;
	NI hi;
	NI ho;
	NI he;
	NCSTRING cmdl;
	NCSTRING wd;
	NCSTRING e;
	NI16* tmp;
	NI16* ee;
	NI16* wwd;
	NI32 LOC33;
	NI32 lasterror;
	NI32 LOC50;
	nimfr("startProcess", "osproc.nim")
	result = 0;
	memset((void*)(&si), 0, sizeof(si));
	memset((void*)(&procinfo), 0, sizeof(procinfo));
	success = 0;
	hi = 0;
	ho = 0;
	he = 0;
	nimln(418, "osproc.nim");
	result = (Processobj146402*) newObj((&NTI146404), sizeof(Processobj146402));
	(*result).Sup.m_type = (&NTI146402);
	nimln(419, "osproc.nim");
	si.cb = ((int) (((NI)sizeof(Tstartupinfo105244))));
	nimln(420, "osproc.nim");
	{
		if (!!(((options &(1<<((((NU8) 4))&7)))!=0))) goto LA3;
		nimln(421, "osproc.nim");
		si.dwflags = ((NI32) 256);
		nimln(422, "osproc.nim");
		createpipehandles_147985((&si.hstdinput), (&hi));
		nimln(423, "osproc.nim");
		createpipehandles_147985((&ho), (&si.hstdoutput));
		nimln(424, "osproc.nim");
		{
			if (!((options &(1<<((((NU8) 3))&7)))!=0)) goto LA7;
			nimln(425, "osproc.nim");
			si.hstderror = si.hstdoutput;
			nimln(426, "osproc.nim");
			he = ho;
		}
		goto LA5;
		LA7: ;
		{
			nimln(428, "osproc.nim");
			createpipehandles_147985((&he), (&si.hstderror));
		}
		LA5: ;
		nimln(429, "osproc.nim");
		(*result).inhandle = ((int) (hi));
		nimln(430, "osproc.nim");
		(*result).outhandle = ((int) (ho));
		nimln(431, "osproc.nim");
		(*result).errhandle = ((int) (he));
	}
	goto LA1;
	LA3: ;
	{
		nimln(433, "osproc.nim");
		si.hstderror = Dl_105638(((NI32) -12));
		nimln(434, "osproc.nim");
		si.hstdinput = Dl_105638(((NI32) -10));
		nimln(435, "osproc.nim");
		si.hstdoutput = Dl_105638(((NI32) -11));
		nimln(436, "osproc.nim");
		(*result).inhandle = ((int) (si.hstdinput));
		nimln(437, "osproc.nim");
		(*result).outhandle = ((int) (si.hstdoutput));
		nimln(438, "osproc.nim");
		(*result).errhandle = ((int) (si.hstderror));
	}
	LA1: ;
	cmdl = 0;
	nimln(441, "osproc.nim");
	{
		if (!((options &(1<<((((NU8) 2))&7)))!=0)) goto LA13;
		nimln(442, "osproc.nim");
		cmdl = command->data;
		nimln(443, "osproc.nim");
		{
			if (!!((argsLen0 == ((NI) 0)))) goto LA17;
			failedassertimpl_88817(((NimStringDesc*) &TMP632));
		}
		LA17: ;
	}
	goto LA11;
	LA13: ;
	{
		nimln(445, "osproc.nim");
		cmdl = buildcommandline_147867(command, args, argsLen0);
	}
	LA11: ;
	nimln(446, "osproc.nim");
	wd = NIM_NIL;
	nimln(447, "osproc.nim");
	e = NIM_NIL;
	nimln(448, "osproc.nim");
	{
		if (!(((NI) 0) < (workingdir ? workingdir->Sup.len : 0))) goto LA22;
		wd = workingdir->data;
	}
	LA22: ;
	nimln(449, "osproc.nim");
	{
		if (!!((env == NIM_NIL))) goto LA26;
		e = buildenv_147906(env);
	}
	LA26: ;
	nimln(450, "osproc.nim");
	{
		NimStringDesc* LOC32;
		if (!((options &(1<<((((NU8) 0))&7)))!=0)) goto LA30;
		LOC32 = 0;
		LOC32 = cstrToNimstr(cmdl);
		printf("%s\015\012", LOC32? (LOC32)->data:"nil");
	}
	LA30: ;
	nimln(452, "osproc.nim");
	tmp = newwidecstring_81144(cmdl);
	nimln(453, "osproc.nim");
	ee = newwidecstring_81144(e);
	nimln(454, "osproc.nim");
	wwd = newwidecstring_81144(wd);
	nimln(455, "osproc.nim");
	LOC33 = 0;
	LOC33 = Dl_105463(NIM_NIL, tmp, NIM_NIL, NIM_NIL, ((NI32) 1), ((NI32) 1056), ee, wwd, (&si), (&procinfo));
	success = ((NI) (LOC33));
	nimln(461, "osproc.nim");
	lasterror = oslasterror_115454();
	nimln(463, "osproc.nim");
	{
		if (!!(((options &(1<<((((NU8) 4))&7)))!=0))) goto LA36;
		nimln(464, "osproc.nim");
		fileclose_148001(si.hstdinput);
		nimln(465, "osproc.nim");
		fileclose_148001(si.hstdoutput);
		nimln(466, "osproc.nim");
		{
			if (!!(((options &(1<<((((NU8) 3))&7)))!=0))) goto LA40;
			nimln(467, "osproc.nim");
			fileclose_148001(si.hstderror);
		}
		LA40: ;
	}
	LA36: ;
	nimln(469, "osproc.nim");
	{
		if (!!((e == NIM_NIL))) goto LA44;
		dealloc_6048(((void*) (e)));
	}
	LA44: ;
	nimln(470, "osproc.nim");
	{
		if (!(success == ((NI) 0))) goto LA48;
		raiseoserror_115430(lasterror);
	}
	LA48: ;
	nimln(472, "osproc.nim");
	LOC50 = 0;
	LOC50 = Dl_105424(procinfo.hthread);
	nimln(473, "osproc.nim");
	(*result).fprocesshandle = procinfo.hprocess;
	nimln(474, "osproc.nim");
	(*result).id = ((NI) (procinfo.dwprocessid));
	popFrame();
	return result;
}

N_NIMCALL(void, nospsuspend)(Processobj146402* p) {
	NI32 LOC1;
	nimfr("suspend", "osproc.nim")
	nimln(485, "osproc.nim");
	LOC1 = 0;
	LOC1 = Dl_105604((*p).fprocesshandle);
	popFrame();
}

N_NIMCALL(void, nospresume)(Processobj146402* p) {
	NI32 LOC1;
	nimfr("resume", "osproc.nim")
	nimln(488, "osproc.nim");
	LOC1 = 0;
	LOC1 = Dl_105610((*p).fprocesshandle);
	popFrame();
}

N_NIMCALL(NIM_BOOL, nosprunning)(Processobj146402* p) {
	NIM_BOOL result;
	NI32 x;
	nimfr("running", "osproc.nim")
{	result = 0;
	nimln(491, "osproc.nim");
	x = Dl_105616((*p).fprocesshandle, ((NI32) 50));
	nimln(492, "osproc.nim");
	result = (x == ((NI32) 258));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nospterminate)(Processobj146402* p) {
	nimfr("terminate", "osproc.nim")
	nimln(495, "osproc.nim");
	{
		NIM_BOOL LOC3;
		NI32 LOC6;
		LOC3 = 0;
		LOC3 = nosprunning(p);
		if (!LOC3) goto LA4;
		nimln(496, "osproc.nim");
		LOC6 = 0;
		LOC6 = Dl_105623((*p).fprocesshandle, ((NI) 0));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, nospkill)(Processobj146402* p) {
	nimfr("kill", "osproc.nim")
	nimln(499, "osproc.nim");
	nospterminate(p);
	popFrame();
}

N_NIMCALL(NI, nospwaitForExit)(Processobj146402* p, NI timeout) {
	NI result;
	NI32 LOC1;
	NI32 res;
	NI32 LOC2;
	NI32 LOC3;
	nimfr("waitForExit", "osproc.nim")
	result = 0;
	nimln(502, "osproc.nim");
	LOC1 = 0;
	LOC1 = Dl_105616((*p).fprocesshandle, ((NI32) (timeout)));
	res = 0;
	nimln(505, "osproc.nim");
	LOC2 = 0;
	LOC2 = Dl_105630((*p).fprocesshandle, (&res));
	nimln(506, "osproc.nim");
	result = ((NI) (res));
	nimln(507, "osproc.nim");
	LOC3 = 0;
	LOC3 = Dl_105424((*p).fprocesshandle);
	popFrame();
	return result;
}

N_NIMCALL(NI, peekexitcode_146725)(Processobj146402* p) {
	NI result;
	NIM_BOOL b;
	NI32 LOC1;
	nimfr("peekExitCode", "osproc.nim")
{	result = 0;
	nimln(510, "osproc.nim");
	LOC1 = 0;
	LOC1 = Dl_105616((*p).fprocesshandle, ((NI32) 50));
	b = (LOC1 == ((NI32) 258));
	nimln(511, "osproc.nim");
	{
		if (!b) goto LA4;
		result = ((NI) -1);
	}
	goto LA2;
	LA4: ;
	{
		NI32 res;
		NI32 LOC7;
		res = 0;
		nimln(514, "osproc.nim");
		LOC7 = 0;
		LOC7 = Dl_105630((*p).fprocesshandle, (&res));
		nimln(515, "osproc.nim");
		result = ((NI) (res));
		goto BeforeRet;
	}
	LA2: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj141027*, nospinputStream)(Processobj146402* p) {
	Streamobj141027* result;
	Tfilehandlestream147807* LOC1;
	nimfr("inputStream", "osproc.nim")
	result = 0;
	nimln(518, "osproc.nim");
	LOC1 = 0;
	LOC1 = newfilehandlestream_147852(((NI) ((*p).inhandle)));
	result = &LOC1->Sup;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj141027*, nospoutputStream)(Processobj146402* p) {
	Streamobj141027* result;
	Tfilehandlestream147807* LOC1;
	nimfr("outputStream", "osproc.nim")
	result = 0;
	nimln(521, "osproc.nim");
	LOC1 = 0;
	LOC1 = newfilehandlestream_147852(((NI) ((*p).outhandle)));
	result = &LOC1->Sup;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj141027*, nosperrorStream)(Processobj146402* p) {
	Streamobj141027* result;
	Tfilehandlestream147807* LOC1;
	nimfr("errorStream", "osproc.nim")
	result = 0;
	nimln(524, "osproc.nim");
	LOC1 = 0;
	LOC1 = newfilehandlestream_147852(((NI) ((*p).errhandle)));
	result = &LOC1->Sup;
	popFrame();
	return result;
}

N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command) {
	NI result;
	Tstartupinfo105244 si;
	Tprocessinformation105246 procinfo;
	NI process;
	NI32 L;
	NI16* c;
	NI32 res;
	nimfr("execCmd", "osproc.nim")
	result = 0;
	memset((void*)(&si), 0, sizeof(si));
	memset((void*)(&procinfo), 0, sizeof(procinfo));
	process = 0;
	L = 0;
	nimln(532, "osproc.nim");
	si.cb = ((int) (((NI)sizeof(Tstartupinfo105244))));
	nimln(533, "osproc.nim");
	si.hstderror = Dl_105638(((NI32) -12));
	nimln(534, "osproc.nim");
	si.hstdinput = Dl_105638(((NI32) -10));
	nimln(535, "osproc.nim");
	si.hstdoutput = Dl_105638(((NI32) -11));
	nimln(537, "osproc.nim");
	c = newwidecstring_81205(command);
	nimln(538, "osproc.nim");
	res = Dl_105463(NIM_NIL, c, NIM_NIL, NIM_NIL, ((NI32) 0), ((NI32) 32), NIM_NIL, NIM_NIL, (&si), (&procinfo));
	nimln(543, "osproc.nim");
	{
		NI32 LOC5;
		if (!(res == ((NI32) 0))) goto LA3;
		nimln(544, "osproc.nim");
		LOC5 = 0;
		LOC5 = oslasterror_115454();
		raiseoserror_115430(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		NI32 LOC7;
		NI32 LOC15;
		nimln(546, "osproc.nim");
		process = procinfo.hprocess;
		nimln(547, "osproc.nim");
		LOC7 = 0;
		LOC7 = Dl_105424(procinfo.hthread);
		nimln(548, "osproc.nim");
		{
			NI32 LOC10;
			NI32 LOC13;
			LOC10 = 0;
			LOC10 = Dl_105616(process, ((NI32) -1));
			if (!!((LOC10 == ((NI32) -1)))) goto LA11;
			nimln(549, "osproc.nim");
			LOC13 = 0;
			LOC13 = Dl_105630(process, (&L));
			nimln(550, "osproc.nim");
			result = ((NI) (L));
		}
		goto LA8;
		LA11: ;
		{
			nimln(552, "osproc.nim");
			result = ((NI) -1);
		}
		LA8: ;
		nimln(553, "osproc.nim");
		LOC15 = 0;
		LOC15 = Dl_105424(process);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, select_147608)(TY147201** readfds, NI timeout) {
	NI result;
	Twohandlearray107273 rfds;
	NI32 ret;
	nimfr("select", "osproc.nim")
{	result = 0;
	nimln(556, "osproc.nim");
	{
		if (!!((((*readfds) ? (*readfds)->Sup.len : 0) <= ((NI) 64)))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP633));
	}
	LA3: ;
	memset((void*)rfds, 0, sizeof(rfds));
	{
		NI i_149020;
		NI HEX3Atmp_149066;
		NI TMP634;
		NI res_149069;
		i_149020 = 0;
		HEX3Atmp_149066 = 0;
		nimln(558, "osproc.nim");
		TMP634 = subInt(((*readfds) ? (*readfds)->Sup.len : 0), ((NI) 1));
		HEX3Atmp_149066 = (NI)(TMP634);
		nimln(1598, "system.nim");
		res_149069 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP635;
				if (!(res_149069 <= HEX3Atmp_149066)) goto LA7;
				nimln(1600, "system.nim");
				i_149020 = res_149069;
				nimln(559, "osproc.nim");
				if ((NU)(i_149020) > (NU)(63)) raiseIndexError();
				if ((NU)(i_149020) >= (NU)((*readfds)->Sup.len)) raiseIndexError();
				rfds[(i_149020)- 0] = (*(*readfds)->data[i_149020]).fprocesshandle;
				nimln(1619, "system.nim");
				TMP635 = addInt(res_149069, ((NI) 1));
				res_149069 = (NI)(TMP635);
			} LA7: ;
		}
	}
	nimln(561, "osproc.nim");
	ret = Dl_107280(((NI32) (((*readfds) ? (*readfds)->Sup.len : 0))), rfds, ((NI32) 0), ((NI32) (timeout)));
	nimln(563, "osproc.nim");
	switch (ret) {
	case ((NI32) 258):
	{
		nimln(565, "osproc.nim");
		result = ((NI) 0);
		goto BeforeRet;
	}
	break;
	case ((NI32) -1):
	{
		NI32 LOC10;
		nimln(567, "osproc.nim");
		LOC10 = 0;
		LOC10 = oslasterror_115454();
		raiseoserror_115430(LOC10);
	}
	break;
	default:
	{
		NI32 i;
		NI32 TMP636;
		nimln(569, "osproc.nim");
		TMP636 = subInt(ret, ((NI32) 0));
		i = (NI32)(TMP636);
		nimln(570, "osproc.nim");
		del_149033(readfds, ((NI)chckRange(i, ((NI) 0), ((NI) 2147483647))));
		nimln(571, "osproc.nim");
		result = ((NI) 1);
		goto BeforeRet;
	}
	break;
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nospclose)(Processobj146402* p) {
	nimfr("close", "osproc.nim")
	popFrame();
}

N_NIMCALL(void, execcmdex_149204)(NimStringDesc* command, NU8 options, TY149210* Result) {
	Processobj146402* p;
	TY146637 LOC1;
	Streamobj141027* outp;
	NimStringDesc* line;
	nimfr("execCmdEx", "osproc.nim")
	nimln(959, "osproc.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	p = nospstartProcess(command, ((NimStringDesc*) &TMP571), LOC1, 0, NIM_NIL, (options | 4));
	nimln(960, "osproc.nim");
	outp = nospoutputStream(p);
	nimln(961, "osproc.nim");
	unsureAsgnRef((void**) (&(*Result).Field0), copyString(TMP637.Field0));
	(*Result).Field1 = TMP637.Field1;
	nimln(962, "osproc.nim");
	line = rawNewString(((NI) 120));
	{
		nimln(963, "osproc.nim");
		while (1) {
			nimln(964, "osproc.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				LOC6 = readline_141509(outp, (&line));
				if (!LOC6) goto LA7;
				nimln(965, "osproc.nim");
				(*Result).Field0 = resizeString((*Result).Field0, line->Sup.len + 0);
appendString((*Result).Field0, line);
				nimln(966, "osproc.nim");
				(*Result).Field0 = resizeString((*Result).Field0, 2);
appendString((*Result).Field0, ((NimStringDesc*) &TMP613));
			}
			goto LA4;
			LA7: ;
			{
				nimln(968, "osproc.nim");
				(*Result).Field1 = peekexitcode_146725(p);
				nimln(969, "osproc.nim");
				{
					if (!!(((*Result).Field1 == ((NI) -1)))) goto LA12;
					goto LA2;
				}
				LA12: ;
			}
			LA4: ;
		}
	} LA2: ;
	nimln(970, "osproc.nim");
	nospclose(p);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit)(void) {
	nimfr("osproc", "osproc.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit)(void) {
static TNimNode* TMP597[6];
static TNimNode* TMP616[2];
static TNimNode TMP547[10];
NTI146402.size = sizeof(Processobj146402);
NTI146402.kind = 17;
NTI146402.base = (&NTI3411);
NTI146402.flags = 1;
TMP597[0] = &TMP547[1];
TMP547[1].kind = 1;
TMP547[1].offset = offsetof(Processobj146402, fprocesshandle);
TMP547[1].typ = (&NTI105222);
TMP547[1].name = "fProcessHandle";
TMP597[1] = &TMP547[2];
TMP547[2].kind = 1;
TMP547[2].offset = offsetof(Processobj146402, inhandle);
TMP547[2].typ = (&NTI13008);
TMP547[2].name = "inHandle";
TMP597[2] = &TMP547[3];
TMP547[3].kind = 1;
TMP547[3].offset = offsetof(Processobj146402, outhandle);
TMP547[3].typ = (&NTI13008);
TMP547[3].name = "outHandle";
TMP597[3] = &TMP547[4];
TMP547[4].kind = 1;
TMP547[4].offset = offsetof(Processobj146402, errhandle);
TMP547[4].typ = (&NTI13008);
TMP547[4].name = "errHandle";
TMP597[4] = &TMP547[5];
TMP547[5].kind = 1;
TMP547[5].offset = offsetof(Processobj146402, id);
TMP547[5].typ = (&NTI105222);
TMP547[5].name = "id";
TMP597[5] = &TMP547[6];
TMP547[6].kind = 1;
TMP547[6].offset = offsetof(Processobj146402, exitcode);
TMP547[6].typ = (&NTI5811);
TMP547[6].name = "exitCode";
TMP547[0].len = 6; TMP547[0].kind = 2; TMP547[0].sons = &TMP597[0];
NTI146402.node = &TMP547[0];
NTI146404.size = sizeof(Processobj146402*);
NTI146404.kind = 22;
NTI146404.base = (&NTI146402);
NTI146404.marker = TMP598;
NTI147201.size = sizeof(TY147201*);
NTI147201.kind = 24;
NTI147201.base = (&NTI146404);
NTI147201.marker = TMP599;
NTI147807.size = sizeof(Tfilehandlestream147807);
NTI147807.kind = 17;
NTI147807.base = (&NTI141027);
NTI147807.flags = 1;
TMP616[0] = &TMP547[8];
TMP547[8].kind = 1;
TMP547[8].offset = offsetof(Tfilehandlestream147807, handle);
TMP547[8].typ = (&NTI105222);
TMP547[8].name = "handle";
TMP616[1] = &TMP547[9];
TMP547[9].kind = 1;
TMP547[9].offset = offsetof(Tfilehandlestream147807, attheend);
TMP547[9].typ = (&NTI138);
TMP547[9].name = "atTheEnd";
TMP547[7].len = 2; TMP547[7].kind = 2; TMP547[7].sons = &TMP616[0];
NTI147807.node = &TMP547[7];
NTI147805.size = sizeof(Tfilehandlestream147807*);
NTI147805.kind = 22;
NTI147805.base = (&NTI147807);
NTI147805.marker = TMP619;
}

