/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdlib.h>

#include <time.h>
typedef struct TY13606 TY13606;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Oserror3433 Oserror3433;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TY108548 TY108548;
typedef struct TY119789 TY119789;
typedef struct Twin32finddata106219 Twin32finddata106219;
typedef struct Slice88061 Slice88061;
typedef struct Tfiletime105248 Tfiletime105248;
typedef struct Tbyhandlefileinformation105250 Tbyhandlefileinformation105250;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef N_STDCALL_PTR(NI16*, TY106435) (void);
typedef N_STDCALL_PTR(NI32, TY106437) (NI16* para1);
typedef N_STDCALL_PTR(void, TY106632) (NI32 dwmilliseconds);
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Oserror3433  {
  Systemerror3429 Sup;
NI32 errorcode;
};
typedef N_STDCALL_PTR(NI32, TY105663) (NI32 dwflags, void* lpsource, NI32 dwmessageid, NI32 dwlanguageid, void* lpbuffer, NI32 nsize, void* Arguments);
typedef N_STDCALL_PTR(void, TY105805) (void* p);
typedef N_STDCALL_PTR(NI32, TY105658) (void);
struct TY108548 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct TY119789 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef N_STDCALL_PTR(NI32, TY105829) (NI handle, NI16* buf, NI32 size);
typedef N_STDCALL_PTR(NI32, TY106411) (NI16* lpfilename, NI32 nbufferlength, NI16* lpbuffer, NI16** lpfilepart);
typedef N_STDCALL_PTR(NI, TY106240) (NI16* lpfilename, Twin32finddata106219* lpfindfiledata);
typedef N_STDCALL_PTR(NI32, TY105818) (NI16* pathname, void* security);
typedef N_STDCALL_PTR(NI32, TY106418) (NI16* lpfilename);
struct  Slice88061  {
NI a;
NI b;
};
typedef N_STDCALL_PTR(NI16*, TY106440) (void);
typedef N_STDCALL_PTR(NI32, TY105825) (NI16* lpname, NI16* lpvalue);
typedef N_STDCALL_PTR(NI32, TY105811) (NI32 nbufferlength, NI16* lpbuffer);
struct  Tfiletime105248  {
NI32 dwlowdatetime;
NI32 dwhighdatetime;
};
typedef NI16 TY106228[260];
typedef NI16 TY106232[14];
struct  Twin32finddata106219  {
NI32 dwfileattributes;
Tfiletime105248 ftcreationtime;
Tfiletime105248 ftlastaccesstime;
Tfiletime105248 ftlastwritetime;
NI32 nfilesizehigh;
NI32 nfilesizelow;
NI32 dwreserved0;
NI32 dwreserved1;
TY106228 cfilename;
TY106232 calternatefilename;
};
typedef N_STDCALL_PTR(void, TY106405) (NI hfindfile);
typedef N_STDCALL_PTR(NI, TY107318) (NI16* lpfilename, NI32 dwdesiredaccess, NI32 dwsharemode, void* lpsecurityattributes, NI32 dwcreationdisposition, NI32 dwflagsandattributes, NI htemplatefile);
struct  Tbyhandlefileinformation105250  {
NI32 dwfileattributes;
Tfiletime105248 ftcreationtime;
Tfiletime105248 ftlastaccesstime;
Tfiletime105248 ftlastwritetime;
NI32 dwvolumeserialnumber;
NI32 nfilesizehigh;
NI32 nfilesizelow;
NI32 nnumberoflinks;
NI32 nfileindexhigh;
NI32 nfileindexlow;
};
typedef N_STDCALL_PTR(NI32, TY106805) (NI hfile, Tbyhandlefileinformation105250* lpfileinformation);
typedef N_STDCALL_PTR(NI32, TY105425) (NI hobject);
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_125662)(TY13606** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, cmp_4717)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, findenvvar_124804)(NimStringDesc* key);
N_NIMCALL(void, getenvvarsc_124405)(void);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, HEX24_81389)(NI16* s);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, oserrormsg_115020)(NI32 errorcode);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, searchextpos_119736)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, normext_119726)(NimStringDesc* ext);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY119789* Result);
N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_NOCONV(void*, alloc_6001)(NI size);
N_NIMCALL(NimStringDesc*, HEX24_81212)(NI16* w, NI estimate);
N_NIMCALL(NI16*, newwidecstring_81021)(NCSTRING source, NI L);
N_NIMCALL(NI16*, newwidecstring_81205)(NimStringDesc* s);
N_NIMCALL(void, raiseoserror_115430)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_115454)(void);
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NI, parentdirpos_119559)(NimStringDesc* path);
N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY108548* Result);
N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_NIMCALL(void, rawcreatedir_126041)(NimStringDesc* dir);
N_NIMCALL(NimStringDesc*, HEX2F_119492)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, nosgetHomeDir)(void);
N_NIMCALL(NimStringDesc*, getenv_124843)(NimStringDesc* key);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x);
static N_INLINE(Slice88061, HEX2EHEX2E_110273)(NI a, NI b);
N_NIMCALL(TY13606*, nosparseCmdLine)(NimStringDesc* c);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(time_t, nosgetLastModificationTime)(NimStringDesc* file);
N_NIMCALL(NI, findfirstfile_116416)(NimStringDesc* a, Twin32finddata106219* b);
N_NIMCALL(time_t, wintimetounixtime_109688)(NI64 t);
N_NIMCALL(NI64, rdfiletime_106604)(Tfiletime105248 f);
N_NIMCALL(NI, openhandle_120429)(NimStringDesc* path, NIM_BOOL followsymlink);
N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
STRING_LITERAL(TMP519, "", 0);
STRING_LITERAL(TMP618, "unknown OS error", 16);
STRING_LITERAL(TMP1489, "USERPROFILE", 11);
STRING_LITERAL(TMP1490, "\\", 1);
STRING_LITERAL(TMP1957, ":\\", 2);
STRING_LITERAL(TMP1958, ".", 1);
STRING_LITERAL(TMP1961, "..\\", 3);
STRING_LITERAL(TMP2486, "APPDATA", 7);
STRING_LITERAL(TMP10770, "exe", 3);
STRING_LITERAL(TMP10771, "PATH", 4);
STRING_LITERAL(TMP10772, "not (\'\\0\' == sep) ", 18);
NIM_BOOL envcomputed_124007;
TY13606* environment_124009;
extern TFrame* frameptr_17042;
TY13606* ownargv_128609;
extern TNimType NTI13606; /* seq[string] */
extern Tgcheap48616 gch_48644;
extern TY106435 Dl_106434;
extern TY106437 Dl_106436;
extern TY106632 Dl_106631;
extern TNimType NTI115433; /* ref OSError */
extern TNimType NTI3433; /* OSError */
extern TY105663 Dl_105662;
extern TY105805 Dl_105804;
extern TY105658 Dl_105657;
extern TY105829 Dl_105828;
extern TY106411 Dl_106410;
extern TY106240 Dl_106239;
extern TY105818 Dl_105817;
extern TY106418 Dl_106417;
extern TY106440 Dl_106439;
extern TY105825 Dl_105824;
extern TY105811 Dl_105810;
extern TY106405 Dl_106404;
extern TY107318 Dl_107317;
extern TY106805 Dl_106804;
extern TY105425 Dl_105424;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(NimStringDesc*, pop_125662)(TY13606** s) {
	NimStringDesc* result;
	NI L;
	NI TMP467;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1926, "system.nim");
	TMP467 = subInt(((*s) ? (*s)->Sup.len : 0), ((NI) 1));
	L = (NI)(TMP467);
	nimln(1927, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln(1928, "system.nim");
	(*s) = (TY13606*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) 2147483647))));
	popFrame();
	return result;
}

N_NIMCALL(NI, noscmpPaths)(NimStringDesc* patha, NimStringDesc* pathb) {
	NI result;
	nimfr("cmpPaths", "os.nim")
	result = 0;
	nimln(776, "os.nim");
	{
		if (!NIM_FALSE) goto LA3;
		nimln(777, "os.nim");
		result = cmp_4717(patha, pathb);
	}
	goto LA1;
	LA3: ;
	{
		nimln(779, "os.nim");
		result = nsuCmpIgnoreCase(patha, pathb);
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getenvvarsc_124405)(void) {
	nimfr("getEnvVarsC", "os.nim")
{	nimln(1096, "os.nim");
	{
		NI16* env;
		NI16* e;
		NI32 LOC17;
		if (!!(envcomputed_124007)) goto LA3;
		nimln(1097, "os.nim");
		if (environment_124009) nimGCunrefNoCycle(environment_124009);
		environment_124009 = (TY13606*) newSeqRC1((&NTI13606), 0);
		nimln(1100, "os.nim");
		env = Dl_106434();
		nimln(1101, "os.nim");
		e = env;
		nimln(1102, "os.nim");
		{
			if (!(e == NIM_NIL)) goto LA7;
			goto BeforeRet;
		}
		LA7: ;
		{
			nimln(1103, "os.nim");
			while (1) {
				NI16* eend;
				NimStringDesc* LOC11;
				NimStringDesc* LOC12;
				NI TMP513;
				nimln(1104, "os.nim");
				eend = wcschr(e, ((NI32) 0));
				nimln(1105, "os.nim");
				LOC11 = 0;
				LOC11 = HEX24_81389(e);
				environment_124009 = (TY13606*) incrSeq(&(environment_124009)->Sup, sizeof(NimStringDesc*));
				LOC12 = 0;
				LOC12 = environment_124009->data[environment_124009->Sup.len-1]; environment_124009->data[environment_124009->Sup.len-1] = copyStringRC1(LOC11);
				if (LOC12) nimGCunrefNoCycle(LOC12);
				nimln(1106, "os.nim");
				TMP513 = addInt(((NI) (eend)), ((NI) 2));
				e = ((NI16*) ((NI)(TMP513)));
				nimln(1107, "os.nim");
				{
					if (!(((NI) (eend[(((NI) 1))- 0])) == ((NI) 0))) goto LA15;
					goto LA9;
				}
				LA15: ;
			}
		} LA9: ;
		nimln(1108, "os.nim");
		LOC17 = 0;
		LOC17 = Dl_106436(env);
		nimln(1120, "os.nim");
		envcomputed_124007 = NIM_TRUE;
	}
	LA3: ;
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NI, findenvvar_124804)(NimStringDesc* key) {
	NI result;
	NimStringDesc* temp;
	NimStringDesc* LOC1;
	nimfr("findEnvVar", "os.nim")
{	result = 0;
	nimln(1154, "os.nim");
	getenvvarsc_124405();
	nimln(1155, "os.nim");
	LOC1 = 0;
	LOC1 = rawNewString(key->Sup.len + 1);
appendString(LOC1, key);
appendChar(LOC1, 61);
	temp = LOC1;
	{
		NI i_124819;
		NI HEX3Atmp_124821;
		NI res_124824;
		i_124819 = 0;
		HEX3Atmp_124821 = 0;
		nimln(1156, "os.nim");
		HEX3Atmp_124821 = (environment_124009 ? (environment_124009->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_124824 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP515;
				if (!(res_124824 <= HEX3Atmp_124821)) goto LA4;
				nimln(1600, "system.nim");
				i_124819 = res_124824;
				nimln(1157, "os.nim");
				{
					NIM_BOOL LOC7;
					if ((NU)(i_124819) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = nsuStartsWith(environment_124009->data[i_124819], temp);
					if (!LOC7) goto LA8;
					result = i_124819;
					goto BeforeRet;
				}
				LA8: ;
				nimln(1619, "system.nim");
				TMP515 = addInt(res_124824, ((NI) 1));
				res_124824 = (NI)(TMP515);
			} LA4: ;
		}
	}
	nimln(1158, "os.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenv_124843)(NimStringDesc* key) {
	NimStringDesc* result;
	NI i;
	nimfr("getEnv", "os.nim")
{	result = 0;
	nimln(1166, "os.nim");
	i = findenvvar_124804(key);
	nimln(1167, "os.nim");
	{
		NI LOC5;
		NI TMP518;
		if (!(((NI) 0) <= i)) goto LA3;
		nimln(1168, "os.nim");
		if ((NU)(i) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
		if ((NU)(i) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = nsuFindChar(environment_124009->data[i], 61, ((NI) 0));
		TMP518 = addInt(LOC5, ((NI) 1));
		result = copyStr(environment_124009->data[i], (NI)(TMP518));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NCSTRING env;
		nimln(1170, "os.nim");
		env = getenv(key->data);
		nimln(1171, "os.nim");
		{
			if (!(env == NIM_NIL)) goto LA9;
			result = copyString(((NimStringDesc*) &TMP519));
			goto BeforeRet;
		}
		LA9: ;
		nimln(1172, "os.nim");
		result = cstrToNimstr(env);
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossleep)(NI milsecs) {
	nimfr("sleep", "os.nim")
	nimln(1843, "os.nim");
	Dl_106631(((NI32) (milsecs)));
	popFrame();
}

N_NIMCALL(NimStringDesc*, oserrormsg_115020)(NI32 errorcode) {
	NimStringDesc* result;
	nimfr("osErrorMsg", "os.nim")
	result = 0;
	nimln(245, "os.nim");
	result = copyString(((NimStringDesc*) &TMP519));
	nimln(247, "os.nim");
	{
		NI16* msgbuf;
		if (!!((errorcode == ((NI32) 0)))) goto LA3;
		msgbuf = 0;
		nimln(250, "os.nim");
		{
			NI32 LOC7;
			nimln(251, "os.nim");
			nimln(250, "os.nim");
			LOC7 = 0;
			LOC7 = Dl_105662(((NI32) 4864), NIM_NIL, errorcode, ((NI32) 0), ((void*) (&msgbuf)), ((NI32) 0), NIM_NIL);
			if (!!((LOC7 == ((NI32) 0)))) goto LA8;
			nimln(252, "os.nim");
			result = HEX24_81389(msgbuf);
			nimln(253, "os.nim");
			{
				if (!!((msgbuf == NIM_NIL))) goto LA12;
				Dl_105804(((void*) (msgbuf)));
			}
			LA12: ;
		}
		LA8: ;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, raiseoserror_115430)(NI32 errorcode) {
	Oserror3433* e;
	nimfr("raiseOSError", "os.nim")
	e = 0;
	nimln(272, "os.nim");
	e = (Oserror3433*) newObj((&NTI115433), sizeof(Oserror3433));
	(*e).Sup.Sup.Sup.m_type = (&NTI3433);
	nimln(273, "os.nim");
	(*e).errorcode = errorcode;
	nimln(274, "os.nim");
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), oserrormsg_115020(errorcode));
	nimln(275, "os.nim");
	{
		NimStringDesc* LOC5;
		if (!(((*e).Sup.Sup.message) && ((*e).Sup.Sup.message)->Sup.len == 0)) goto LA3;
		nimln(276, "os.nim");
		LOC5 = 0;
		LOC5 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP618));
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	LA3: ;
	nimln(277, "os.nim");
	raiseException((Exception*)e, "OSError");
	popFrame();
}

N_NIMCALL(NI32, oslasterror_115454)(void) {
	NI32 result;
	result = 0;
	result = Dl_105657();
	return result;
}

N_NIMCALL(NI, searchextpos_119736)(NimStringDesc* s) {
	NI result;
	nimfr("searchExtPos", "os.nim")
	result = 0;
	nimln(666, "os.nim");
	result = ((NI) -1);
	{
		NI i_119751;
		NI HEX3Atmp_119764;
		NI TMP651;
		NI res_119767;
		i_119751 = 0;
		HEX3Atmp_119764 = 0;
		nimln(667, "os.nim");
		TMP651 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_119764 = (NI)(TMP651);
		nimln(1586, "system.nim");
		res_119767 = HEX3Atmp_119764;
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP652;
				if (!(((NI) 1) <= res_119767)) goto LA3;
				nimln(1588, "system.nim");
				i_119751 = res_119767;
				nimln(668, "os.nim");
				{
					if ((NU)(i_119751) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NU8)(s->data[i_119751]) == (NU8)(46))) goto LA6;
					nimln(669, "os.nim");
					result = i_119751;
					nimln(670, "os.nim");
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					nimln(671, "os.nim");
					if ((NU)(i_119751) > (NU)(s->Sup.len)) raiseIndexError();
					if (!(((NU8)(s->data[i_119751])) == ((NU8)(92)) || ((NU8)(s->data[i_119751])) == ((NU8)(47)))) goto LA9;
					nimln(672, "os.nim");
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				nimln(1589, "system.nim");
				TMP652 = subInt(res_119767, ((NI) 1));
				res_119767 = (NI)(TMP652);
			} LA3: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, normext_119726)(NimStringDesc* ext) {
	NimStringDesc* result;
	nimfr("normExt", "os.nim")
	result = 0;
	nimln(661, "os.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((ext) && (ext)->Sup.len == 0);
		if (LOC3) goto LA4;
		if ((NU)(((NI) 0)) > (NU)(ext->Sup.len)) raiseIndexError();
		LOC3 = ((NU8)(ext->data[((NI) 0)]) == (NU8)(46));
		LA4: ;
		if (!LOC3) goto LA5;
		result = copyString(ext);
	}
	goto LA1;
	LA5: ;
	{
		NimStringDesc* LOC8;
		nimln(662, "os.nim");
		LOC8 = 0;
		LOC8 = rawNewString(ext->Sup.len + 1);
appendChar(LOC8, 46);
appendString(LOC8, ext);
		result = LOC8;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, noschangeFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extpos;
	nimfr("changeFileExt", "os.nim")
	result = 0;
	nimln(750, "os.nim");
	extpos = searchextpos_119736(filename);
	nimln(751, "os.nim");
	{
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		if (!(extpos < ((NI) 0))) goto LA3;
		LOC5 = 0;
		LOC6 = 0;
		LOC6 = normext_119726(ext);
		LOC5 = rawNewString(filename->Sup.len + LOC6->Sup.len + 0);
appendString(LOC5, filename);
appendString(LOC5, LOC6);
		result = LOC5;
	}
	goto LA1;
	LA3: ;
	{
		NimStringDesc* LOC8;
		NI TMP653;
		NimStringDesc* LOC9;
		NimStringDesc* LOC10;
		nimln(752, "os.nim");
		LOC8 = 0;
		TMP653 = subInt(extpos, ((NI) 1));
		LOC9 = 0;
		LOC9 = copyStrLast(filename, ((NI) 0), (NI)(TMP653));
		LOC10 = 0;
		LOC10 = normext_119726(ext);
		LOC8 = rawNewString(LOC9->Sup.len + LOC10->Sup.len + 0);
appendString(LOC8, LOC9);
appendString(LOC8, LOC10);
		result = LOC8;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nossplitPath)(NimStringDesc* path, TY108548* Result) {
	NI seppos;
	nimfr("splitPath", "os.nim")
	nimln(588, "os.nim");
	seppos = ((NI) -1);
	{
		NI i_119524;
		NI HEX3Atmp_119537;
		NI TMP654;
		NI res_119540;
		i_119524 = 0;
		HEX3Atmp_119537 = 0;
		nimln(589, "os.nim");
		TMP654 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		HEX3Atmp_119537 = (NI)(TMP654);
		nimln(1586, "system.nim");
		res_119540 = HEX3Atmp_119537;
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP655;
				if (!(((NI) 0) <= res_119540)) goto LA3;
				nimln(1588, "system.nim");
				i_119524 = res_119540;
				nimln(590, "os.nim");
				{
					if ((NU)(i_119524) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i_119524])) == ((NU8)(92)) || ((NU8)(path->data[i_119524])) == ((NU8)(47)))) goto LA6;
					nimln(591, "os.nim");
					seppos = i_119524;
					nimln(592, "os.nim");
					goto LA1;
				}
				LA6: ;
				nimln(1589, "system.nim");
				TMP655 = subInt(res_119540, ((NI) 1));
				res_119540 = (NI)(TMP655);
			} LA3: ;
		}
	} LA1: ;
	nimln(593, "os.nim");
	{
		NI TMP656;
		NI TMP657;
		if (!(((NI) 0) <= seppos)) goto LA10;
		nimln(594, "os.nim");
		TMP656 = subInt(seppos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TMP656)));
		nimln(595, "os.nim");
		TMP657 = addInt(seppos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStr(path, (NI)(TMP657)));
	}
	goto LA8;
	LA10: ;
	{
		nimln(597, "os.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(((NimStringDesc*) &TMP519)));
		nimln(598, "os.nim");
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(path));
	}
	LA8: ;
	popFrame();
}

N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY119789* Result) {
	nimfr("splitFile", "os.nim")
	nimln(691, "os.nim");
	{
		NIM_BOOL LOC3;
		NI TMP658;
		LOC3 = 0;
		LOC3 = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		TMP658 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP658)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC3 = (((NU8)(path->data[(NI)(TMP658)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TMP658)])) == ((NU8)(47)));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(692, "os.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), copyString(path));
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(((NimStringDesc*) &TMP519)));
		unsureAsgnRef((void**) (&(*Result).Field2), copyString(((NimStringDesc*) &TMP519)));
	}
	goto LA1;
	LA5: ;
	{
		NI seppos;
		NI dotpos;
		NI TMP662;
		NI TMP663;
		NI TMP664;
		nimln(694, "os.nim");
		seppos = ((NI) -1);
		nimln(695, "os.nim");
		dotpos = (path ? path->Sup.len : 0);
		{
			NI i_119819;
			NI HEX3Atmp_119843;
			NI TMP659;
			NI res_119846;
			i_119819 = 0;
			HEX3Atmp_119843 = 0;
			nimln(696, "os.nim");
			TMP659 = subInt((path ? path->Sup.len : 0), ((NI) 1));
			HEX3Atmp_119843 = (NI)(TMP659);
			nimln(1586, "system.nim");
			res_119846 = HEX3Atmp_119843;
			{
				nimln(1587, "system.nim");
				while (1) {
					NI TMP661;
					if (!(((NI) 0) <= res_119846)) goto LA10;
					nimln(1588, "system.nim");
					i_119819 = res_119846;
					nimln(697, "os.nim");
					{
						if ((NU)(i_119819) > (NU)(path->Sup.len)) raiseIndexError();
						if (!((NU8)(path->data[i_119819]) == (NU8)(46))) goto LA13;
						nimln(698, "os.nim");
						{
							NIM_BOOL LOC17;
							NIM_BOOL LOC18;
							NI TMP660;
							LOC17 = 0;
							LOC18 = 0;
							LOC18 = (dotpos == (path ? path->Sup.len : 0));
							if (!(LOC18)) goto LA19;
							LOC18 = (((NI) 0) < i_119819);
							LA19: ;
							LOC17 = LOC18;
							if (!(LOC17)) goto LA20;
							nimln(699, "os.nim");
							TMP660 = subInt(i_119819, ((NI) 1));
							if ((NU)((NI)(TMP660)) > (NU)(path->Sup.len)) raiseIndexError();
							LOC17 = !((((NU8)(path->data[(NI)(TMP660)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TMP660)])) == ((NU8)(47))));
							LA20: ;
							if (!LOC17) goto LA21;
							dotpos = i_119819;
						}
						LA21: ;
					}
					goto LA11;
					LA13: ;
					{
						nimln(700, "os.nim");
						if ((NU)(i_119819) > (NU)(path->Sup.len)) raiseIndexError();
						if (!(((NU8)(path->data[i_119819])) == ((NU8)(92)) || ((NU8)(path->data[i_119819])) == ((NU8)(47)))) goto LA24;
						nimln(701, "os.nim");
						seppos = i_119819;
						nimln(702, "os.nim");
						goto LA8;
					}
					goto LA11;
					LA24: ;
					LA11: ;
					nimln(1589, "system.nim");
					TMP661 = subInt(res_119846, ((NI) 1));
					res_119846 = (NI)(TMP661);
				} LA10: ;
			}
		} LA8: ;
		nimln(703, "os.nim");
		TMP662 = subInt(seppos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field0), copyStrLast(path, ((NI) 0), (NI)(TMP662)));
		nimln(704, "os.nim");
		TMP663 = addInt(seppos, ((NI) 1));
		TMP664 = subInt(dotpos, ((NI) 1));
		unsureAsgnRef((void**) (&(*Result).Field1), copyStrLast(path, (NI)(TMP663), (NI)(TMP664)));
		nimln(705, "os.nim");
		unsureAsgnRef((void**) (&(*Result).Field2), copyStr(path, dotpos));
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void) {
	NimStringDesc* result;
	NI16* buf;
	void* LOC1;
	NI32 len;
	nimfr("getAppFilename", "os.nim")
	result = 0;
	nimln(1794, "os.nim");
	LOC1 = 0;
	LOC1 = alloc_6001(((NI) 512));
	buf = ((NI16*) (LOC1));
	nimln(1795, "os.nim");
	len = Dl_105828(((NI) 0), buf, ((NI32) 256));
	nimln(1796, "os.nim");
	result = HEX24_81212(buf, ((NI) (len)));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosgetAppDir)(void) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	TY119789 LOC2;
	nimfr("getAppDir", "os.nim")
	result = 0;
	nimln(1838, "os.nim");
	LOC1 = 0;
	LOC1 = nosgetAppFilename();
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	nossplitFile(LOC1, (&LOC2));
	result = copyString(LOC2.Field0);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosexpandFilename)(NimStringDesc* filename) {
	NimStringDesc* result;
	NI16* unused;
	NI16* res;
	NI32 L;
	NI16* LOC1;
	nimfr("expandFilename", "os.nim")
	result = 0;
	unused = 0;
	nimln(723, "os.nim");
	res = newwidecstring_81021("", ((NI) 1536));
	nimln(724, "os.nim");
	LOC1 = 0;
	LOC1 = newwidecstring_81205(filename);
	L = Dl_106410(LOC1, ((NI32) 3072), res, &unused);
	nimln(725, "os.nim");
	{
		NIM_BOOL LOC4;
		NI32 LOC8;
		LOC4 = 0;
		LOC4 = (L <= ((NI32) 0));
		if (LOC4) goto LA5;
		LOC4 = (((NI32) 3072) <= L);
		LA5: ;
		if (!LOC4) goto LA6;
		nimln(726, "os.nim");
		LOC8 = 0;
		LOC8 = oslasterror_115454();
		raiseoserror_115430(LOC8);
	}
	LA6: ;
	nimln(727, "os.nim");
	result = HEX24_81212(res, ((NI) (L)));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr("joinPath", "os.nim")
	result = 0;
	nimln(541, "os.nim");
	{
		if (!((head ? head->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(542, "os.nim");
		result = copyString(tail);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP667;
		nimln(543, "os.nim");
		TMP667 = subInt((head ? head->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP667)) > (NU)(head->Sup.len)) raiseIndexError();
		if (!(((NU8)(head->data[(NI)(TMP667)])) == ((NU8)(92)) || ((NU8)(head->data[(NI)(TMP667)])) == ((NU8)(47)))) goto LA6;
		nimln(544, "os.nim");
		{
			NimStringDesc* LOC12;
			NimStringDesc* LOC13;
			if ((NU)(((NI) 0)) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[((NI) 0)])) == ((NU8)(92)) || ((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)))) goto LA10;
			nimln(545, "os.nim");
			LOC12 = 0;
			LOC13 = 0;
			LOC13 = copyStr(tail, ((NI) 1));
			LOC12 = rawNewString(head->Sup.len + LOC13->Sup.len + 0);
appendString(LOC12, head);
appendString(LOC12, LOC13);
			result = LOC12;
		}
		goto LA8;
		LA10: ;
		{
			NimStringDesc* LOC15;
			nimln(547, "os.nim");
			LOC15 = 0;
			LOC15 = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(LOC15, head);
appendString(LOC15, tail);
			result = LOC15;
		}
		LA8: ;
	}
	goto LA1;
	LA6: ;
	{
		nimln(549, "os.nim");
		{
			NimStringDesc* LOC21;
			if ((NU)(((NI) 0)) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[((NI) 0)])) == ((NU8)(92)) || ((NU8)(tail->data[((NI) 0)])) == ((NU8)(47)))) goto LA19;
			nimln(550, "os.nim");
			LOC21 = 0;
			LOC21 = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(LOC21, head);
appendString(LOC21, tail);
			result = LOC21;
		}
		goto LA17;
		LA19: ;
		{
			NimStringDesc* LOC23;
			nimln(552, "os.nim");
			LOC23 = 0;
			LOC23 = rawNewString(head->Sup.len + tail->Sup.len + 1);
appendString(LOC23, head);
appendChar(LOC23, 92);
appendString(LOC23, tail);
			result = LOC23;
		}
		LA17: ;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX2F_119492)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr("/", "os.nim")
{	result = 0;
	nimln(573, "os.nim");
	result = nosjoinPath(head, tail);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, parentdirpos_119559)(NimStringDesc* path) {
	NI result;
	NI q;
	nimfr("parentDirPos", "os.nim")
{	result = 0;
	nimln(601, "os.nim");
	q = ((NI) 1);
	nimln(602, "os.nim");
	{
		NIM_BOOL LOC3;
		NI TMP669;
		LOC3 = 0;
		LOC3 = (((NI) 1) <= (path ? path->Sup.len : 0));
		if (!(LOC3)) goto LA4;
		TMP669 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP669)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC3 = (((NU8)(path->data[(NI)(TMP669)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TMP669)])) == ((NU8)(47)));
		LA4: ;
		if (!LOC3) goto LA5;
		q = ((NI) 2);
	}
	LA5: ;
	{
		NI i_119586;
		NI HEX3Atmp_119599;
		NI TMP670;
		NI res_119602;
		i_119586 = 0;
		HEX3Atmp_119599 = 0;
		nimln(603, "os.nim");
		TMP670 = subInt((path ? path->Sup.len : 0), q);
		HEX3Atmp_119599 = (NI)(TMP670);
		nimln(1586, "system.nim");
		res_119602 = HEX3Atmp_119599;
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP671;
				if (!(((NI) 0) <= res_119602)) goto LA9;
				nimln(1588, "system.nim");
				i_119586 = res_119602;
				nimln(604, "os.nim");
				{
					if ((NU)(i_119586) > (NU)(path->Sup.len)) raiseIndexError();
					if (!(((NU8)(path->data[i_119586])) == ((NU8)(92)) || ((NU8)(path->data[i_119586])) == ((NU8)(47)))) goto LA12;
					result = i_119586;
					goto BeforeRet;
				}
				LA12: ;
				nimln(1589, "system.nim");
				TMP671 = subInt(res_119602, ((NI) 1));
				res_119602 = (NI)(TMP671);
			} LA9: ;
		}
	}
	nimln(605, "os.nim");
	result = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path) {
	NimStringDesc* result;
	NI seppos;
	nimfr("parentDir", "os.nim")
	result = 0;
	nimln(615, "os.nim");
	seppos = parentdirpos_119559(path);
	nimln(616, "os.nim");
	{
		NI TMP672;
		if (!(((NI) 0) <= seppos)) goto LA3;
		nimln(617, "os.nim");
		TMP672 = subInt(seppos, ((NI) 1));
		result = copyStrLast(path, ((NI) 0), (NI)(TMP672));
	}
	goto LA1;
	LA3: ;
	{
		nimln(619, "os.nim");
		result = copyString(((NimStringDesc*) &TMP519));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, findfirstfile_116416)(NimStringDesc* a, Twin32finddata106219* b) {
	NI result;
	NI16* LOC1;
	nimfr("findFirstFile", "os.nim")
	result = 0;
	nimln(363, "os.nim");
	LOC1 = 0;
	LOC1 = newwidecstring_81205(a);
	result = Dl_106239(LOC1, b);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosextractFilename)(NimStringDesc* path) {
	NimStringDesc* result;
	nimfr("extractFilename", "os.nim")
	result = 0;
	nimln(711, "os.nim");
	{
		NIM_BOOL LOC3;
		NI TMP675;
		LOC3 = 0;
		LOC3 = ((path ? path->Sup.len : 0) == ((NI) 0));
		if (LOC3) goto LA4;
		TMP675 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP675)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC3 = (((NU8)(path->data[(NI)(TMP675)])) == ((NU8)(92)) || ((NU8)(path->data[(NI)(TMP675)])) == ((NU8)(47)));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(712, "os.nim");
		result = copyString(((NimStringDesc*) &TMP519));
	}
	goto LA1;
	LA5: ;
	{
		TY108548 LOC8;
		nimln(714, "os.nim");
		memset((void*)(&LOC8), 0, sizeof(LOC8));
		nossplitPath(path, (&LOC8));
		result = copyString(LOC8.Field1);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosjoinPathOpenArray)(NimStringDesc** parts, NI partsLen0) {
	NimStringDesc* result;
	nimfr("joinPath", "os.nim")
	result = 0;
	nimln(559, "os.nim");
	if ((NU)(((NI) 0)) >= (NU)(partsLen0)) raiseIndexError();
	result = copyString(parts[((NI) 0)]);
	{
		NI i_119466;
		NI HEX3Atmp_119470;
		NI res_119473;
		i_119466 = 0;
		HEX3Atmp_119470 = 0;
		nimln(560, "os.nim");
		HEX3Atmp_119470 = (partsLen0-1);
		nimln(1598, "system.nim");
		res_119473 = ((NI) 1);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP678;
				if (!(res_119473 <= HEX3Atmp_119470)) goto LA3;
				nimln(1600, "system.nim");
				i_119466 = res_119473;
				nimln(561, "os.nim");
				if ((NU)(i_119466) >= (NU)(partsLen0)) raiseIndexError();
				result = nosjoinPath(result, parts[i_119466]);
				nimln(1619, "system.nim");
				TMP678 = addInt(res_119473, ((NI) 1));
				res_119473 = (NI)(TMP678);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path) {
	NIM_BOOL result;
	NI len;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC5;
	NIM_BOOL LOC6;
	nimfr("isAbsolute", "os.nim")
	result = 0;
	nimln(786, "os.nim");
	len = (path ? path->Sup.len : 0);
	nimln(787, "os.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = (((NI) 1) < len);
	if (!(LOC2)) goto LA3;
	if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
	LOC2 = (((NU8)(path->data[((NI) 0)])) == ((NU8)(47)) || ((NU8)(path->data[((NI) 0)])) == ((NU8)(92)));
	LA3: ;
	LOC1 = LOC2;
	if (LOC1) goto LA4;
	nimln(788, "os.nim");
	LOC5 = 0;
	LOC6 = 0;
	LOC6 = (((NI) 2) < len);
	if (!(LOC6)) goto LA7;
	if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
	LOC6 = (((NU8)(path->data[((NI) 0)])) >= ((NU8)(65)) && ((NU8)(path->data[((NI) 0)])) <= ((NU8)(90)) || ((NU8)(path->data[((NI) 0)])) >= ((NU8)(97)) && ((NU8)(path->data[((NI) 0)])) <= ((NU8)(122)));
	LA7: ;
	LOC5 = LOC6;
	if (!(LOC5)) goto LA8;
	if ((NU)(((NI) 1)) > (NU)(path->Sup.len)) raiseIndexError();
	LOC5 = ((NU8)(path->data[((NI) 1)]) == (NU8)(58));
	LA8: ;
	LOC1 = LOC5;
	LA4: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(void, rawcreatedir_126041)(NimStringDesc* dir) {
	NI32 res;
	NI16* LOC1;
	nimfr("rawCreateDir", "os.nim")
	nimln(358, "os.nim");
	LOC1 = 0;
	LOC1 = newwidecstring_81205(dir);
	res = Dl_105817(LOC1, NIM_NIL);
	nimln(1382, "os.nim");
	{
		NIM_BOOL LOC4;
		NI32 LOC6;
		NI32 LOC9;
		LOC4 = 0;
		LOC4 = (res == ((NI32) 0));
		if (!(LOC4)) goto LA5;
		LOC6 = 0;
		LOC6 = Dl_105657();
		LOC4 = !((LOC6 == ((NI32) 183)));
		LA5: ;
		if (!LOC4) goto LA7;
		nimln(1383, "os.nim");
		LOC9 = 0;
		LOC9 = oslasterror_115454();
		raiseoserror_115430(LOC9);
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(void, noscreateDir)(NimStringDesc* dir) {
	NIM_BOOL omitnext;
	nimfr("createDir", "os.nim")
	nimln(1392, "os.nim");
	omitnext = NIM_FALSE;
	nimln(1394, "os.nim");
	omitnext = nosisAbsolute(dir);
	{
		NI i_126611;
		NI HEX3Atmp_126624;
		NI TMP681;
		NI res_126627;
		i_126611 = 0;
		HEX3Atmp_126624 = 0;
		nimln(1395, "os.nim");
		TMP681 = subInt((dir ? dir->Sup.len : 0), ((NI) 1));
		HEX3Atmp_126624 = (NI)(TMP681);
		nimln(1598, "system.nim");
		res_126627 = ((NI) 1);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP683;
				if (!(res_126627 <= HEX3Atmp_126624)) goto LA3;
				nimln(1600, "system.nim");
				i_126611 = res_126627;
				nimln(1396, "os.nim");
				{
					if ((NU)(i_126611) > (NU)(dir->Sup.len)) raiseIndexError();
					if (!(((NU8)(dir->data[i_126611])) == ((NU8)(92)) || ((NU8)(dir->data[i_126611])) == ((NU8)(47)))) goto LA6;
					nimln(1397, "os.nim");
					{
						if (!omitnext) goto LA10;
						nimln(1398, "os.nim");
						omitnext = NIM_FALSE;
					}
					goto LA8;
					LA10: ;
					{
						NI TMP682;
						NimStringDesc* LOC13;
						nimln(1400, "os.nim");
						TMP682 = subInt(i_126611, ((NI) 1));
						LOC13 = 0;
						LOC13 = copyStrLast(dir, ((NI) 0), (NI)(TMP682));
						rawcreatedir_126041(LOC13);
					}
					LA8: ;
				}
				LA6: ;
				nimln(1619, "system.nim");
				TMP683 = addInt(res_126627, ((NI) 1));
				res_126627 = (NI)(TMP683);
			} LA3: ;
		}
	}
	nimln(1401, "os.nim");
	rawcreatedir_126041(dir);
	popFrame();
}

N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	NI32 a;
	NI16* LOC1;
	nimfr("existsFile", "os.nim")
	result = 0;
	nimln(358, "os.nim");
	LOC1 = 0;
	LOC1 = newwidecstring_81205(filename);
	a = Dl_106417(LOC1);
	nimln(390, "os.nim");
	{
		if (!!((a == ((NI32) -1)))) goto LA4;
		nimln(391, "os.nim");
		result = ((NI32)(a & ((NI32) 16)) == ((NI32) 0));
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext) {
	NimStringDesc* result;
	NI extpos;
	nimfr("addFileExt", "os.nim")
	result = 0;
	nimln(762, "os.nim");
	extpos = searchextpos_119736(filename);
	nimln(763, "os.nim");
	{
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		if (!(extpos < ((NI) 0))) goto LA3;
		LOC5 = 0;
		LOC6 = 0;
		LOC6 = normext_119726(ext);
		LOC5 = rawNewString(filename->Sup.len + LOC6->Sup.len + 0);
appendString(LOC5, filename);
appendString(LOC5, LOC6);
		result = LOC5;
	}
	goto LA1;
	LA3: ;
	{
		nimln(764, "os.nim");
		result = copyString(filename);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosgetHomeDir)(void) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("getHomeDir", "os.nim")
{	result = 0;
	nimln(1629, "os.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = getenv_124843(((NimStringDesc*) &TMP1489));
	LOC1 = rawNewString(LOC2->Sup.len + 1);
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP1490));
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x) {
	NimStringDesc* result;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2880, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice88061, HEX2EHEX2E_110273)(NI a, NI b) {
	Slice88061 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(234, "system.nim");
	result.a = a;
	nimln(235, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, expandtilde_130411)(NimStringDesc* path) {
	NimStringDesc* result;
	nimfr("expandTilde", "os.nim")
	result = 0;
	nimln(1899, "os.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC7;
		NimStringDesc* LOC11;
		NI TMP1491;
		Slice88061 LOC12;
		NimStringDesc* LOC13;
		LOC3 = 0;
		LOC4 = 0;
		LOC4 = (((NI) 1) < (path ? path->Sup.len : 0));
		if (!(LOC4)) goto LA5;
		if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC4 = ((NU8)(path->data[((NI) 0)]) == (NU8)(126));
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		LOC7 = 0;
		if ((NU)(((NI) 1)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC7 = ((NU8)(path->data[((NI) 1)]) == (NU8)(47));
		if (LOC7) goto LA8;
		if ((NU)(((NI) 1)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC7 = ((NU8)(path->data[((NI) 1)]) == (NU8)(92));
		LA8: ;
		LOC3 = LOC7;
		LA6: ;
		if (!LOC3) goto LA9;
		nimln(1900, "os.nim");
		LOC11 = 0;
		LOC11 = nosgetHomeDir();
		TMP1491 = subInt((path ? path->Sup.len : 0), ((NI) 1));
		LOC12 = HEX2EHEX2E_110273(((NI) 2), (NI)(TMP1491));
		LOC13 = 0;
		LOC13 = HEX5BHEX5D_88054(path, LOC12);
		result = HEX2F_119492(LOC11, LOC13);
	}
	goto LA1;
	LA9: ;
	{
		nimln(1902, "os.nim");
		result = copyString(path);
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (-2147483647 -1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI)(a % b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TY13606*, nosparseCmdLine)(NimStringDesc* c) {
	TY13606* result;
	NI i;
	NimStringDesc* a;
	nimfr("parseCmdLine", "os.nim")
	result = 0;
	nimln(1493, "os.nim");
	result = (TY13606*) newSeq((&NTI13606), 0);
	nimln(1494, "os.nim");
	i = ((NI) 0);
	nimln(1495, "os.nim");
	a = copyString(((NimStringDesc*) &TMP519));
	{
		nimln(1496, "os.nim");
		while (1) {
			NIM_BOOL inquote;
			NimStringDesc* LOC49;
			nimln(1497, "os.nim");
			a = setLengthStr(a, ((NI) 0));
			{
				nimln(1499, "os.nim");
				while (1) {
					NIM_BOOL LOC5;
					NIM_BOOL LOC6;
					NIM_BOOL LOC7;
					NI TMP1801;
					LOC5 = 0;
					LOC6 = 0;
					LOC7 = 0;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC7 = ((NU8)(c->data[i]) == (NU8)(32));
					if (LOC7) goto LA8;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC7 = ((NU8)(c->data[i]) == (NU8)(9));
					LA8: ;
					LOC6 = LOC7;
					if (LOC6) goto LA9;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC6 = ((NU8)(c->data[i]) == (NU8)(10));
					LA9: ;
					LOC5 = LOC6;
					if (LOC5) goto LA10;
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					LOC5 = ((NU8)(c->data[i]) == (NU8)(13));
					LA10: ;
					if (!LOC5) goto LA4;
					TMP1801 = addInt(i, ((NI) 1));
					i = (NI)(TMP1801);
				} LA4: ;
			}
			nimln(1502, "os.nim");
			{
				if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
				if (!((NU8)(c->data[i]) == (NU8)(0))) goto LA13;
				goto LA1;
			}
			LA13: ;
			nimln(1503, "os.nim");
			inquote = NIM_FALSE;
			{
				nimln(1504, "os.nim");
				while (1) {
					nimln(1505, "os.nim");
					if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
					switch (((NU8)(c->data[i]))) {
					case 0:
					{
						nimln(1506, "os.nim");
						goto LA15;
					}
					break;
					case 92:
					{
						NI j;
						nimln(1508, "os.nim");
						j = i;
						{
							nimln(1509, "os.nim");
							while (1) {
								NI TMP1802;
								if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();
								if (!((NU8)(c->data[j]) == (NU8)(92))) goto LA20;
								TMP1802 = addInt(j, ((NI) 1));
								j = (NI)(TMP1802);
							} LA20: ;
						}
						nimln(1510, "os.nim");
						{
							if ((NU)(j) > (NU)(c->Sup.len)) raiseIndexError();
							if (!((NU8)(c->data[j]) == (NU8)(34))) goto LA23;
							{
								NI k_127622;
								NI HEX3Atmp_127684;
								NI TMP1803;
								NI TMP1804;
								NI res_127687;
								k_127622 = 0;
								HEX3Atmp_127684 = 0;
								nimln(1511, "os.nim");
								TMP1803 = subInt(j, i);
								TMP1804 = divInt((NI)(TMP1803), ((NI) 2));
								HEX3Atmp_127684 = (NI)(TMP1804);
								nimln(1598, "system.nim");
								res_127687 = ((NI) 1);
								{
									nimln(1599, "system.nim");
									while (1) {
										NI TMP1805;
										if (!(res_127687 <= HEX3Atmp_127684)) goto LA27;
										nimln(1600, "system.nim");
										k_127622 = res_127687;
										nimln(1511, "os.nim");
										a = addChar(a, 92);
										nimln(1619, "system.nim");
										TMP1805 = addInt(res_127687, ((NI) 1));
										res_127687 = (NI)(TMP1805);
									} LA27: ;
								}
							}
							nimln(1512, "os.nim");
							{
								NI TMP1806;
								NI TMP1807;
								TMP1806 = subInt(j, i);
								TMP1807 = modInt((NI)(TMP1806), ((NI) 2));
								if (!(((NI) ((NI)(TMP1807))) == ((NI) 0))) goto LA30;
								nimln(1513, "os.nim");
								i = j;
							}
							goto LA28;
							LA30: ;
							{
								NI TMP1808;
								nimln(1515, "os.nim");
								a = addChar(a, 34);
								nimln(1516, "os.nim");
								TMP1808 = addInt(j, ((NI) 1));
								i = (NI)(TMP1808);
							}
							LA28: ;
						}
						goto LA21;
						LA23: ;
						{
							NI TMP1809;
							nimln(1518, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							a = addChar(a, c->data[i]);
							nimln(1519, "os.nim");
							TMP1809 = addInt(i, ((NI) 1));
							i = (NI)(TMP1809);
						}
						LA21: ;
					}
					break;
					case 34:
					{
						NI TMP1810;
						nimln(1521, "os.nim");
						TMP1810 = addInt(i, ((NI) 1));
						i = (NI)(TMP1810);
						nimln(1522, "os.nim");
						{
							if (!!(inquote)) goto LA37;
							inquote = NIM_TRUE;
						}
						goto LA35;
						LA37: ;
						{
							NI TMP1811;
							nimln(1523, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							if (!((NU8)(c->data[i]) == (NU8)(34))) goto LA40;
							nimln(1524, "os.nim");
							if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
							a = addChar(a, c->data[i]);
							nimln(1525, "os.nim");
							TMP1811 = addInt(i, ((NI) 1));
							i = (NI)(TMP1811);
						}
						goto LA35;
						LA40: ;
						{
							nimln(1527, "os.nim");
							inquote = NIM_FALSE;
							nimln(1528, "os.nim");
							goto LA15;
						}
						LA35: ;
					}
					break;
					case 32:
					case 9:
					{
						NI TMP1812;
						nimln(1530, "os.nim");
						{
							if (!!(inquote)) goto LA46;
							goto LA15;
						}
						LA46: ;
						nimln(1531, "os.nim");
						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
						a = addChar(a, c->data[i]);
						nimln(1532, "os.nim");
						TMP1812 = addInt(i, ((NI) 1));
						i = (NI)(TMP1812);
					}
					break;
					default:
					{
						NI TMP1813;
						nimln(1534, "os.nim");
						if ((NU)(i) > (NU)(c->Sup.len)) raiseIndexError();
						a = addChar(a, c->data[i]);
						nimln(1535, "os.nim");
						TMP1813 = addInt(i, ((NI) 1));
						i = (NI)(TMP1813);
					}
					break;
					}
				}
			} LA15: ;
			nimln(1550, "os.nim");
			result = (TY13606*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
			LOC49 = 0;
			LOC49 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(a);
			if (LOC49) nimGCunrefNoCycle(LOC49);
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nosparamCount)(void) {
	NI result;
	NI TMP1814;
	nimfr("paramCount", "os.nim")
	result = 0;
	nimln(1699, "os.nim");
	{
		NI16* LOC5;
		NimStringDesc* LOC6;
		if (!ownargv_128609 == 0) goto LA3;
		LOC5 = 0;
		LOC5 = Dl_106439();
		LOC6 = 0;
		LOC6 = HEX24_81389(LOC5);
		asgnRefNoCycle((void**) (&ownargv_128609), nosparseCmdLine(LOC6));
	}
	LA3: ;
	nimln(1700, "os.nim");
	TMP1814 = subInt((ownargv_128609 ? ownargv_128609->Sup.len : 0), ((NI) 1));
	result = (NI)(TMP1814);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosparamStr)(NI i) {
	NimStringDesc* result;
	nimfr("paramStr", "os.nim")
{	result = 0;
	nimln(1705, "os.nim");
	{
		NI16* LOC5;
		NimStringDesc* LOC6;
		if (!ownargv_128609 == 0) goto LA3;
		LOC5 = 0;
		LOC5 = Dl_106439();
		LOC6 = 0;
		LOC6 = HEX24_81389(LOC5);
		asgnRefNoCycle((void**) (&ownargv_128609), nosparseCmdLine(LOC6));
	}
	LA3: ;
	nimln(1706, "os.nim");
	if ((NU)(i) >= (NU)(ownargv_128609->Sup.len)) raiseIndexError();
	result = copyString(ownargv_128609->data[i]);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosunixToNativePath)(NimStringDesc* path, NimStringDesc* drive) {
	NimStringDesc* result;
	NI start;
	NI i;
	nimfr("unixToNativePath", "os.nim")
	result = 0;
	start = 0;
	nimln(316, "os.nim");
	{
		if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
		if (!((NU8)(path->data[((NI) 0)]) == (NU8)(47))) goto LA3;
		nimln(319, "os.nim");
		{
			NimStringDesc* LOC9;
			if (!!(((drive) && (drive)->Sup.len == 0))) goto LA7;
			nimln(320, "os.nim");
			LOC9 = 0;
			LOC9 = rawNewString(drive->Sup.len + 2);
appendString(LOC9, drive);
appendString(LOC9, ((NimStringDesc*) &TMP1957));
			result = LOC9;
		}
		goto LA5;
		LA7: ;
		{
			nimln(322, "os.nim");
			result = copyString(((NimStringDesc*) &TMP1490));
		}
		LA5: ;
		nimln(327, "os.nim");
		start = ((NI) 1);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC12;
		nimln(328, "os.nim");
		LOC12 = 0;
		if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC12 = ((NU8)(path->data[((NI) 0)]) == (NU8)(46));
		if (!(LOC12)) goto LA13;
		if ((NU)(((NI) 1)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC12 = ((NU8)(path->data[((NI) 1)]) == (NU8)(47));
		LA13: ;
		if (!LOC12) goto LA14;
		nimln(330, "os.nim");
		result = copyString(((NimStringDesc*) &TMP1958));
		nimln(331, "os.nim");
		start = ((NI) 2);
	}
	goto LA1;
	LA14: ;
	{
		nimln(333, "os.nim");
		result = copyString(((NimStringDesc*) &TMP519));
		nimln(334, "os.nim");
		start = ((NI) 0);
	}
	LA1: ;
	nimln(336, "os.nim");
	i = start;
	{
		nimln(337, "os.nim");
		while (1) {
			if (!(i < (path ? path->Sup.len : 0))) goto LA18;
			nimln(338, "os.nim");
			{
				NIM_BOOL LOC21;
				NIM_BOOL LOC22;
				NI TMP1959;
				NI TMP1960;
				NI TMP1962;
				LOC21 = 0;
				LOC22 = 0;
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				LOC22 = ((NU8)(path->data[i]) == (NU8)(46));
				if (!(LOC22)) goto LA23;
				TMP1959 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TMP1959)) > (NU)(path->Sup.len)) raiseIndexError();
				LOC22 = ((NU8)(path->data[(NI)(TMP1959)]) == (NU8)(46));
				LA23: ;
				LOC21 = LOC22;
				if (!(LOC21)) goto LA24;
				TMP1960 = addInt(i, ((NI) 2));
				if ((NU)((NI)(TMP1960)) > (NU)(path->Sup.len)) raiseIndexError();
				LOC21 = ((NU8)(path->data[(NI)(TMP1960)]) == (NU8)(47));
				LA24: ;
				if (!LOC21) goto LA25;
				nimln(346, "os.nim");
				result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TMP1961));
				nimln(347, "os.nim");
				TMP1962 = addInt(i, ((NI) 3));
				i = (NI)(TMP1962);
			}
			goto LA19;
			LA25: ;
			{
				NI TMP1963;
				nimln(348, "os.nim");
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				if (!((NU8)(path->data[i]) == (NU8)(47))) goto LA28;
				nimln(349, "os.nim");
				result = addChar(result, 92);
				nimln(350, "os.nim");
				TMP1963 = addInt(i, ((NI) 1));
				i = (NI)(TMP1963);
			}
			goto LA19;
			LA28: ;
			{
				NI TMP1964;
				nimln(352, "os.nim");
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				result = addChar(result, path->data[i]);
				nimln(353, "os.nim");
				TMP1964 = addInt(i, ((NI) 1));
				i = (NI)(TMP1964);
			}
			LA19: ;
		} LA18: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, putenv_124868)(NimStringDesc* key, NimStringDesc* val) {
	NI indx;
	NI16* k;
	NI16* v;
	nimfr("putEnv", "os.nim")
	nimln(1188, "os.nim");
	indx = findenvvar_124804(key);
	nimln(1189, "os.nim");
	{
		NimStringDesc* LOC5;
		if (!(((NI) 0) <= indx)) goto LA3;
		nimln(1190, "os.nim");
		if ((NU)(indx) >= (NU)(environment_124009->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = rawNewString(key->Sup.len + val->Sup.len + 1);
appendString(LOC5, key);
appendChar(LOC5, 61);
appendString(LOC5, val);
		asgnRefNoCycle((void**) (&environment_124009->data[indx]), LOC5);
	}
	goto LA1;
	LA3: ;
	{
		NimStringDesc* LOC7;
		NimStringDesc* LOC8;
		nimln(1192, "os.nim");
		LOC7 = 0;
		LOC7 = rawNewString(key->Sup.len + val->Sup.len + 1);
appendString(LOC7, key);
appendChar(LOC7, 61);
appendString(LOC7, val);
		environment_124009 = (TY13606*) incrSeq(&(environment_124009)->Sup, sizeof(NimStringDesc*));
		LOC8 = 0;
		LOC8 = environment_124009->data[environment_124009->Sup.len-1]; environment_124009->data[environment_124009->Sup.len-1] = copyStringRC1(LOC7);
		if (LOC8) nimGCunrefNoCycle(LOC8);
		nimln(1193, "os.nim");
		indx = (environment_124009 ? (environment_124009->Sup.len-1) : -1);
	}
	LA1: ;
	nimln(1199, "os.nim");
	k = newwidecstring_81205(key);
	nimln(1200, "os.nim");
	v = newwidecstring_81205(val);
	nimln(1201, "os.nim");
	{
		NI32 LOC11;
		NI32 LOC14;
		LOC11 = 0;
		LOC11 = Dl_105824(k, v);
		if (!(LOC11 == ((NI32) 0))) goto LA12;
		LOC14 = 0;
		LOC14 = oslasterror_115454();
		raiseoserror_115430(LOC14);
	}
	LA12: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, nosgetConfigDir)(void) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("getConfigDir", "os.nim")
{	result = 0;
	nimln(1634, "os.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = getenv_124843(((NimStringDesc*) &TMP2486));
	LOC1 = rawNewString(LOC2->Sup.len + 1);
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP1490));
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void) {
	NimStringDesc* result;
	NI16* res;
	NI32 L;
	nimfr("getCurrentDir", "os.nim")
	result = 0;
	nimln(488, "os.nim");
	res = newwidecstring_81021("", ((NI) 512));
	nimln(489, "os.nim");
	L = Dl_105810(((NI32) 512), res);
	nimln(490, "os.nim");
	{
		NI32 LOC5;
		if (!(L == ((NI32) 0))) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_115454();
		raiseoserror_115430(LOC5);
	}
	LA3: ;
	nimln(491, "os.nim");
	result = HEX24_81212(res, ((NI) (L)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringDesc* path) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("isRootDir", "os.nim")
	result = 0;
	nimln(624, "os.nim");
	LOC1 = 0;
	LOC1 = parentdirpos_119559(path);
	result = (LOC1 < ((NI) 0));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, existsenv_124858)(NimStringDesc* key) {
	NIM_BOOL result;
	nimfr("existsEnv", "os.nim")
{	result = 0;
	nimln(1177, "os.nim");
	{
		NCSTRING LOC3;
		LOC3 = 0;
		LOC3 = getenv(key->data);
		if (!!((LOC3 == NIM_NIL))) goto LA4;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA4: ;
	{
		NI LOC7;
		nimln(1178, "os.nim");
		LOC7 = 0;
		LOC7 = findenvvar_124804(key);
		result = (((NI) 0) <= LOC7);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosexistsDir)(NimStringDesc* dir) {
	NIM_BOOL result;
	NI32 a;
	NI16* LOC1;
	nimfr("existsDir", "os.nim")
	result = 0;
	nimln(358, "os.nim");
	LOC1 = 0;
	LOC1 = newwidecstring_81205(dir);
	a = Dl_106417(LOC1);
	nimln(404, "os.nim");
	{
		if (!!((a == ((NI32) -1)))) goto LA4;
		nimln(405, "os.nim");
		result = !(((NI32)(a & ((NI32) 16)) == ((NI32) 0)));
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(time_t, nosgetLastModificationTime)(NimStringDesc* file) {
	time_t result;
	Twin32finddata106219 f;
	NI h;
	NI64 LOC6;
	nimfr("getLastModificationTime", "os.nim")
	result = 0;
	memset((void*)(&f), 0, sizeof(f));
	nimln(441, "os.nim");
	h = findfirstfile_116416(file, (&f));
	nimln(442, "os.nim");
	{
		NI32 LOC5;
		if (!(h == ((NI) -1))) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_115454();
		raiseoserror_115430(LOC5);
	}
	LA3: ;
	nimln(443, "os.nim");
	LOC6 = 0;
	LOC6 = rdfiletime_106604(f.ftlastwritetime);
	result = wintimetounixtime_109688(LOC6);
	nimln(444, "os.nim");
	Dl_106404(h);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosfileNewer)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	time_t LOC1;
	time_t LOC2;
	NI64 LOC3;
	nimfr("fileNewer", "os.nim")
	result = 0;
	nimln(481, "os.nim");
	LOC1 = 0;
	LOC1 = nosgetLastModificationTime(a);
	LOC2 = 0;
	LOC2 = nosgetLastModificationTime(b);
	LOC3 = 0;
	LOC3 = ntDiffTime(LOC1, LOC2);
	result = (IL64(0) < LOC3);
	popFrame();
	return result;
}

N_NIMCALL(NI, openhandle_120429)(NimStringDesc* path, NIM_BOOL followsymlink) {
	NI result;
	NI32 flags;
	NI16* LOC5;
	nimfr("openHandle", "os.nim")
	result = 0;
	nimln(798, "os.nim");
	flags = ((NI32) 33554560);
	nimln(799, "os.nim");
	{
		if (!!(followsymlink)) goto LA3;
		nimln(800, "os.nim");
		flags = (NI32)(flags | ((NI32) 2097152));
	}
	LA3: ;
	nimln(803, "os.nim");
	nimln(804, "os.nim");
	LOC5 = 0;
	LOC5 = newwidecstring_81205(path);
	result = Dl_107317(LOC5, ((NI32) 0), ((NI32) 7), NIM_NIL, ((NI32) 3), flags, ((NI) 0));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nossameFile)(NimStringDesc* path1, NimStringDesc* path2) {
	NIM_BOOL result;
	NIM_BOOL success;
	NI f1;
	NI f2;
	NI32 lasterr;
	NI32 LOC21;
	NI32 LOC22;
	nimfr("sameFile", "os.nim")
	result = 0;
	nimln(824, "os.nim");
	success = NIM_TRUE;
	nimln(825, "os.nim");
	f1 = openhandle_120429(path1, NIM_TRUE);
	nimln(826, "os.nim");
	f2 = openhandle_120429(path2, NIM_TRUE);
	lasterr = 0;
	nimln(829, "os.nim");
	{
		NIM_BOOL LOC3;
		Tbyhandlefileinformation105250 fi1;
		Tbyhandlefileinformation105250 fi2;
		LOC3 = 0;
		LOC3 = !((f1 == ((NI) -1)));
		if (!(LOC3)) goto LA4;
		LOC3 = !((f2 == ((NI) -1)));
		LA4: ;
		if (!LOC3) goto LA5;
		memset((void*)(&fi1), 0, sizeof(fi1));
		memset((void*)(&fi2), 0, sizeof(fi2));
		nimln(832, "os.nim");
		{
			NIM_BOOL LOC9;
			NI32 LOC10;
			NI32 LOC12;
			NIM_BOOL LOC15;
			NIM_BOOL LOC16;
			LOC9 = 0;
			LOC10 = 0;
			LOC10 = Dl_106804(f1, (&fi1));
			LOC9 = !((LOC10 == ((NI32) 0)));
			if (!(LOC9)) goto LA11;
			nimln(833, "os.nim");
			LOC12 = 0;
			LOC12 = Dl_106804(f2, (&fi2));
			LOC9 = !((LOC12 == ((NI32) 0)));
			LA11: ;
			if (!LOC9) goto LA13;
			nimln(834, "os.nim");
			nimln(835, "os.nim");
			LOC15 = 0;
			nimln(834, "os.nim");
			LOC16 = 0;
			LOC16 = (fi1.dwvolumeserialnumber == fi2.dwvolumeserialnumber);
			if (!(LOC16)) goto LA17;
			nimln(835, "os.nim");
			LOC16 = (fi1.nfileindexhigh == fi2.nfileindexhigh);
			LA17: ;
			LOC15 = LOC16;
			if (!(LOC15)) goto LA18;
			nimln(836, "os.nim");
			LOC15 = (fi1.nfileindexlow == fi2.nfileindexlow);
			LA18: ;
			result = LOC15;
		}
		goto LA7;
		LA13: ;
		{
			nimln(838, "os.nim");
			lasterr = oslasterror_115454();
			nimln(839, "os.nim");
			success = NIM_FALSE;
		}
		LA7: ;
	}
	goto LA1;
	LA5: ;
	{
		nimln(841, "os.nim");
		lasterr = oslasterror_115454();
		nimln(842, "os.nim");
		success = NIM_FALSE;
	}
	LA1: ;
	nimln(844, "os.nim");
	LOC21 = 0;
	LOC21 = Dl_105424(f1);
	nimln(845, "os.nim");
	LOC22 = 0;
	LOC22 = Dl_105424(f2);
	nimln(847, "os.nim");
	{
		if (!!(success)) goto LA25;
		raiseoserror_115430(lasterr);
	}
	LA25: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, findexe_130417)(NimStringDesc* exe) {
	NimStringDesc* result;
	NimStringDesc* path;
	nimfr("findExe", "os.nim")
{	result = 0;
	nimln(1873, "os.nim");
	result = nosaddFileExt(exe, ((NimStringDesc*) &TMP10770));
	nimln(1874, "os.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nosexistsFile(result);
		if (!LOC3) goto LA4;
		goto BeforeRet;
	}
	LA4: ;
	nimln(1875, "os.nim");
	path = getenv_124843(((NimStringDesc*) &TMP10771));
	{
		NimStringDesc* candidate_130422;
		NI last_130607;
		candidate_130422 = 0;
		nimln(279, "strutils.nim");
		last_130607 = ((NI) 0);
		nimln(280, "strutils.nim");
		{
			if (!NIM_FALSE) goto LA9;
			failedassertimpl_88817(((NimStringDesc*) &TMP10772));
		}
		LA9: ;
		nimln(281, "strutils.nim");
		{
			if (!(((NI) 0) < (path ? path->Sup.len : 0))) goto LA13;
			{
				nimln(283, "strutils.nim");
				while (1) {
					NI first_130609;
					NI TMP10774;
					NimStringDesc* x;
					NI TMP10775;
					if (!(last_130607 <= (path ? path->Sup.len : 0))) goto LA16;
					nimln(284, "strutils.nim");
					first_130609 = last_130607;
					{
						nimln(285, "strutils.nim");
						while (1) {
							NIM_BOOL LOC19;
							NI TMP10773;
							LOC19 = 0;
							LOC19 = (last_130607 < (path ? path->Sup.len : 0));
							if (!(LOC19)) goto LA20;
							if ((NU)(last_130607) > (NU)(path->Sup.len)) raiseIndexError();
							LOC19 = !(((NU8)(path->data[last_130607]) == (NU8)(59)));
							LA20: ;
							if (!LOC19) goto LA18;
							TMP10773 = addInt(last_130607, ((NI) 1));
							last_130607 = (NI)(TMP10773);
						} LA18: ;
					}
					nimln(286, "strutils.nim");
					TMP10774 = subInt(last_130607, ((NI) 1));
					candidate_130422 = copyStrLast(path, first_130609, (NI)(TMP10774));
					nimln(1878, "os.nim");
					x = HEX2F_119492(candidate_130422, result);
					nimln(1881, "os.nim");
					{
						NIM_BOOL LOC23;
						LOC23 = 0;
						LOC23 = nosexistsFile(x);
						if (!LOC23) goto LA24;
						result = copyString(x);
						goto BeforeRet;
					}
					LA24: ;
					nimln(287, "strutils.nim");
					TMP10775 = addInt(last_130607, ((NI) 1));
					last_130607 = (NI)(TMP10775);
				} LA16: ;
			}
		}
		LA13: ;
	}
	nimln(1882, "os.nim");
	result = copyString(((NimStringDesc*) &TMP519));
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void) {
	nimfr("os", "os.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void) {
}

