/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Table164376 Table164376;
typedef struct Keyvaluepairseq164379 Keyvaluepairseq164379;
typedef struct Keyvaluepair164382 Keyvaluepair164382;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46747 Tcell46747;
typedef struct Tcellseq46763 Tcellseq46763;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46759 Tcellset46759;
typedef struct Tpagedesc46755 Tpagedesc46755;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Table313052 Table313052;
typedef struct Keyvaluepairseq313055 Keyvaluepairseq313055;
typedef struct Keyvaluepair313058 Keyvaluepair313058;
typedef struct TY314897 TY314897;
typedef struct Tindexentry314396 Tindexentry314396;
typedef struct Table314409 Table314409;
typedef struct Keyvaluepairseq314412 Keyvaluepairseq314412;
typedef struct Keyvaluepair314415 Keyvaluepair314415;
typedef struct Tnode192813 Tnode192813;
typedef struct Table383650 Table383650;
typedef struct Keyvaluepairseq383653 Keyvaluepairseq383653;
typedef struct Keyvaluepair383656 Keyvaluepair383656;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
typedef struct Ttype192849 Ttype192849;
typedef struct Tlineinfo164338 Tlineinfo164338;
typedef struct Tsym192843 Tsym192843;
typedef struct Tident168021 Tident168021;
typedef struct Tnodeseq192807 Tnodeseq192807;
typedef struct Tidobj168015 Tidobj168015;
typedef struct TNimObject TNimObject;
typedef struct Ttypeseq192845 Ttypeseq192845;
typedef struct Tloc192827 Tloc192827;
typedef struct Ropeobj162009 Ropeobj162009;
typedef struct Tscope192837 Tscope192837;
typedef struct TY192944 TY192944;
typedef struct Tstrtable192817 Tstrtable192817;
typedef struct Tsymseq192815 Tsymseq192815;
typedef struct Tlib192831 Tlib192831;
typedef struct Tinstantiation192833 Tinstantiation192833;
typedef struct Tlistentry130022 Tlistentry130022;
typedef struct TY192933 TY192933;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Table164376  {
Keyvaluepairseq164379* data;
NI counter;
};
struct Keyvaluepair164382 {
NI Field0;
NimStringDesc* Field1;
NI32 Field2;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46747  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46763  {
NI len;
NI cap;
Tcell46747** d;
};
struct  Tcellset46759  {
NI counter;
NI max;
Tpagedesc46755* head;
Tpagedesc46755** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46763 zct;
Tcellseq46763 decstack;
Tcellset46759 cycleroots;
Tcellseq46763 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
struct  Table313052  {
Keyvaluepairseq313055* data;
NI counter;
};
struct Keyvaluepair313058 {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct  Tindexentry314396  {
NimStringDesc* keyword;
NimStringDesc* link;
NimStringDesc* linktitle;
NimStringDesc* linkdesc;
};
struct  Table314409  {
Keyvaluepairseq314412* data;
NI counter;
};
struct Keyvaluepair314415 {
NI Field0;
Tindexentry314396 Field1;
TY314897* Field2;
};
struct  Table383650  {
Keyvaluepairseq383653* data;
NI counter;
};
struct Keyvaluepair383656 {
NI Field0;
NI64 Field1;
Tnode192813* Field2;
};
typedef NI TY27820[16];
struct  Tpagedesc46755  {
Tpagedesc46755* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tlineinfo164338  {
NI16 line;
NI16 col;
NI32 fileindex;
};
struct  Tnode192813  {
Ttype192849* typ;
Tlineinfo164338 info;
NU16 flags;
NU8 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym192843* sym;
} S4;
struct {Tident168021* ident;
} S5;
struct {Tnodeseq192807* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj168015  {
  TNimObject Sup;
NI id;
};
struct  Tloc192827  {
NU8 k;
NU8 s;
NU16 flags;
Ttype192849* t;
Ropeobj162009* r;
Ropeobj162009* heaproot;
};
struct  Ttype192849  {
  Tidobj168015 Sup;
NU8 kind;
NU8 callconv;
NU32 flags;
Ttypeseq192845* sons;
Tnode192813* n;
Tsym192843* owner;
Tsym192843* sym;
Tsym192843* destructor;
Tsym192843* deepcopy;
Tsym192843* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc192827 loc;
};
struct  Tstrtable192817  {
NI counter;
Tsymseq192815* data;
};
struct  Tsym192843  {
  Tidobj168015 Sup;
NU8 kind;
union{
struct {Ttypeseq192845* typeinstcache;
Tscope192837* typscope;
} S1;
struct {TY192944* procinstcache;
Tsym192843* gcunsafetyreason;
} S2;
struct {TY192944* usedgenerics;
Tstrtable192817 tab;
} S3;
struct {Tsym192843* guard;
} S4;
} kindU;
NU16 magic;
Ttype192849* typ;
Tident168021* name;
Tlineinfo164338 info;
Tsym192843* owner;
NU32 flags;
Tnode192813* ast;
NU32 options;
NI position;
NI offset;
Tloc192827 loc;
Tlib192831* annex;
Tnode192813* constraint;
};
struct  Tident168021  {
  Tidobj168015 Sup;
NimStringDesc* s;
Tident168021* next;
NI h;
};
struct  Ropeobj162009  {
  TNimObject Sup;
Ropeobj162009* left;
Ropeobj162009* right;
NI length;
NimStringDesc* data;
};
struct  Tscope192837  {
NI depthlevel;
Tstrtable192817 symbols;
Tnodeseq192807* usingsyms;
Tscope192837* parent;
};
struct  Tlistentry130022  {
  TNimObject Sup;
Tlistentry130022* prev;
Tlistentry130022* next;
};
struct  Tlib192831  {
  Tlistentry130022 Sup;
NU8 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj162009* name;
Tnode192813* path;
};
struct  Tinstantiation192833  {
Tsym192843* sym;
Ttypeseq192845* concretetypes;
TY192933* usedby;
};
struct Keyvaluepairseq164379 {
  TGenericSeq Sup;
  Keyvaluepair164382 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq313055 {
  TGenericSeq Sup;
  Keyvaluepair313058 data[SEQ_DECL_SIZE];
};
struct TY314897 {
  TGenericSeq Sup;
  Tindexentry314396 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq314412 {
  TGenericSeq Sup;
  Keyvaluepair314415 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq383653 {
  TGenericSeq Sup;
  Keyvaluepair383656 data[SEQ_DECL_SIZE];
};
struct Tnodeseq192807 {
  TGenericSeq Sup;
  Tnode192813* data[SEQ_DECL_SIZE];
};
struct Ttypeseq192845 {
  TGenericSeq Sup;
  Ttype192849* data[SEQ_DECL_SIZE];
};
struct TY192944 {
  TGenericSeq Sup;
  Tinstantiation192833* data[SEQ_DECL_SIZE];
};
struct Tsymseq192815 {
  TGenericSeq Sup;
  Tsym192843* data[SEQ_DECL_SIZE];
};
struct TY192933 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_157201)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_157211)(NI hcode);
static N_INLINE(NIM_BOOL, mustrehash_157313)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_87017)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, rightsize_157407)(NI count);
N_NIMCALL(NI, nextpoweroftwo_150531)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, nexttry_157420)(NI h, NI maxhash);
N_NIMCALL(NIM_BOOL, ispoweroftwo_150521)(NI x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP1193)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, rawget_164555)(Table164376 t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_131839)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, enlarge_164672)(Table164376* t);
static N_INLINE(NI, rawgetknownhc_164726)(Table164376 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_164752)(Table164376* t, Keyvaluepairseq164379** data, NimStringDesc* key, NI32 val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46747*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46747* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46763* s, Tcell46747* c);
N_NIMCALL(void, TMP5852)(void* p, NI op);
static N_INLINE(NI, rawget_314086)(Table313052 t, NimStringDesc* key, NI* hc);
N_NIMCALL(void, enlarge_314185)(Table313052* t);
static N_INLINE(NI, rawgetknownhc_314239)(Table313052 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_314265)(Table313052* t, Keyvaluepairseq313055** data, NimStringDesc* key, NI val, NI hc, NI h);
static N_INLINE(NI, rawget_316294)(Table314409 t, Tindexentry314396 key, NI* hc);
N_NIMCALL(NI, hash_314441)(Tindexentry314396 x);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_316309)(Tindexentry314396 x, Tindexentry314396 y);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_81604, TNimType* mt);
N_NIMCALL(void, TMP5999)(void* p, NI op);
N_NIMCALL(void, enlarge_317109)(Table314409* t);
static N_INLINE(NI, rawgetknownhc_317163)(Table314409 t, Tindexentry314396 key, NI hc);
N_NIMCALL(void, rawinsert_317198)(Table314409* t, Keyvaluepairseq314412** data, Tindexentry314396 key, TY314897* val, NI hc, NI h);
static N_INLINE(NI, rawget_384110)(Table383650 t, NI64 key, NI* hc);
static N_INLINE(NI, hash_131811)(NI64 x);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, enlarge_384198)(Table383650* t);
N_NIMCALL(void, TMP7589)(void* p, NI op);
static N_INLINE(NI, rawgetknownhc_384252)(Table383650 t, NI64 key, NI hc);
N_NIMCALL(void, rawinsert_384278)(Table383650* t, Keyvaluepairseq383653** data, NI64 key, Tnode192813* val, NI hc, NI h);
STRING_LITERAL(TMP736, "counter < length ", 17);
STRING_LITERAL(TMP1191, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_17042;
TNimType NTI164382; /* KeyValuePair */
extern TNimType NTI131021; /* THash */
extern TNimType NTI149; /* string */
extern TNimType NTI114; /* int32 */
TNimType NTI164379; /* KeyValuePairSeq */
TNimType NTI164376; /* Table */
extern TNimType NTI108; /* int */
extern Tgcheap48616 gch_48644;
TNimType NTI313058; /* KeyValuePair */
TNimType NTI313055; /* KeyValuePairSeq */
extern TNimType NTI314897; /* seq[TIndexEntry] */
TNimType NTI314415; /* KeyValuePair */
extern TNimType NTI314396; /* TIndexEntry */
TNimType NTI314412; /* KeyValuePairSeq */
TNimType NTI313052; /* Table */
TNimType NTI383656; /* KeyValuePair */
extern TNimType NTI5710; /* BiggestInt */
extern TNimType NTI192805; /* PNode */
TNimType NTI383653; /* KeyValuePairSeq */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(NIM_BOOL, isempty_157201)(NI hcode) {
	NIM_BOOL result;
	nimfr("isEmpty", "tables.nim")
	result = 0;
	nimln(89, "tables.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_157211)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "tables.nim")
	result = 0;
	nimln(92, "tables.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustrehash_157313)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP737;
	NI TMP738;
	NI TMP739;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(128, "tables.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_87017(((NimStringDesc*) &TMP736));
	}
	LA3: ;
	nimln(129, "tables.nim");
	LOC5 = 0;
	TMP737 = mulInt(length, ((NI) 2));
	TMP738 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP737) < (NI)(TMP738));
	if (LOC5) goto LA6;
	TMP739 = subInt(length, counter);
	LOC5 = ((NI)(TMP739) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (-2147483647 -1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rightsize_157407)(NI count) {
	NI result;
	NI TMP740;
	NI TMP741;
	NI TMP742;
	nimfr("rightSize", "tables.nim")
	result = 0;
	nimln(138, "tables.nim");
	TMP740 = mulInt(((NI) (count)), ((NI) 3));
	TMP741 = divInt(((NI)chckRange((NI)(TMP740), ((NI) (-2147483647 -1)), ((NI) 2147483647))), ((NI) 2));
	TMP742 = addInt(((NI)chckRange((NI)(TMP741), ((NI) (-2147483647 -1)), ((NI) 2147483647))), ((NI) 4));
	result = nextpoweroftwo_150531(((NI)chckRange((NI)(TMP742), ((NI) (-2147483647 -1)), ((NI) 2147483647))));
	popFrame();
	return result;
}

static N_INLINE(NI, nexttry_157420)(NI h, NI maxhash) {
	NI result;
	NI TMP743;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(141, "tables.nim");
	TMP743 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP743) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP1193)(void* p, NI op) {
	Keyvaluepairseq164379* a;
	NI LOC1;
	a = (Keyvaluepairseq164379*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_164368)(NI initialsize, Table164376* Result) {
	nimfr("initTable", "tables.nim")
	nimln(313, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_150521(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_87017(((NimStringDesc*) &TMP1191));
	}
	LA4: ;
	nimln(314, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(315, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq164379*) newSeq((&NTI164379), ((NI)chckRange(initialsize, ((NI) 0), ((NI) 2147483647)))));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rawget_164555)(Table164376 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TMP1209;
	nimfr("rawGet", "tables.nim")
{	result = 0;
	nimln(156, "tables.nim");
	(*hc) = hash_131839(key);
	nimln(157, "tables.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(158, "tables.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(144, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(153, "tables.nim");
	TMP1209 = subInt(((NI) -1), h);
	result = (NI)(TMP1209);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_164543)(Table164376 t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	hc = 0;
	nimln(216, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_164555(t, key, (&hc));
	result = (((NI) 0) <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NI32, HEX5BHEX5D_164586)(Table164376 t, NimStringDesc* key) {
	NI32 result;
	NI hc;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	hc = 0;
	nimln(190, "tables.nim");
	index = rawget_164555(t, key, (&hc));
	nimln(191, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawgetknownhc_164726)(Table164376 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TMP1213;
	nimfr("rawGetKnownHC", "tables.nim")
{	result = 0;
	nimln(144, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(153, "tables.nim");
	TMP1213 = subInt(((NI) -1), h);
	result = (NI)(TMP1213);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(Tcell46747*, usrtocell_50246)(void* usr) {
	Tcell46747* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46747*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46747))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46747* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46747* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_164752)(Table164376* t, Keyvaluepairseq164379** data, NimStringDesc* key, NI32 val, NI hc, NI h) {
	NimStringDesc* LOC1;
	nimfr("rawInsert", "tables.nim")
	nimln(171, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(172, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field2 = val;
	nimln(173, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_164672)(Table164376* t) {
	Keyvaluepairseq164379* n;
	NI TMP1212;
	Keyvaluepairseq164379* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(224, "tables.nim");
	TMP1212 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq164379*) newSeq((&NTI164379), ((NI)chckRange((NI)(TMP1212), ((NI) 0), ((NI) 2147483647))));
	nimln(225, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_164724;
		NI HEX3Atmp_164778;
		NI res_164781;
		i_164724 = 0;
		HEX3Atmp_164778 = 0;
		nimln(226, "tables.nim");
		HEX3Atmp_164778 = (n ? (n->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_164781 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP1215;
				if (!(res_164781 <= HEX3Atmp_164778)) goto LA4;
				nimln(1600, "system.nim");
				i_164724 = res_164781;
				nimln(227, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP1214;
					if ((NU)(i_164724) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_157211(n->data[i_164724].Field0);
					if (!LOC7) goto LA8;
					nimln(228, "tables.nim");
					if ((NU)(i_164724) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_164724) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_164726((*t), n->data[i_164724].Field1, n->data[i_164724].Field0);
					TMP1214 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP1214);
					nimln(229, "tables.nim");
					if ((NU)(i_164724) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_164724) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_164724) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_164752(t, (&(*t).data), n->data[i_164724].Field1, n->data[i_164724].Field2, n->data[i_164724].Field0, j);
				}
				LA8: ;
				nimln(1614, "system.nim");
				TMP1215 = addInt(res_164781, ((NI) 1));
				res_164781 = (NI)(TMP1215);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_164635)(Table164376* t, NimStringDesc* key, NI32 val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(248, "tables.nim");
	index = rawget_164555((*t), key, (&hc));
	nimln(249, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = val;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP1216;
		NI TMP1217;
		nimln(239, "tables.nim");
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = mustrehash_157313(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(240, "tables.nim");
			enlarge_164672(t);
			nimln(241, "tables.nim");
			index = rawgetknownhc_164726((*t), key, hc);
		}
		LA9: ;
		nimln(242, "tables.nim");
		TMP1216 = subInt(((NI) -1), index);
		index = (NI)(TMP1216);
		nimln(243, "tables.nim");
		rawinsert_164752(t, (&(*t).data), key, val, hc, index);
		nimln(244, "tables.nim");
		TMP1217 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP1217);
	}
	LA1: ;
	popFrame();
}
N_NIMCALL(void, TMP5852)(void* p, NI op) {
	Keyvaluepairseq313055* a;
	NI LOC1;
	a = (Keyvaluepairseq313055*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, inittable_313116)(NI initialsize, Table313052* Result) {
	nimfr("initTable", "tables.nim")
	nimln(313, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_150521(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_87017(((NimStringDesc*) &TMP1191));
	}
	LA4: ;
	nimln(314, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(315, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq313055*) newSeq((&NTI313055), ((NI)chckRange(initialsize, ((NI) 0), ((NI) 2147483647)))));
	popFrame();
}

static N_INLINE(NI, rawget_314086)(Table313052 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TMP5910;
	nimfr("rawGet", "tables.nim")
{	result = 0;
	nimln(156, "tables.nim");
	(*hc) = hash_131839(key);
	nimln(157, "tables.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(158, "tables.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(144, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(153, "tables.nim");
	TMP5910 = subInt(((NI) -1), h);
	result = (NI)(TMP5910);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, haskey_314074)(Table313052 t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	hc = 0;
	nimln(216, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_314086(t, key, (&hc));
	result = (((NI) 0) <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX5BHEX5D_314117)(Table313052 t, NimStringDesc* key) {
	NI result;
	NI hc;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	hc = 0;
	nimln(190, "tables.nim");
	index = rawget_314086(t, key, (&hc));
	nimln(191, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawgetknownhc_314239)(Table313052 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TMP5914;
	nimfr("rawGetKnownHC", "tables.nim")
{	result = 0;
	nimln(144, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(153, "tables.nim");
	TMP5914 = subInt(((NI) -1), h);
	result = (NI)(TMP5914);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_314265)(Table313052* t, Keyvaluepairseq313055** data, NimStringDesc* key, NI val, NI hc, NI h) {
	NimStringDesc* LOC1;
	nimfr("rawInsert", "tables.nim")
	nimln(171, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(172, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field2 = val;
	nimln(173, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_314185)(Table313052* t) {
	Keyvaluepairseq313055* n;
	NI TMP5913;
	Keyvaluepairseq313055* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(224, "tables.nim");
	TMP5913 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq313055*) newSeq((&NTI313055), ((NI)chckRange((NI)(TMP5913), ((NI) 0), ((NI) 2147483647))));
	nimln(225, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_314237;
		NI HEX3Atmp_314291;
		NI res_314294;
		i_314237 = 0;
		HEX3Atmp_314291 = 0;
		nimln(226, "tables.nim");
		HEX3Atmp_314291 = (n ? (n->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_314294 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP5916;
				if (!(res_314294 <= HEX3Atmp_314291)) goto LA4;
				nimln(1600, "system.nim");
				i_314237 = res_314294;
				nimln(227, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP5915;
					if ((NU)(i_314237) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_157211(n->data[i_314237].Field0);
					if (!LOC7) goto LA8;
					nimln(228, "tables.nim");
					if ((NU)(i_314237) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_314237) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_314239((*t), n->data[i_314237].Field1, n->data[i_314237].Field0);
					TMP5915 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP5915);
					nimln(229, "tables.nim");
					if ((NU)(i_314237) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_314237) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_314237) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_314265(t, (&(*t).data), n->data[i_314237].Field1, n->data[i_314237].Field2, n->data[i_314237].Field0, j);
				}
				LA8: ;
				nimln(1614, "system.nim");
				TMP5916 = addInt(res_314294, ((NI) 1));
				res_314294 = (NI)(TMP5916);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_314148)(Table313052* t, NimStringDesc* key, NI val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(248, "tables.nim");
	index = rawget_314086((*t), key, (&hc));
	nimln(249, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = val;
	}
	goto LA1;
	LA3: ;
	{
		NI TMP5917;
		NI TMP5918;
		nimln(239, "tables.nim");
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = mustrehash_157313(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(240, "tables.nim");
			enlarge_314185(t);
			nimln(241, "tables.nim");
			index = rawgetknownhc_314239((*t), key, hc);
		}
		LA9: ;
		nimln(242, "tables.nim");
		TMP5917 = subInt(((NI) -1), index);
		index = (NI)(TMP5917);
		nimln(243, "tables.nim");
		rawinsert_314265(t, (&(*t).data), key, val, hc, index);
		nimln(244, "tables.nim");
		TMP5918 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP5918);
	}
	LA1: ;
	popFrame();
}

static N_INLINE(NI, rawget_316294)(Table314409 t, Tindexentry314396 key, NI* hc) {
	NI result;
	NI h;
	NI TMP5981;
	nimfr("rawGet", "tables.nim")
{	result = 0;
	nimln(156, "tables.nim");
	(*hc) = hash_314441(key);
	nimln(157, "tables.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(158, "tables.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(144, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = HEX3DHEX3D_316309(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(153, "tables.nim");
	TMP5981 = subInt(((NI) -1), h);
	result = (NI)(TMP5981);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY314897*, HEX5BHEX5D_316282)(Table314409 t, Tindexentry314396 key) {
	TY314897* result;
	NI hc;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	hc = 0;
	nimln(190, "tables.nim");
	index = rawget_316294(t, key, (&hc));
	nimln(191, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		genericSeqAssign((&result), t.data->data[index].Field2, (&NTI314897));
	}
	LA3: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP5999)(void* p, NI op) {
	Keyvaluepairseq314412* a;
	NI LOC1;
	a = (Keyvaluepairseq314412*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1.keyword, op);
	nimGCvisit((void*)a->data[LOC1].Field1.link, op);
	nimGCvisit((void*)a->data[LOC1].Field1.linktitle, op);
	nimGCvisit((void*)a->data[LOC1].Field1.linkdesc, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_316724)(NI initialsize, Table314409* Result) {
	nimfr("initTable", "tables.nim")
	nimln(313, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_150521(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_87017(((NimStringDesc*) &TMP1191));
	}
	LA4: ;
	nimln(314, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(315, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq314412*) newSeq((&NTI314412), ((NI)chckRange(initialsize, ((NI) 0), ((NI) 2147483647)))));
	popFrame();
}

N_NIMCALL(NI, len_317060)(Table314409 t) {
	NI result;
	nimfr("len", "tables.nim")
	result = 0;
	nimln(96, "tables.nim");
	result = t.counter;
	popFrame();
	return result;
}

static N_INLINE(NI, rawgetknownhc_317163)(Table314409 t, Tindexentry314396 key, NI hc) {
	NI result;
	NI h;
	NI TMP6001;
	nimfr("rawGetKnownHC", "tables.nim")
{	result = 0;
	nimln(144, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = HEX3DHEX3D_316309(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(153, "tables.nim");
	TMP6001 = subInt(((NI) -1), h);
	result = (NI)(TMP6001);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_317198)(Table314409* t, Keyvaluepairseq314412** data, Tindexentry314396 key, TY314897* val, NI hc, NI h) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(171, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1.keyword; (*data)->data[h].Field1.keyword = copyStringRC1(key.keyword);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	LOC2 = 0;
	LOC2 = (*data)->data[h].Field1.link; (*data)->data[h].Field1.link = copyStringRC1(key.link);
	if (LOC2) nimGCunrefNoCycle(LOC2);
	LOC3 = 0;
	LOC3 = (*data)->data[h].Field1.linktitle; (*data)->data[h].Field1.linktitle = copyStringRC1(key.linktitle);
	if (LOC3) nimGCunrefNoCycle(LOC3);
	LOC4 = 0;
	LOC4 = (*data)->data[h].Field1.linkdesc; (*data)->data[h].Field1.linkdesc = copyStringRC1(key.linkdesc);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(172, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	genericSeqAssign((&(*data)->data[h].Field2), val, (&NTI314897));
	nimln(173, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_317109)(Table314409* t) {
	Keyvaluepairseq314412* n;
	NI TMP6000;
	Keyvaluepairseq314412* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(224, "tables.nim");
	TMP6000 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq314412*) newSeq((&NTI314412), ((NI)chckRange((NI)(TMP6000), ((NI) 0), ((NI) 2147483647))));
	nimln(225, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_317161;
		NI HEX3Atmp_317224;
		NI res_317227;
		i_317161 = 0;
		HEX3Atmp_317224 = 0;
		nimln(226, "tables.nim");
		HEX3Atmp_317224 = (n ? (n->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_317227 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP6003;
				if (!(res_317227 <= HEX3Atmp_317224)) goto LA4;
				nimln(1600, "system.nim");
				i_317161 = res_317227;
				nimln(227, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP6002;
					if ((NU)(i_317161) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_157211(n->data[i_317161].Field0);
					if (!LOC7) goto LA8;
					nimln(228, "tables.nim");
					if ((NU)(i_317161) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_317161) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_317163((*t), n->data[i_317161].Field1, n->data[i_317161].Field0);
					TMP6002 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP6002);
					nimln(229, "tables.nim");
					if ((NU)(i_317161) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_317161) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_317161) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_317198(t, (&(*t).data), n->data[i_317161].Field1, n->data[i_317161].Field2, n->data[i_317161].Field0, j);
				}
				LA8: ;
				nimln(1614, "system.nim");
				TMP6003 = addInt(res_317227, ((NI) 1));
				res_317227 = (NI)(TMP6003);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_317072)(Table314409* t, Tindexentry314396 key, TY314897* val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(248, "tables.nim");
	index = rawget_316294((*t), key, (&hc));
	nimln(249, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		genericSeqAssign((&(*t).data->data[index].Field2), val, (&NTI314897));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP6004;
		NI TMP6005;
		nimln(239, "tables.nim");
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = mustrehash_157313(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(240, "tables.nim");
			enlarge_317109(t);
			nimln(241, "tables.nim");
			index = rawgetknownhc_317163((*t), key, hc);
		}
		LA9: ;
		nimln(242, "tables.nim");
		TMP6004 = subInt(((NI) -1), index);
		index = (NI)(TMP6004);
		nimln(243, "tables.nim");
		rawinsert_317198(t, (&(*t).data), key, val, hc, index);
		nimln(244, "tables.nim");
		TMP6005 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP6005);
	}
	LA1: ;
	popFrame();
}

static N_INLINE(NI, hash_131811)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(111, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, rawget_384110)(Table383650 t, NI64 key, NI* hc) {
	NI result;
	NI h;
	NI TMP7584;
	nimfr("rawGet", "tables.nim")
{	result = 0;
	nimln(156, "tables.nim");
	(*hc) = hash_131811(key);
	nimln(157, "tables.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(158, "tables.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(144, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field1 == key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(153, "tables.nim");
	TMP7584 = subInt(((NI) -1), h);
	result = (NI)(TMP7584);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Tnode192813*, HEX5BHEX5D_384098)(Table383650 t, NI64 key) {
	Tnode192813* result;
	NI hc;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	hc = 0;
	nimln(190, "tables.nim");
	index = rawget_384110(t, key, (&hc));
	nimln(191, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index].Field2;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46747* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46747* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, TMP7589)(void* p, NI op) {
	Keyvaluepairseq383653* a;
	NI LOC1;
	a = (Keyvaluepairseq383653*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

static N_INLINE(NI, rawgetknownhc_384252)(Table383650 t, NI64 key, NI hc) {
	NI result;
	NI h;
	NI TMP7590;
	nimfr("rawGetKnownHC", "tables.nim")
{	result = 0;
	nimln(144, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(145, "tables.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_157211(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(150, "tables.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field1 == key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(151, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(152, "tables.nim");
			h = nexttry_157420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(153, "tables.nim");
	TMP7590 = subInt(((NI) -1), h);
	result = (NI)(TMP7590);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_384278)(Table383650* t, Keyvaluepairseq383653** data, NI64 key, Tnode192813* val, NI hc, NI h) {
	nimfr("rawInsert", "tables.nim")
	nimln(171, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field1 = key;
	nimln(172, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	asgnRefNoCycle((void**) (&(*data)->data[h].Field2), val);
	nimln(173, "tables.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_384198)(Table383650* t) {
	Keyvaluepairseq383653* n;
	NI TMP7587;
	Keyvaluepairseq383653* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(224, "tables.nim");
	TMP7587 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq383653*) newSeq((&NTI383653), ((NI)chckRange((NI)(TMP7587), ((NI) 0), ((NI) 2147483647))));
	nimln(225, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_384250;
		NI HEX3Atmp_384304;
		NI res_384307;
		i_384250 = 0;
		HEX3Atmp_384304 = 0;
		nimln(226, "tables.nim");
		HEX3Atmp_384304 = (n ? (n->Sup.len-1) : -1);
		nimln(1598, "system.nim");
		res_384307 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP7592;
				if (!(res_384307 <= HEX3Atmp_384304)) goto LA4;
				nimln(1600, "system.nim");
				i_384250 = res_384307;
				nimln(227, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP7591;
					if ((NU)(i_384250) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_157211(n->data[i_384250].Field0);
					if (!LOC7) goto LA8;
					nimln(228, "tables.nim");
					if ((NU)(i_384250) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_384250) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_384252((*t), n->data[i_384250].Field1, n->data[i_384250].Field0);
					TMP7591 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP7591);
					nimln(229, "tables.nim");
					if ((NU)(i_384250) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_384250) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_384250) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_384278(t, (&(*t).data), n->data[i_384250].Field1, n->data[i_384250].Field2, n->data[i_384250].Field0, j);
				}
				LA8: ;
				nimln(1614, "system.nim");
				TMP7592 = addInt(res_384307, ((NI) 1));
				res_384307 = (NI)(TMP7592);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_384161)(Table383650* t, NI64 key, Tnode192813* val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(248, "tables.nim");
	index = rawget_384110((*t), key, (&hc));
	nimln(249, "tables.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*t).data->data[index].Field2), val);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP7593;
		NI TMP7594;
		nimln(239, "tables.nim");
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = mustrehash_157313(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(240, "tables.nim");
			enlarge_384198(t);
			nimln(241, "tables.nim");
			index = rawgetknownhc_384252((*t), key, hc);
		}
		LA9: ;
		nimln(242, "tables.nim");
		TMP7593 = subInt(((NI) -1), index);
		index = (NI)(TMP7593);
		nimln(243, "tables.nim");
		rawinsert_384278(t, (&(*t).data), key, val, hc, index);
		nimln(244, "tables.nim");
		TMP7594 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP7594);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, inittable_384469)(NI initialsize, Table383650* Result) {
	nimfr("initTable", "tables.nim")
	nimln(313, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_150521(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_87017(((NimStringDesc*) &TMP1191));
	}
	LA4: ;
	nimln(314, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(315, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq383653*) newSeq((&NTI383653), ((NI)chckRange(initialsize, ((NI) 0), ((NI) 2147483647)))));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void) {
static TNimNode* TMP1192[3];
static TNimNode* TMP1194[2];
static TNimNode* TMP5851[3];
static TNimNode* TMP5998[3];
static TNimNode* TMP6263[2];
static TNimNode* TMP7588[3];
static TNimNode TMP734[22];
NTI164382.size = sizeof(Keyvaluepair164382);
NTI164382.kind = 18;
NTI164382.base = 0;
NTI164382.flags = 2;
TMP1192[0] = &TMP734[1];
TMP734[1].kind = 1;
TMP734[1].offset = offsetof(Keyvaluepair164382, Field0);
TMP734[1].typ = (&NTI131021);
TMP734[1].name = "Field0";
TMP1192[1] = &TMP734[2];
TMP734[2].kind = 1;
TMP734[2].offset = offsetof(Keyvaluepair164382, Field1);
TMP734[2].typ = (&NTI149);
TMP734[2].name = "Field1";
TMP1192[2] = &TMP734[3];
TMP734[3].kind = 1;
TMP734[3].offset = offsetof(Keyvaluepair164382, Field2);
TMP734[3].typ = (&NTI114);
TMP734[3].name = "Field2";
TMP734[0].len = 3; TMP734[0].kind = 2; TMP734[0].sons = &TMP1192[0];
NTI164382.node = &TMP734[0];
NTI164379.size = sizeof(Keyvaluepairseq164379*);
NTI164379.kind = 24;
NTI164379.base = (&NTI164382);
NTI164379.flags = 2;
NTI164379.marker = TMP1193;
NTI164376.size = sizeof(Table164376);
NTI164376.kind = 18;
NTI164376.base = 0;
NTI164376.flags = 2;
TMP1194[0] = &TMP734[5];
TMP734[5].kind = 1;
TMP734[5].offset = offsetof(Table164376, data);
TMP734[5].typ = (&NTI164379);
TMP734[5].name = "data";
TMP1194[1] = &TMP734[6];
TMP734[6].kind = 1;
TMP734[6].offset = offsetof(Table164376, counter);
TMP734[6].typ = (&NTI108);
TMP734[6].name = "counter";
TMP734[4].len = 2; TMP734[4].kind = 2; TMP734[4].sons = &TMP1194[0];
NTI164376.node = &TMP734[4];
NTI313058.size = sizeof(Keyvaluepair313058);
NTI313058.kind = 18;
NTI313058.base = 0;
NTI313058.flags = 2;
TMP5851[0] = &TMP734[8];
TMP734[8].kind = 1;
TMP734[8].offset = offsetof(Keyvaluepair313058, Field0);
TMP734[8].typ = (&NTI131021);
TMP734[8].name = "Field0";
TMP5851[1] = &TMP734[9];
TMP734[9].kind = 1;
TMP734[9].offset = offsetof(Keyvaluepair313058, Field1);
TMP734[9].typ = (&NTI149);
TMP734[9].name = "Field1";
TMP5851[2] = &TMP734[10];
TMP734[10].kind = 1;
TMP734[10].offset = offsetof(Keyvaluepair313058, Field2);
TMP734[10].typ = (&NTI108);
TMP734[10].name = "Field2";
TMP734[7].len = 3; TMP734[7].kind = 2; TMP734[7].sons = &TMP5851[0];
NTI313058.node = &TMP734[7];
NTI313055.size = sizeof(Keyvaluepairseq313055*);
NTI313055.kind = 24;
NTI313055.base = (&NTI313058);
NTI313055.flags = 2;
NTI313055.marker = TMP5852;
NTI314415.size = sizeof(Keyvaluepair314415);
NTI314415.kind = 18;
NTI314415.base = 0;
NTI314415.flags = 2;
TMP5998[0] = &TMP734[12];
TMP734[12].kind = 1;
TMP734[12].offset = offsetof(Keyvaluepair314415, Field0);
TMP734[12].typ = (&NTI131021);
TMP734[12].name = "Field0";
TMP5998[1] = &TMP734[13];
TMP734[13].kind = 1;
TMP734[13].offset = offsetof(Keyvaluepair314415, Field1);
TMP734[13].typ = (&NTI314396);
TMP734[13].name = "Field1";
TMP5998[2] = &TMP734[14];
TMP734[14].kind = 1;
TMP734[14].offset = offsetof(Keyvaluepair314415, Field2);
TMP734[14].typ = (&NTI314897);
TMP734[14].name = "Field2";
TMP734[11].len = 3; TMP734[11].kind = 2; TMP734[11].sons = &TMP5998[0];
NTI314415.node = &TMP734[11];
NTI314412.size = sizeof(Keyvaluepairseq314412*);
NTI314412.kind = 24;
NTI314412.base = (&NTI314415);
NTI314412.flags = 2;
NTI314412.marker = TMP5999;
NTI313052.size = sizeof(Table313052);
NTI313052.kind = 18;
NTI313052.base = 0;
NTI313052.flags = 2;
TMP6263[0] = &TMP734[16];
TMP734[16].kind = 1;
TMP734[16].offset = offsetof(Table313052, data);
TMP734[16].typ = (&NTI313055);
TMP734[16].name = "data";
TMP6263[1] = &TMP734[17];
TMP734[17].kind = 1;
TMP734[17].offset = offsetof(Table313052, counter);
TMP734[17].typ = (&NTI108);
TMP734[17].name = "counter";
TMP734[15].len = 2; TMP734[15].kind = 2; TMP734[15].sons = &TMP6263[0];
NTI313052.node = &TMP734[15];
NTI383656.size = sizeof(Keyvaluepair383656);
NTI383656.kind = 18;
NTI383656.base = 0;
NTI383656.flags = 2;
TMP7588[0] = &TMP734[19];
TMP734[19].kind = 1;
TMP734[19].offset = offsetof(Keyvaluepair383656, Field0);
TMP734[19].typ = (&NTI131021);
TMP734[19].name = "Field0";
TMP7588[1] = &TMP734[20];
TMP734[20].kind = 1;
TMP734[20].offset = offsetof(Keyvaluepair383656, Field1);
TMP734[20].typ = (&NTI5710);
TMP734[20].name = "Field1";
TMP7588[2] = &TMP734[21];
TMP734[21].kind = 1;
TMP734[21].offset = offsetof(Keyvaluepair383656, Field2);
TMP734[21].typ = (&NTI192805);
TMP734[21].name = "Field2";
TMP734[18].len = 3; TMP734[18].kind = 2; TMP734[18].sons = &TMP7588[0];
NTI383656.node = &TMP734[18];
NTI383653.size = sizeof(Keyvaluepairseq383653*);
NTI383653.kind = 24;
NTI383653.base = (&NTI383656);
NTI383653.flags = 2;
NTI383653.marker = TMP7589;
}

